// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/public/value.proto

package zetasql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValueProto struct {
	// Types that are valid to be assigned to Value:
	//	*ValueProto_Int32Value
	//	*ValueProto_Int64Value
	//	*ValueProto_Uint32Value
	//	*ValueProto_Uint64Value
	//	*ValueProto_BoolValue
	//	*ValueProto_FloatValue
	//	*ValueProto_DoubleValue
	//	*ValueProto_StringValue
	//	*ValueProto_BytesValue
	//	*ValueProto_DateValue
	//	*ValueProto_EnumValue
	//	*ValueProto_ArrayValue
	//	*ValueProto_StructValue
	//	*ValueProto_ProtoValue
	//	*ValueProto_TimestampValue
	//	*ValueProto_DatetimeValue
	//	*ValueProto_TimeValue
	//	*ValueProto_GeographyValue
	//	*ValueProto_NumericValue
	//	*ValueProto_BignumericValue
	//	*ValueProto_JsonValue
	//	*ValueProto_X_ValueProto_SwitchMustHaveADefault
	Value                isValueProto_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ValueProto) Reset()         { *m = ValueProto{} }
func (m *ValueProto) String() string { return proto.CompactTextString(m) }
func (*ValueProto) ProtoMessage()    {}
func (*ValueProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5510b35f888f5c, []int{0}
}

func (m *ValueProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueProto.Unmarshal(m, b)
}
func (m *ValueProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueProto.Marshal(b, m, deterministic)
}
func (m *ValueProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueProto.Merge(m, src)
}
func (m *ValueProto) XXX_Size() int {
	return xxx_messageInfo_ValueProto.Size(m)
}
func (m *ValueProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueProto.DiscardUnknown(m)
}

var xxx_messageInfo_ValueProto proto.InternalMessageInfo

type isValueProto_Value interface {
	isValueProto_Value()
}

type ValueProto_Int32Value struct {
	Int32Value int32 `protobuf:"varint,1,opt,name=int32_value,json=int32Value,oneof"`
}

type ValueProto_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,oneof"`
}

type ValueProto_Uint32Value struct {
	Uint32Value uint32 `protobuf:"varint,3,opt,name=uint32_value,json=uint32Value,oneof"`
}

type ValueProto_Uint64Value struct {
	Uint64Value uint64 `protobuf:"varint,4,opt,name=uint64_value,json=uint64Value,oneof"`
}

type ValueProto_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,oneof"`
}

type ValueProto_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,oneof"`
}

type ValueProto_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,7,opt,name=double_value,json=doubleValue,oneof"`
}

type ValueProto_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,oneof"`
}

type ValueProto_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,oneof"`
}

type ValueProto_DateValue struct {
	DateValue int32 `protobuf:"varint,10,opt,name=date_value,json=dateValue,oneof"`
}

type ValueProto_EnumValue struct {
	EnumValue int32 `protobuf:"varint,12,opt,name=enum_value,json=enumValue,oneof"`
}

type ValueProto_ArrayValue struct {
	ArrayValue *ValueProto_Array `protobuf:"bytes,13,opt,name=array_value,json=arrayValue,oneof"`
}

type ValueProto_StructValue struct {
	StructValue *ValueProto_Struct `protobuf:"bytes,14,opt,name=struct_value,json=structValue,oneof"`
}

type ValueProto_ProtoValue struct {
	ProtoValue []byte `protobuf:"bytes,15,opt,name=proto_value,json=protoValue,oneof"`
}

type ValueProto_TimestampValue struct {
	TimestampValue *timestamp.Timestamp `protobuf:"bytes,16,opt,name=timestamp_value,json=timestampValue,oneof"`
}

type ValueProto_DatetimeValue struct {
	DatetimeValue *ValueProto_Datetime `protobuf:"bytes,17,opt,name=datetime_value,json=datetimeValue,oneof"`
}

type ValueProto_TimeValue struct {
	TimeValue int64 `protobuf:"varint,18,opt,name=time_value,json=timeValue,oneof"`
}

type ValueProto_GeographyValue struct {
	GeographyValue []byte `protobuf:"bytes,19,opt,name=geography_value,json=geographyValue,oneof"`
}

type ValueProto_NumericValue struct {
	NumericValue []byte `protobuf:"bytes,20,opt,name=numeric_value,json=numericValue,oneof"`
}

type ValueProto_BignumericValue struct {
	BignumericValue []byte `protobuf:"bytes,21,opt,name=bignumeric_value,json=bignumericValue,oneof"`
}

type ValueProto_JsonValue struct {
	JsonValue string `protobuf:"bytes,23,opt,name=json_value,json=jsonValue,oneof"`
}

type ValueProto_X_ValueProto_SwitchMustHaveADefault struct {
	X_ValueProto_SwitchMustHaveADefault bool `protobuf:"varint,255,opt,name=__ValueProto__switch_must_have_a_default,json=ValueProtoSwitchMustHaveADefault,oneof"`
}

func (*ValueProto_Int32Value) isValueProto_Value() {}

func (*ValueProto_Int64Value) isValueProto_Value() {}

func (*ValueProto_Uint32Value) isValueProto_Value() {}

func (*ValueProto_Uint64Value) isValueProto_Value() {}

func (*ValueProto_BoolValue) isValueProto_Value() {}

func (*ValueProto_FloatValue) isValueProto_Value() {}

func (*ValueProto_DoubleValue) isValueProto_Value() {}

func (*ValueProto_StringValue) isValueProto_Value() {}

func (*ValueProto_BytesValue) isValueProto_Value() {}

func (*ValueProto_DateValue) isValueProto_Value() {}

func (*ValueProto_EnumValue) isValueProto_Value() {}

func (*ValueProto_ArrayValue) isValueProto_Value() {}

func (*ValueProto_StructValue) isValueProto_Value() {}

func (*ValueProto_ProtoValue) isValueProto_Value() {}

func (*ValueProto_TimestampValue) isValueProto_Value() {}

func (*ValueProto_DatetimeValue) isValueProto_Value() {}

func (*ValueProto_TimeValue) isValueProto_Value() {}

func (*ValueProto_GeographyValue) isValueProto_Value() {}

func (*ValueProto_NumericValue) isValueProto_Value() {}

func (*ValueProto_BignumericValue) isValueProto_Value() {}

func (*ValueProto_JsonValue) isValueProto_Value() {}

func (*ValueProto_X_ValueProto_SwitchMustHaveADefault) isValueProto_Value() {}

func (m *ValueProto) GetValue() isValueProto_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ValueProto) GetInt32Value() int32 {
	if x, ok := m.GetValue().(*ValueProto_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *ValueProto) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*ValueProto_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *ValueProto) GetUint32Value() uint32 {
	if x, ok := m.GetValue().(*ValueProto_Uint32Value); ok {
		return x.Uint32Value
	}
	return 0
}

func (m *ValueProto) GetUint64Value() uint64 {
	if x, ok := m.GetValue().(*ValueProto_Uint64Value); ok {
		return x.Uint64Value
	}
	return 0
}

func (m *ValueProto) GetBoolValue() bool {
	if x, ok := m.GetValue().(*ValueProto_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *ValueProto) GetFloatValue() float32 {
	if x, ok := m.GetValue().(*ValueProto_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *ValueProto) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*ValueProto_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *ValueProto) GetStringValue() string {
	if x, ok := m.GetValue().(*ValueProto_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *ValueProto) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*ValueProto_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *ValueProto) GetDateValue() int32 {
	if x, ok := m.GetValue().(*ValueProto_DateValue); ok {
		return x.DateValue
	}
	return 0
}

func (m *ValueProto) GetEnumValue() int32 {
	if x, ok := m.GetValue().(*ValueProto_EnumValue); ok {
		return x.EnumValue
	}
	return 0
}

func (m *ValueProto) GetArrayValue() *ValueProto_Array {
	if x, ok := m.GetValue().(*ValueProto_ArrayValue); ok {
		return x.ArrayValue
	}
	return nil
}

func (m *ValueProto) GetStructValue() *ValueProto_Struct {
	if x, ok := m.GetValue().(*ValueProto_StructValue); ok {
		return x.StructValue
	}
	return nil
}

func (m *ValueProto) GetProtoValue() []byte {
	if x, ok := m.GetValue().(*ValueProto_ProtoValue); ok {
		return x.ProtoValue
	}
	return nil
}

func (m *ValueProto) GetTimestampValue() *timestamp.Timestamp {
	if x, ok := m.GetValue().(*ValueProto_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (m *ValueProto) GetDatetimeValue() *ValueProto_Datetime {
	if x, ok := m.GetValue().(*ValueProto_DatetimeValue); ok {
		return x.DatetimeValue
	}
	return nil
}

func (m *ValueProto) GetTimeValue() int64 {
	if x, ok := m.GetValue().(*ValueProto_TimeValue); ok {
		return x.TimeValue
	}
	return 0
}

func (m *ValueProto) GetGeographyValue() []byte {
	if x, ok := m.GetValue().(*ValueProto_GeographyValue); ok {
		return x.GeographyValue
	}
	return nil
}

func (m *ValueProto) GetNumericValue() []byte {
	if x, ok := m.GetValue().(*ValueProto_NumericValue); ok {
		return x.NumericValue
	}
	return nil
}

func (m *ValueProto) GetBignumericValue() []byte {
	if x, ok := m.GetValue().(*ValueProto_BignumericValue); ok {
		return x.BignumericValue
	}
	return nil
}

func (m *ValueProto) GetJsonValue() string {
	if x, ok := m.GetValue().(*ValueProto_JsonValue); ok {
		return x.JsonValue
	}
	return ""
}

func (m *ValueProto) GetX_ValueProto_SwitchMustHaveADefault() bool {
	if x, ok := m.GetValue().(*ValueProto_X_ValueProto_SwitchMustHaveADefault); ok {
		return x.X_ValueProto_SwitchMustHaveADefault
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ValueProto) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ValueProto_Int32Value)(nil),
		(*ValueProto_Int64Value)(nil),
		(*ValueProto_Uint32Value)(nil),
		(*ValueProto_Uint64Value)(nil),
		(*ValueProto_BoolValue)(nil),
		(*ValueProto_FloatValue)(nil),
		(*ValueProto_DoubleValue)(nil),
		(*ValueProto_StringValue)(nil),
		(*ValueProto_BytesValue)(nil),
		(*ValueProto_DateValue)(nil),
		(*ValueProto_EnumValue)(nil),
		(*ValueProto_ArrayValue)(nil),
		(*ValueProto_StructValue)(nil),
		(*ValueProto_ProtoValue)(nil),
		(*ValueProto_TimestampValue)(nil),
		(*ValueProto_DatetimeValue)(nil),
		(*ValueProto_TimeValue)(nil),
		(*ValueProto_GeographyValue)(nil),
		(*ValueProto_NumericValue)(nil),
		(*ValueProto_BignumericValue)(nil),
		(*ValueProto_JsonValue)(nil),
		(*ValueProto_X_ValueProto_SwitchMustHaveADefault)(nil),
	}
}

type ValueProto_Array struct {
	Element              []*ValueProto `protobuf:"bytes,1,rep,name=element" json:"element,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ValueProto_Array) Reset()         { *m = ValueProto_Array{} }
func (m *ValueProto_Array) String() string { return proto.CompactTextString(m) }
func (*ValueProto_Array) ProtoMessage()    {}
func (*ValueProto_Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5510b35f888f5c, []int{0, 0}
}

func (m *ValueProto_Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueProto_Array.Unmarshal(m, b)
}
func (m *ValueProto_Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueProto_Array.Marshal(b, m, deterministic)
}
func (m *ValueProto_Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueProto_Array.Merge(m, src)
}
func (m *ValueProto_Array) XXX_Size() int {
	return xxx_messageInfo_ValueProto_Array.Size(m)
}
func (m *ValueProto_Array) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueProto_Array.DiscardUnknown(m)
}

var xxx_messageInfo_ValueProto_Array proto.InternalMessageInfo

func (m *ValueProto_Array) GetElement() []*ValueProto {
	if m != nil {
		return m.Element
	}
	return nil
}

type ValueProto_Struct struct {
	Field                []*ValueProto `protobuf:"bytes,1,rep,name=field" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ValueProto_Struct) Reset()         { *m = ValueProto_Struct{} }
func (m *ValueProto_Struct) String() string { return proto.CompactTextString(m) }
func (*ValueProto_Struct) ProtoMessage()    {}
func (*ValueProto_Struct) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5510b35f888f5c, []int{0, 1}
}

func (m *ValueProto_Struct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueProto_Struct.Unmarshal(m, b)
}
func (m *ValueProto_Struct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueProto_Struct.Marshal(b, m, deterministic)
}
func (m *ValueProto_Struct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueProto_Struct.Merge(m, src)
}
func (m *ValueProto_Struct) XXX_Size() int {
	return xxx_messageInfo_ValueProto_Struct.Size(m)
}
func (m *ValueProto_Struct) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueProto_Struct.DiscardUnknown(m)
}

var xxx_messageInfo_ValueProto_Struct proto.InternalMessageInfo

func (m *ValueProto_Struct) GetField() []*ValueProto {
	if m != nil {
		return m.Field
	}
	return nil
}

type ValueProto_Datetime struct {
	BitFieldDatetimeSeconds *int64   `protobuf:"varint,1,opt,name=bit_field_datetime_seconds,json=bitFieldDatetimeSeconds" json:"bit_field_datetime_seconds,omitempty"`
	Nanos                   *int32   `protobuf:"varint,2,opt,name=nanos" json:"nanos,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *ValueProto_Datetime) Reset()         { *m = ValueProto_Datetime{} }
func (m *ValueProto_Datetime) String() string { return proto.CompactTextString(m) }
func (*ValueProto_Datetime) ProtoMessage()    {}
func (*ValueProto_Datetime) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf5510b35f888f5c, []int{0, 2}
}

func (m *ValueProto_Datetime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueProto_Datetime.Unmarshal(m, b)
}
func (m *ValueProto_Datetime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueProto_Datetime.Marshal(b, m, deterministic)
}
func (m *ValueProto_Datetime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueProto_Datetime.Merge(m, src)
}
func (m *ValueProto_Datetime) XXX_Size() int {
	return xxx_messageInfo_ValueProto_Datetime.Size(m)
}
func (m *ValueProto_Datetime) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueProto_Datetime.DiscardUnknown(m)
}

var xxx_messageInfo_ValueProto_Datetime proto.InternalMessageInfo

func (m *ValueProto_Datetime) GetBitFieldDatetimeSeconds() int64 {
	if m != nil && m.BitFieldDatetimeSeconds != nil {
		return *m.BitFieldDatetimeSeconds
	}
	return 0
}

func (m *ValueProto_Datetime) GetNanos() int32 {
	if m != nil && m.Nanos != nil {
		return *m.Nanos
	}
	return 0
}

func init() {
	proto.RegisterType((*ValueProto)(nil), "zetasql.ValueProto")
	proto.RegisterType((*ValueProto_Array)(nil), "zetasql.ValueProto.Array")
	proto.RegisterType((*ValueProto_Struct)(nil), "zetasql.ValueProto.Struct")
	proto.RegisterType((*ValueProto_Datetime)(nil), "zetasql.ValueProto.Datetime")
}

func init() { proto.RegisterFile("zetasql/public/value.proto", fileDescriptor_bf5510b35f888f5c) }

var fileDescriptor_bf5510b35f888f5c = []byte{
	// 631 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0xef, 0x6b, 0xd3, 0x40,
	0x18, 0xc7, 0x7b, 0x6b, 0xb3, 0x36, 0xd7, 0x9f, 0x66, 0xd3, 0xcd, 0x20, 0x2c, 0x2a, 0x83, 0x0c,
	0xb1, 0x85, 0x6d, 0xec, 0x8d, 0x82, 0x6c, 0x4c, 0x29, 0x43, 0x41, 0x53, 0xf5, 0x85, 0x20, 0xe1,
	0x92, 0x5e, 0xbb, 0x48, 0x92, 0xab, 0xc9, 0xdd, 0x64, 0xfe, 0x65, 0xfe, 0x69, 0xbe, 0x53, 0xee,
	0xee, 0xb9, 0xeb, 0x84, 0xe2, 0xcb, 0x7e, 0x9f, 0xcf, 0xf7, 0xf9, 0x75, 0x4f, 0x83, 0xfd, 0x9f,
	0x94, 0x93, 0xfa, 0x7b, 0x3e, 0x59, 0x89, 0x24, 0xcf, 0xd2, 0xc9, 0x0d, 0xc9, 0x05, 0x1d, 0xaf,
	0x2a, 0xc6, 0x99, 0xd7, 0x86, 0x98, 0x7f, 0xb0, 0x64, 0x6c, 0x99, 0xd3, 0x89, 0x92, 0x13, 0xb1,
	0x98, 0xf0, 0xac, 0xa0, 0x35, 0x27, 0xc5, 0x4a, 0x93, 0x4f, 0x7e, 0xb9, 0x18, 0x7f, 0x96, 0xce,
	0xf7, 0xca, 0xf8, 0x18, 0x77, 0xb3, 0x92, 0x9f, 0x1c, 0xc7, 0x2a, 0xdb, 0x3e, 0x0a, 0x50, 0xe8,
	0x4c, 0x1b, 0x11, 0x56, 0xa2, 0xe2, 0x00, 0x39, 0x3b, 0x05, 0x64, 0x2b, 0x40, 0x61, 0x13, 0x90,
	0xb3, 0x53, 0x8d, 0x3c, 0xc5, 0x3d, 0x71, 0x37, 0x4d, 0x33, 0x40, 0x61, 0x7f, 0xda, 0x88, 0xba,
	0xe2, 0x4e, 0x1e, 0x80, 0x6c, 0xa2, 0x56, 0x80, 0xc2, 0x96, 0x81, 0x4c, 0xa6, 0x03, 0x8c, 0x13,
	0xc6, 0x72, 0x40, 0x9c, 0x00, 0x85, 0x9d, 0x69, 0x23, 0x72, 0xa5, 0x66, 0xbb, 0x59, 0xe4, 0x8c,
	0x70, 0x20, 0xb6, 0x03, 0x14, 0x6e, 0xc9, 0x6e, 0x94, 0x68, 0x0b, 0xcd, 0x99, 0x48, 0x72, 0x0a,
	0x4c, 0x3b, 0x40, 0x21, 0x92, 0x85, 0xb4, 0x6a, 0xa1, 0x9a, 0x57, 0x59, 0xb9, 0x04, 0xa8, 0x13,
	0xa0, 0xd0, 0x95, 0x90, 0x56, 0x6d, 0xb1, 0xe4, 0x96, 0xd3, 0x1a, 0x18, 0x37, 0x40, 0x61, 0x4f,
	0x16, 0x53, 0xa2, 0x6d, 0x78, 0x4e, 0xb8, 0x29, 0x85, 0x61, 0x7f, 0xae, 0xd4, 0x2c, 0x40, 0x4b,
	0x51, 0x00, 0xd0, 0x33, 0x80, 0xd4, 0x34, 0xf0, 0x12, 0x77, 0x49, 0x55, 0x91, 0x5b, 0x20, 0xfa,
	0x01, 0x0a, 0xbb, 0xc7, 0x0f, 0xc7, 0xf0, 0xa2, 0xe3, 0xf5, 0x63, 0x8d, 0xcf, 0x25, 0x26, 0xeb,
	0x2b, 0x5e, 0xbb, 0x5f, 0xa9, 0x39, 0x44, 0x6a, 0x16, 0x32, 0x50, 0x76, 0x7f, 0x93, 0x7d, 0xa6,
	0x38, 0x98, 0x51, 0xa4, 0xdc, 0xce, 0xa8, 0x2e, 0x03, 0xfc, 0x43, 0x33, 0xa3, 0x12, 0x35, 0xf2,
	0x1a, 0x0f, 0xed, 0x19, 0x01, 0x36, 0x82, 0x32, 0xfa, 0xdc, 0xc6, 0xe6, 0xdc, 0xc6, 0x1f, 0x0d,
	0x37, 0x6d, 0x44, 0x03, 0x6b, 0x32, 0x69, 0x06, 0x72, 0x2d, 0x52, 0x85, 0x2c, 0xf7, 0x54, 0x96,
	0x47, 0x9b, 0x9a, 0xbd, 0x04, 0x72, 0xda, 0x88, 0xfa, 0xc6, 0x65, 0x17, 0x7a, 0x27, 0x85, 0x07,
	0xe7, 0xe8, 0xae, 0x81, 0x23, 0x3c, 0x5c, 0x52, 0xb6, 0xac, 0xc8, 0xea, 0xda, 0x2c, 0x75, 0x07,
	0xa6, 0x1a, 0xd8, 0x80, 0x46, 0x0f, 0x71, 0xbf, 0x14, 0x05, 0xad, 0xb2, 0x14, 0xc0, 0x5d, 0x00,
	0x7b, 0x20, 0x6b, 0xec, 0x19, 0x1e, 0x25, 0xd9, 0xf2, 0x5f, 0xf2, 0x3e, 0x90, 0xc3, 0x75, 0xc4,
	0xf6, 0xf7, 0xad, 0x66, 0x25, 0x60, 0x7b, 0x70, 0x57, 0xae, 0xd4, 0x34, 0xf0, 0x09, 0x87, 0x71,
	0xbc, 0x1e, 0x35, 0x8e, 0xeb, 0x1f, 0x19, 0x4f, 0xaf, 0xe3, 0x42, 0xd4, 0x3c, 0xbe, 0x26, 0x37,
	0x34, 0x26, 0xf1, 0x9c, 0x2e, 0x88, 0xc8, 0xf9, 0xfe, 0x1f, 0x04, 0x7f, 0x81, 0x60, 0x6d, 0x98,
	0x29, 0xfc, 0x9d, 0xa8, 0xf9, 0x94, 0xdc, 0xd0, 0xf3, 0x4b, 0x8d, 0xfa, 0x67, 0xd8, 0x51, 0x07,
	0xe2, 0x3d, 0xc7, 0x6d, 0x9a, 0xd3, 0x82, 0x96, 0x7c, 0x1f, 0x05, 0xcd, 0xb0, 0x7b, 0xbc, 0xb3,
	0x61, 0xc1, 0x91, 0x61, 0xfc, 0x13, 0xbc, 0xad, 0x2f, 0xc3, 0x3b, 0xc2, 0xce, 0x22, 0xa3, 0xf9,
	0xfc, 0x7f, 0x36, 0x4d, 0xf8, 0x5f, 0x71, 0xc7, 0xbc, 0x90, 0xf7, 0x02, 0xfb, 0x49, 0xc6, 0x63,
	0x15, 0x88, 0xed, 0x0b, 0xd7, 0x34, 0x65, 0xe5, 0xbc, 0x56, 0x9f, 0x94, 0x66, 0xb4, 0x97, 0x64,
	0xfc, 0x8d, 0x04, 0x8c, 0x6b, 0xa6, 0xc3, 0xde, 0x2e, 0x76, 0x4a, 0x52, 0xb2, 0x5a, 0x7d, 0x57,
	0x9c, 0x48, 0xff, 0xb8, 0x68, 0x63, 0x47, 0xad, 0xef, 0xaa, 0xd5, 0xe9, 0x8e, 0x7a, 0x57, 0xad,
	0xce, 0x83, 0xd1, 0xde, 0xc5, 0x21, 0xf6, 0x52, 0x56, 0x98, 0x93, 0x83, 0xde, 0x2e, 0x7a, 0x5f,
	0x28, 0x27, 0xb3, 0x0f, 0x6f, 0x55, 0x8f, 0xbf, 0x11, 0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0xeb, 0xa3, 0xae, 0x28, 0x05, 0x00, 0x00,
}
