// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/resolved_ast/serialization.proto

package resolved_ast

import (
	fmt "fmt"
	parse_location_rangepb "github.com/apstndb/go-zetasql-genproto/zetasql/public/parse_location_rangepb"
	typepb "github.com/apstndb/go-zetasql-genproto/zetasql/public/typepb"
	valuepb "github.com/apstndb/go-zetasql-genproto/zetasql/public/valuepb"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResolvedColumnProto struct {
	ColumnId             *int64            `protobuf:"varint,1,opt,name=column_id,json=columnId" json:"column_id,omitempty"`
	TableName            *string           `protobuf:"bytes,2,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Name                 *string           `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Type                 *typepb.TypeProto `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResolvedColumnProto) Reset()         { *m = ResolvedColumnProto{} }
func (m *ResolvedColumnProto) String() string { return proto.CompactTextString(m) }
func (*ResolvedColumnProto) ProtoMessage()    {}
func (*ResolvedColumnProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{0}
}

func (m *ResolvedColumnProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedColumnProto.Unmarshal(m, b)
}
func (m *ResolvedColumnProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedColumnProto.Marshal(b, m, deterministic)
}
func (m *ResolvedColumnProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedColumnProto.Merge(m, src)
}
func (m *ResolvedColumnProto) XXX_Size() int {
	return xxx_messageInfo_ResolvedColumnProto.Size(m)
}
func (m *ResolvedColumnProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedColumnProto.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedColumnProto proto.InternalMessageInfo

func (m *ResolvedColumnProto) GetColumnId() int64 {
	if m != nil && m.ColumnId != nil {
		return *m.ColumnId
	}
	return 0
}

func (m *ResolvedColumnProto) GetTableName() string {
	if m != nil && m.TableName != nil {
		return *m.TableName
	}
	return ""
}

func (m *ResolvedColumnProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ResolvedColumnProto) GetType() *typepb.TypeProto {
	if m != nil {
		return m.Type
	}
	return nil
}

type ValueWithTypeProto struct {
	Type                 *typepb.TypeProto   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Value                *valuepb.ValueProto `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ValueWithTypeProto) Reset()         { *m = ValueWithTypeProto{} }
func (m *ValueWithTypeProto) String() string { return proto.CompactTextString(m) }
func (*ValueWithTypeProto) ProtoMessage()    {}
func (*ValueWithTypeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{1}
}

func (m *ValueWithTypeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueWithTypeProto.Unmarshal(m, b)
}
func (m *ValueWithTypeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueWithTypeProto.Marshal(b, m, deterministic)
}
func (m *ValueWithTypeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueWithTypeProto.Merge(m, src)
}
func (m *ValueWithTypeProto) XXX_Size() int {
	return xxx_messageInfo_ValueWithTypeProto.Size(m)
}
func (m *ValueWithTypeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueWithTypeProto.DiscardUnknown(m)
}

var xxx_messageInfo_ValueWithTypeProto proto.InternalMessageInfo

func (m *ValueWithTypeProto) GetType() *typepb.TypeProto {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *ValueWithTypeProto) GetValue() *valuepb.ValueProto {
	if m != nil {
		return m.Value
	}
	return nil
}

type TableRefProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SerializationId      *int64   `protobuf:"varint,2,opt,name=serialization_id,json=serializationId" json:"serialization_id,omitempty"`
	FullName             *string  `protobuf:"bytes,3,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableRefProto) Reset()         { *m = TableRefProto{} }
func (m *TableRefProto) String() string { return proto.CompactTextString(m) }
func (*TableRefProto) ProtoMessage()    {}
func (*TableRefProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{2}
}

func (m *TableRefProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableRefProto.Unmarshal(m, b)
}
func (m *TableRefProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableRefProto.Marshal(b, m, deterministic)
}
func (m *TableRefProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableRefProto.Merge(m, src)
}
func (m *TableRefProto) XXX_Size() int {
	return xxx_messageInfo_TableRefProto.Size(m)
}
func (m *TableRefProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TableRefProto.DiscardUnknown(m)
}

var xxx_messageInfo_TableRefProto proto.InternalMessageInfo

func (m *TableRefProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TableRefProto) GetSerializationId() int64 {
	if m != nil && m.SerializationId != nil {
		return *m.SerializationId
	}
	return 0
}

func (m *TableRefProto) GetFullName() string {
	if m != nil && m.FullName != nil {
		return *m.FullName
	}
	return ""
}

type ModelRefProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	SerializationId      *int64   `protobuf:"varint,2,opt,name=serialization_id,json=serializationId" json:"serialization_id,omitempty"`
	FullName             *string  `protobuf:"bytes,3,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelRefProto) Reset()         { *m = ModelRefProto{} }
func (m *ModelRefProto) String() string { return proto.CompactTextString(m) }
func (*ModelRefProto) ProtoMessage()    {}
func (*ModelRefProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{3}
}

func (m *ModelRefProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelRefProto.Unmarshal(m, b)
}
func (m *ModelRefProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelRefProto.Marshal(b, m, deterministic)
}
func (m *ModelRefProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelRefProto.Merge(m, src)
}
func (m *ModelRefProto) XXX_Size() int {
	return xxx_messageInfo_ModelRefProto.Size(m)
}
func (m *ModelRefProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelRefProto.DiscardUnknown(m)
}

var xxx_messageInfo_ModelRefProto proto.InternalMessageInfo

func (m *ModelRefProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ModelRefProto) GetSerializationId() int64 {
	if m != nil && m.SerializationId != nil {
		return *m.SerializationId
	}
	return 0
}

func (m *ModelRefProto) GetFullName() string {
	if m != nil && m.FullName != nil {
		return *m.FullName
	}
	return ""
}

type ConnectionRefProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FullName             *string  `protobuf:"bytes,3,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionRefProto) Reset()         { *m = ConnectionRefProto{} }
func (m *ConnectionRefProto) String() string { return proto.CompactTextString(m) }
func (*ConnectionRefProto) ProtoMessage()    {}
func (*ConnectionRefProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{4}
}

func (m *ConnectionRefProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRefProto.Unmarshal(m, b)
}
func (m *ConnectionRefProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRefProto.Marshal(b, m, deterministic)
}
func (m *ConnectionRefProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRefProto.Merge(m, src)
}
func (m *ConnectionRefProto) XXX_Size() int {
	return xxx_messageInfo_ConnectionRefProto.Size(m)
}
func (m *ConnectionRefProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRefProto.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRefProto proto.InternalMessageInfo

func (m *ConnectionRefProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ConnectionRefProto) GetFullName() string {
	if m != nil && m.FullName != nil {
		return *m.FullName
	}
	return ""
}

type ConstantRefProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConstantRefProto) Reset()         { *m = ConstantRefProto{} }
func (m *ConstantRefProto) String() string { return proto.CompactTextString(m) }
func (*ConstantRefProto) ProtoMessage()    {}
func (*ConstantRefProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{5}
}

func (m *ConstantRefProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstantRefProto.Unmarshal(m, b)
}
func (m *ConstantRefProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstantRefProto.Marshal(b, m, deterministic)
}
func (m *ConstantRefProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstantRefProto.Merge(m, src)
}
func (m *ConstantRefProto) XXX_Size() int {
	return xxx_messageInfo_ConstantRefProto.Size(m)
}
func (m *ConstantRefProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstantRefProto.DiscardUnknown(m)
}

var xxx_messageInfo_ConstantRefProto proto.InternalMessageInfo

func (m *ConstantRefProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type FunctionRefProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionRefProto) Reset()         { *m = FunctionRefProto{} }
func (m *FunctionRefProto) String() string { return proto.CompactTextString(m) }
func (*FunctionRefProto) ProtoMessage()    {}
func (*FunctionRefProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{6}
}

func (m *FunctionRefProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionRefProto.Unmarshal(m, b)
}
func (m *FunctionRefProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionRefProto.Marshal(b, m, deterministic)
}
func (m *FunctionRefProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionRefProto.Merge(m, src)
}
func (m *FunctionRefProto) XXX_Size() int {
	return xxx_messageInfo_FunctionRefProto.Size(m)
}
func (m *FunctionRefProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionRefProto.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionRefProto proto.InternalMessageInfo

func (m *FunctionRefProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type TableValuedFunctionRefProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TableValuedFunctionRefProto) Reset()         { *m = TableValuedFunctionRefProto{} }
func (m *TableValuedFunctionRefProto) String() string { return proto.CompactTextString(m) }
func (*TableValuedFunctionRefProto) ProtoMessage()    {}
func (*TableValuedFunctionRefProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{7}
}

func (m *TableValuedFunctionRefProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableValuedFunctionRefProto.Unmarshal(m, b)
}
func (m *TableValuedFunctionRefProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableValuedFunctionRefProto.Marshal(b, m, deterministic)
}
func (m *TableValuedFunctionRefProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableValuedFunctionRefProto.Merge(m, src)
}
func (m *TableValuedFunctionRefProto) XXX_Size() int {
	return xxx_messageInfo_TableValuedFunctionRefProto.Size(m)
}
func (m *TableValuedFunctionRefProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TableValuedFunctionRefProto.DiscardUnknown(m)
}

var xxx_messageInfo_TableValuedFunctionRefProto proto.InternalMessageInfo

func (m *TableValuedFunctionRefProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type ResolvedNodeProto struct {
	ParseLocationRange   *parse_location_rangepb.ParseLocationRangeProto `protobuf:"bytes,1,opt,name=parse_location_range,json=parseLocationRange" json:"parse_location_range,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *ResolvedNodeProto) Reset()         { *m = ResolvedNodeProto{} }
func (m *ResolvedNodeProto) String() string { return proto.CompactTextString(m) }
func (*ResolvedNodeProto) ProtoMessage()    {}
func (*ResolvedNodeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{8}
}

func (m *ResolvedNodeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedNodeProto.Unmarshal(m, b)
}
func (m *ResolvedNodeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedNodeProto.Marshal(b, m, deterministic)
}
func (m *ResolvedNodeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedNodeProto.Merge(m, src)
}
func (m *ResolvedNodeProto) XXX_Size() int {
	return xxx_messageInfo_ResolvedNodeProto.Size(m)
}
func (m *ResolvedNodeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedNodeProto.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedNodeProto proto.InternalMessageInfo

func (m *ResolvedNodeProto) GetParseLocationRange() *parse_location_rangepb.ParseLocationRangeProto {
	if m != nil {
		return m.ParseLocationRange
	}
	return nil
}

type FieldDescriptorRefProto struct {
	ContainingProto      *typepb.ProtoTypeProto `protobuf:"bytes,1,opt,name=containing_proto,json=containingProto" json:"containing_proto,omitempty"`
	Number               *int32                 `protobuf:"varint,2,opt,name=number" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FieldDescriptorRefProto) Reset()         { *m = FieldDescriptorRefProto{} }
func (m *FieldDescriptorRefProto) String() string { return proto.CompactTextString(m) }
func (*FieldDescriptorRefProto) ProtoMessage()    {}
func (*FieldDescriptorRefProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{9}
}

func (m *FieldDescriptorRefProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDescriptorRefProto.Unmarshal(m, b)
}
func (m *FieldDescriptorRefProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDescriptorRefProto.Marshal(b, m, deterministic)
}
func (m *FieldDescriptorRefProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDescriptorRefProto.Merge(m, src)
}
func (m *FieldDescriptorRefProto) XXX_Size() int {
	return xxx_messageInfo_FieldDescriptorRefProto.Size(m)
}
func (m *FieldDescriptorRefProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDescriptorRefProto.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDescriptorRefProto proto.InternalMessageInfo

func (m *FieldDescriptorRefProto) GetContainingProto() *typepb.ProtoTypeProto {
	if m != nil {
		return m.ContainingProto
	}
	return nil
}

func (m *FieldDescriptorRefProto) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

type OneofDescriptorRefProto struct {
	ContainingProto      *typepb.ProtoTypeProto `protobuf:"bytes,1,opt,name=containing_proto,json=containingProto" json:"containing_proto,omitempty"`
	Index                *int32                 `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OneofDescriptorRefProto) Reset()         { *m = OneofDescriptorRefProto{} }
func (m *OneofDescriptorRefProto) String() string { return proto.CompactTextString(m) }
func (*OneofDescriptorRefProto) ProtoMessage()    {}
func (*OneofDescriptorRefProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{10}
}

func (m *OneofDescriptorRefProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofDescriptorRefProto.Unmarshal(m, b)
}
func (m *OneofDescriptorRefProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofDescriptorRefProto.Marshal(b, m, deterministic)
}
func (m *OneofDescriptorRefProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofDescriptorRefProto.Merge(m, src)
}
func (m *OneofDescriptorRefProto) XXX_Size() int {
	return xxx_messageInfo_OneofDescriptorRefProto.Size(m)
}
func (m *OneofDescriptorRefProto) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofDescriptorRefProto.DiscardUnknown(m)
}

var xxx_messageInfo_OneofDescriptorRefProto proto.InternalMessageInfo

func (m *OneofDescriptorRefProto) GetContainingProto() *typepb.ProtoTypeProto {
	if m != nil {
		return m.ContainingProto
	}
	return nil
}

func (m *OneofDescriptorRefProto) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type ProcedureRefProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcedureRefProto) Reset()         { *m = ProcedureRefProto{} }
func (m *ProcedureRefProto) String() string { return proto.CompactTextString(m) }
func (*ProcedureRefProto) ProtoMessage()    {}
func (*ProcedureRefProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_de31f6b196e43d26, []int{11}
}

func (m *ProcedureRefProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcedureRefProto.Unmarshal(m, b)
}
func (m *ProcedureRefProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcedureRefProto.Marshal(b, m, deterministic)
}
func (m *ProcedureRefProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcedureRefProto.Merge(m, src)
}
func (m *ProcedureRefProto) XXX_Size() int {
	return xxx_messageInfo_ProcedureRefProto.Size(m)
}
func (m *ProcedureRefProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcedureRefProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProcedureRefProto proto.InternalMessageInfo

func (m *ProcedureRefProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ResolvedColumnProto)(nil), "zetasql.ResolvedColumnProto")
	proto.RegisterType((*ValueWithTypeProto)(nil), "zetasql.ValueWithTypeProto")
	proto.RegisterType((*TableRefProto)(nil), "zetasql.TableRefProto")
	proto.RegisterType((*ModelRefProto)(nil), "zetasql.ModelRefProto")
	proto.RegisterType((*ConnectionRefProto)(nil), "zetasql.ConnectionRefProto")
	proto.RegisterType((*ConstantRefProto)(nil), "zetasql.ConstantRefProto")
	proto.RegisterType((*FunctionRefProto)(nil), "zetasql.FunctionRefProto")
	proto.RegisterType((*TableValuedFunctionRefProto)(nil), "zetasql.TableValuedFunctionRefProto")
	proto.RegisterType((*ResolvedNodeProto)(nil), "zetasql.ResolvedNodeProto")
	proto.RegisterType((*FieldDescriptorRefProto)(nil), "zetasql.FieldDescriptorRefProto")
	proto.RegisterType((*OneofDescriptorRefProto)(nil), "zetasql.OneofDescriptorRefProto")
	proto.RegisterType((*ProcedureRefProto)(nil), "zetasql.ProcedureRefProto")
}

func init() {
	proto.RegisterFile("zetasql/resolved_ast/serialization.proto", fileDescriptor_de31f6b196e43d26)
}

var fileDescriptor_de31f6b196e43d26 = []byte{
	// 518 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xdf, 0x4f, 0xdb, 0x30,
	0x10, 0x56, 0xa0, 0xdd, 0xe8, 0xa1, 0x89, 0x62, 0xaa, 0xb5, 0x2b, 0x9a, 0x54, 0xe5, 0x01, 0xda,
	0x97, 0x56, 0xe3, 0x4f, 0x68, 0x37, 0x24, 0x24, 0xc6, 0xba, 0xc0, 0x36, 0x89, 0x97, 0xc8, 0x8d,
	0xaf, 0xc1, 0x9a, 0x63, 0x67, 0x8e, 0x83, 0x06, 0xff, 0xc3, 0xfe, 0xe7, 0xc9, 0x8e, 0xfb, 0x03,
	0x86, 0xba, 0xbd, 0x8c, 0xb7, 0xf8, 0xbe, 0xef, 0xee, 0xfb, 0x7c, 0x77, 0x0e, 0xf4, 0xef, 0xd1,
	0xd0, 0xe2, 0x87, 0x18, 0x69, 0x2c, 0x94, 0xb8, 0x45, 0x16, 0xd3, 0xc2, 0x8c, 0x0a, 0xd4, 0x9c,
	0x0a, 0x7e, 0x4f, 0x0d, 0x57, 0x72, 0x98, 0x6b, 0x65, 0x14, 0x79, 0xe9, 0x99, 0xdd, 0xc1, 0x22,
	0x25, 0x2f, 0x67, 0x82, 0x27, 0xa3, 0x9c, 0xea, 0x02, 0x63, 0xa1, 0x12, 0xc7, 0x8e, 0x35, 0x95,
	0x29, 0x56, 0x39, 0xdd, 0x37, 0x8f, 0xa8, 0xe6, 0x2e, 0x5f, 0x40, 0xdd, 0x47, 0xd0, 0x2d, 0x15,
	0xa5, 0xc7, 0xc2, 0x5f, 0x01, 0x1c, 0x44, 0xde, 0xcf, 0x44, 0x89, 0x32, 0x93, 0x53, 0x67, 0xe1,
	0x10, 0x1a, 0x89, 0x3b, 0xc6, 0x9c, 0x75, 0x82, 0x5e, 0xd0, 0xdf, 0x8e, 0x76, 0xaa, 0xc0, 0x19,
	0x23, 0x6f, 0x01, 0x0c, 0x9d, 0x09, 0x8c, 0x25, 0xcd, 0xb0, 0xb3, 0xd5, 0x0b, 0xfa, 0x8d, 0xa8,
	0xe1, 0x22, 0x17, 0x34, 0x43, 0x42, 0xa0, 0xe6, 0x80, 0x6d, 0x07, 0xb8, 0x6f, 0x72, 0x04, 0x35,
	0xeb, 0xa8, 0x53, 0xeb, 0x05, 0xfd, 0xdd, 0x13, 0x32, 0xf4, 0x96, 0x86, 0x57, 0x77, 0x39, 0x3a,
	0xc5, 0xc8, 0xe1, 0x61, 0x0a, 0xe4, 0xab, 0xb5, 0xf7, 0x8d, 0x9b, 0x9b, 0x25, 0xb6, 0xcc, 0x0e,
	0x36, 0x67, 0x93, 0x01, 0xd4, 0xdd, 0xe5, 0x9c, 0xa7, 0xdd, 0x93, 0x83, 0x25, 0xd1, 0xd5, 0xac,
	0x98, 0x15, 0x23, 0xfc, 0x0e, 0xaf, 0xae, 0xac, 0xe3, 0x08, 0xe7, 0x95, 0xc6, 0xc2, 0x75, 0xb0,
	0xe6, 0x7a, 0x00, 0xcd, 0x07, 0xf3, 0xb1, 0xcd, 0xd8, 0x72, 0xcd, 0xd8, 0x7b, 0x10, 0x3f, 0x63,
	0xb6, 0x61, 0xf3, 0x52, 0x88, 0x78, 0xed, 0xe6, 0x3b, 0x36, 0x60, 0x3b, 0x62, 0xc5, 0x3e, 0x2a,
	0x86, 0xe2, 0x59, 0xc4, 0x3e, 0x00, 0x99, 0x28, 0x29, 0x31, 0xb1, 0xe4, 0x8d, 0x8a, 0x1b, 0xcb,
	0x1c, 0x41, 0x73, 0xa2, 0x64, 0x61, 0xa8, 0x34, 0x9b, 0x8a, 0x58, 0xde, 0x69, 0x29, 0xff, 0x2a,
	0x16, 0xbe, 0x83, 0x43, 0xd7, 0x70, 0x37, 0x0a, 0xf6, 0x4f, 0x29, 0x29, 0xec, 0x2f, 0x76, 0xf3,
	0x42, 0x31, 0xbf, 0x0b, 0x11, 0xb4, 0x9e, 0x7a, 0x06, 0x7e, 0x37, 0x7a, 0xcb, 0x91, 0x4f, 0x2d,
	0xe9, 0xdc, 0x73, 0x22, 0x4b, 0xa9, 0xe6, 0x4f, 0xf2, 0x3f, 0x80, 0xb0, 0x84, 0xf6, 0x29, 0x47,
	0xc1, 0xde, 0x63, 0x91, 0x68, 0x9e, 0x1b, 0xa5, 0x97, 0xbe, 0xc6, 0xd0, 0x4c, 0x94, 0x34, 0x94,
	0x4b, 0x2e, 0xd3, 0xd8, 0x3d, 0x1a, 0x2f, 0xd5, 0x5e, 0x49, 0xd9, 0xe8, 0x6a, 0x17, 0xf7, 0x56,
	0x09, 0x55, 0x8d, 0xd7, 0xf0, 0x42, 0x96, 0xd9, 0x0c, 0xb5, 0x9b, 0x67, 0x3d, 0xf2, 0xa7, 0xb0,
	0x80, 0xf6, 0x27, 0x89, 0x6a, 0xfe, 0x9f, 0x64, 0x5b, 0x50, 0xe7, 0x92, 0xe1, 0x4f, 0xaf, 0x5a,
	0x1d, 0xc2, 0x63, 0xd8, 0x9f, 0x6a, 0x95, 0x20, 0x2b, 0xf5, 0xc6, 0xe5, 0x1f, 0x7f, 0x01, 0x92,
	0xa8, 0x6c, 0x98, 0x2a, 0x95, 0x0a, 0x5c, 0x88, 0x8e, 0x5b, 0xd7, 0x68, 0xe8, 0xe5, 0xe7, 0xf3,
	0xcb, 0xf5, 0x95, 0x9c, 0x06, 0xd7, 0xc7, 0x29, 0x37, 0x37, 0xe5, 0x6c, 0x98, 0xa8, 0x6c, 0x44,
	0xf3, 0xc2, 0x48, 0x36, 0x1b, 0x3d, 0xf5, 0xc3, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x13, 0x96,
	0xe0, 0x6f, 0x07, 0x05, 0x00, 0x00,
}
