// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/public/options.proto

package public

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LanguageVersion int32

const (
	LanguageVersion_VERSION_CURRENT                                 LanguageVersion = 1
	LanguageVersion_VERSION_1_0                                     LanguageVersion = 10000
	LanguageVersion_VERSION_1_1                                     LanguageVersion = 11000
	LanguageVersion_VERSION_1_2                                     LanguageVersion = 12000
	LanguageVersion_VERSION_1_3                                     LanguageVersion = 13000
	LanguageVersion___LanguageVersion__switch_must_have_a_default__ LanguageVersion = -1
)

var LanguageVersion_name = map[int32]string{
	1:     "VERSION_CURRENT",
	10000: "VERSION_1_0",
	11000: "VERSION_1_1",
	12000: "VERSION_1_2",
	13000: "VERSION_1_3",
	-1:    "__LanguageVersion__switch_must_have_a_default__",
}

var LanguageVersion_value = map[string]int32{
	"VERSION_CURRENT": 1,
	"VERSION_1_0":     10000,
	"VERSION_1_1":     11000,
	"VERSION_1_2":     12000,
	"VERSION_1_3":     13000,
	"__LanguageVersion__switch_must_have_a_default__": -1,
}

func (x LanguageVersion) Enum() *LanguageVersion {
	p := new(LanguageVersion)
	*p = x
	return p
}

func (x LanguageVersion) String() string {
	return proto.EnumName(LanguageVersion_name, int32(x))
}

func (x *LanguageVersion) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LanguageVersion_value, data, "LanguageVersion")
	if err != nil {
		return err
	}
	*x = LanguageVersion(value)
	return nil
}

func (LanguageVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{0}
}

type LanguageFeature int32

const (
	LanguageFeature_FEATURE_ANALYTIC_FUNCTIONS                            LanguageFeature = 1
	LanguageFeature_FEATURE_TABLESAMPLE                                   LanguageFeature = 2
	LanguageFeature_FEATURE_DISALLOW_GROUP_BY_FLOAT                       LanguageFeature = 3
	LanguageFeature_FEATURE_TIMESTAMP_NANOS                               LanguageFeature = 5
	LanguageFeature_FEATURE_DML_UPDATE_WITH_JOIN                          LanguageFeature = 6
	LanguageFeature_FEATURE_TABLE_VALUED_FUNCTIONS                        LanguageFeature = 8
	LanguageFeature_FEATURE_CREATE_AGGREGATE_FUNCTION                     LanguageFeature = 9
	LanguageFeature_FEATURE_CREATE_TABLE_FUNCTION                         LanguageFeature = 10
	LanguageFeature_FEATURE_GROUP_BY_ROLLUP                               LanguageFeature = 12
	LanguageFeature_FEATURE_TEMPLATE_FUNCTIONS                            LanguageFeature = 13
	LanguageFeature_FEATURE_CREATE_TABLE_PARTITION_BY                     LanguageFeature = 14
	LanguageFeature_FEATURE_CREATE_TABLE_CLUSTER_BY                       LanguageFeature = 15
	LanguageFeature_FEATURE_NUMERIC_TYPE                                  LanguageFeature = 16
	LanguageFeature_FEATURE_CREATE_TABLE_NOT_NULL                         LanguageFeature = 17
	LanguageFeature_FEATURE_CREATE_TABLE_FIELD_ANNOTATIONS                LanguageFeature = 18
	LanguageFeature_FEATURE_CREATE_TABLE_AS_SELECT_COLUMN_LIST            LanguageFeature = 19
	LanguageFeature_FEATURE_DISALLOW_NULL_PRIMARY_KEYS                    LanguageFeature = 20
	LanguageFeature_FEATURE_DISALLOW_PRIMARY_KEY_UPDATES                  LanguageFeature = 21
	LanguageFeature_FEATURE_TABLESAMPLE_FROM_TABLE_VALUED_FUNCTIONS       LanguageFeature = 22
	LanguageFeature_FEATURE_ENCRYPTION                                    LanguageFeature = 23
	LanguageFeature_FEATURE_GEOGRAPHY                                     LanguageFeature = 25
	LanguageFeature_FEATURE_STRATIFIED_RESERVOIR_TABLESAMPLE              LanguageFeature = 26
	LanguageFeature_FEATURE_FOREIGN_KEYS                                  LanguageFeature = 27
	LanguageFeature_FEATURE_BETWEEN_UINT64_INT64                          LanguageFeature = 28
	LanguageFeature_FEATURE_CHECK_CONSTRAINT                              LanguageFeature = 29
	LanguageFeature_FEATURE_PARAMETERS_IN_GRANTEE_LIST                    LanguageFeature = 30
	LanguageFeature_FEATURE_NAMED_ARGUMENTS                               LanguageFeature = 31
	LanguageFeature_FEATURE_ALLOW_LEGACY_ROW_ACCESS_POLICY_SYNTAX         LanguageFeature = 32
	LanguageFeature_FEATURE_CREATE_MATERIALIZED_VIEW_PARTITION_BY         LanguageFeature = 33
	LanguageFeature_FEATURE_CREATE_MATERIALIZED_VIEW_CLUSTER_BY           LanguageFeature = 34
	LanguageFeature_FEATURE_CREATE_EXTERNAL_TABLE_WITH_TABLE_ELEMENT_LIST LanguageFeature = 35
	LanguageFeature_FEATURE_UNENFORCED_PRIMARY_KEYS                       LanguageFeature = 40
	LanguageFeature_FEATURE_BIGNUMERIC_TYPE                               LanguageFeature = 41
	LanguageFeature_FEATURE_EXTENDED_TYPES                                LanguageFeature = 42
	LanguageFeature_FEATURE_JSON_TYPE                                     LanguageFeature = 43
	LanguageFeature_FEATURE_JSON_NO_VALIDATION                            LanguageFeature = 44
	LanguageFeature_FEATURE_JSON_LEGACY_PARSE                             LanguageFeature = 46
	LanguageFeature_FEATURE_CREATE_EXTERNAL_TABLE_WITH_PARTITION_COLUMNS  LanguageFeature = 47
	LanguageFeature_FEATURE_NO_ADVANCED_NUMERIC_MATH_SIGNATURES           LanguageFeature = 48
	LanguageFeature_FEATURE_INTERVAL_TYPE                                 LanguageFeature = 49
	LanguageFeature_FEATURE_V_1_1_ORDER_BY_COLLATE                        LanguageFeature = 11001
	LanguageFeature_FEATURE_V_1_1_WITH_ON_SUBQUERY                        LanguageFeature = 11002
	LanguageFeature_FEATURE_V_1_1_SELECT_STAR_EXCEPT_REPLACE              LanguageFeature = 11003
	LanguageFeature_FEATURE_V_1_1_ORDER_BY_IN_AGGREGATE                   LanguageFeature = 11004
	LanguageFeature_FEATURE_V_1_1_CAST_DIFFERENT_ARRAY_TYPES              LanguageFeature = 11005
	LanguageFeature_FEATURE_V_1_1_ARRAY_EQUALITY                          LanguageFeature = 11006
	LanguageFeature_FEATURE_V_1_1_LIMIT_IN_AGGREGATE                      LanguageFeature = 11007
	LanguageFeature_FEATURE_V_1_1_HAVING_IN_AGGREGATE                     LanguageFeature = 11008
	LanguageFeature_FEATURE_V_1_1_NULL_HANDLING_MODIFIER_IN_ANALYTIC      LanguageFeature = 11009
	LanguageFeature_FEATURE_V_1_1_NULL_HANDLING_MODIFIER_IN_AGGREGATE     LanguageFeature = 11010
	LanguageFeature_FEATURE_V_1_1_FOR_SYSTEM_TIME_AS_OF                   LanguageFeature = 11011
	LanguageFeature_FEATURE_V_1_2_CIVIL_TIME                              LanguageFeature = 12001
	LanguageFeature_FEATURE_V_1_2_SAFE_FUNCTION_CALL                      LanguageFeature = 12002
	LanguageFeature_FEATURE_V_1_2_GROUP_BY_STRUCT                         LanguageFeature = 12003
	LanguageFeature_FEATURE_V_1_2_PROTO_EXTENSIONS_WITH_NEW               LanguageFeature = 12004
	LanguageFeature_FEATURE_V_1_2_GROUP_BY_ARRAY                          LanguageFeature = 12005
	LanguageFeature_FEATURE_V_1_2_PROTO_EXTENSIONS_WITH_SET               LanguageFeature = 12006
	LanguageFeature_FEATURE_V_1_2_CORRELATED_REFS_IN_NESTED_DML           LanguageFeature = 12007
	LanguageFeature_FEATURE_V_1_2_WEEK_WITH_WEEKDAY                       LanguageFeature = 12008
	LanguageFeature_FEATURE_V_1_2_ARRAY_ELEMENTS_WITH_SET                 LanguageFeature = 12009
	LanguageFeature_FEATURE_V_1_2_NESTED_UPDATE_DELETE_WITH_OFFSET        LanguageFeature = 12010
	LanguageFeature_FEATURE_V_1_2_GENERATED_COLUMNS                       LanguageFeature = 12011
	LanguageFeature_FEATURE_V_1_3_PROTO_DEFAULT_IF_NULL                   LanguageFeature = 13001
	LanguageFeature_FEATURE_V_1_3_EXTRACT_FROM_PROTO                      LanguageFeature = 13002
	LanguageFeature_FEATURE_V_1_3_DISALLOW_PROTO3_HAS_SCALAR_FIELD        LanguageFeature = 13003
	LanguageFeature_FEATURE_V_1_3_ARRAY_ORDERING                          LanguageFeature = 13004
	LanguageFeature_FEATURE_V_1_3_OMIT_INSERT_COLUMN_LIST                 LanguageFeature = 13005
	LanguageFeature_FEATURE_V_1_3_IGNORE_PROTO3_USE_DEFAULTS              LanguageFeature = 13006
	LanguageFeature_FEATURE_V_1_3_REPLACE_FIELDS                          LanguageFeature = 13007
	LanguageFeature_FEATURE_V_1_3_NULLS_FIRST_LAST_IN_ORDER_BY            LanguageFeature = 13008
	LanguageFeature_FEATURE_V_1_3_ALLOW_DASHES_IN_TABLE_NAME              LanguageFeature = 13009
	LanguageFeature_FEATURE_V_1_3_CONCAT_MIXED_TYPES                      LanguageFeature = 13010
	LanguageFeature_FEATURE_V_1_3_WITH_RECURSIVE                          LanguageFeature = 13011
	LanguageFeature_FEATURE_V_1_3_PROTO_MAPS                              LanguageFeature = 13012
	LanguageFeature_FEATURE_V_1_3_ENUM_VALUE_DESCRIPTOR_PROTO             LanguageFeature = 13013
	LanguageFeature_FEATURE_V_1_3_DECIMAL_ALIAS                           LanguageFeature = 13014
	LanguageFeature_FEATURE_V_1_3_UNNEST_AND_FLATTEN_ARRAYS               LanguageFeature = 13015
	LanguageFeature_FEATURE_V_1_3_ALLOW_CONSECUTIVE_ON                    LanguageFeature = 13016
	LanguageFeature_FEATURE_V_1_3_ALLOW_REGEXP_EXTRACT_OPTIONALS          LanguageFeature = 13017
	LanguageFeature_FEATURE_V_1_3_DATE_TIME_CONSTRUCTORS                  LanguageFeature = 13018
	LanguageFeature_FEATURE_V_1_3_DATE_ARITHMETICS                        LanguageFeature = 13019
	LanguageFeature_FEATURE_V_1_3_ADDITIONAL_STRING_FUNCTIONS             LanguageFeature = 13020
	LanguageFeature_FEATURE_V_1_3_WITH_GROUP_ROWS                         LanguageFeature = 13021
	LanguageFeature_FEATURE_V_1_3_EXTENDED_DATE_TIME_SIGNATURES           LanguageFeature = 13022
	LanguageFeature_FEATURE_V_1_3_EXTENDED_GEOGRAPHY_PARSERS              LanguageFeature = 13023
	LanguageFeature_FEATURE_V_1_3_INLINE_LAMBDA_ARGUMENT                  LanguageFeature = 13024
	LanguageFeature_FEATURE_EXPERIMENTAL_MODULES                          LanguageFeature = 999002
	LanguageFeature_FEATURE_TEST_IDEALLY_ENABLED_BUT_IN_DEVELOPMENT       LanguageFeature = 999991
	LanguageFeature_FEATURE_TEST_IDEALLY_DISABLED                         LanguageFeature = 999992
	LanguageFeature_FEATURE_TEST_IDEALLY_DISABLED_AND_IN_DEVELOPMENT      LanguageFeature = 999993
	LanguageFeature___LanguageFeature__switch_must_have_a_default__       LanguageFeature = -1
)

var LanguageFeature_name = map[int32]string{
	1:      "FEATURE_ANALYTIC_FUNCTIONS",
	2:      "FEATURE_TABLESAMPLE",
	3:      "FEATURE_DISALLOW_GROUP_BY_FLOAT",
	5:      "FEATURE_TIMESTAMP_NANOS",
	6:      "FEATURE_DML_UPDATE_WITH_JOIN",
	8:      "FEATURE_TABLE_VALUED_FUNCTIONS",
	9:      "FEATURE_CREATE_AGGREGATE_FUNCTION",
	10:     "FEATURE_CREATE_TABLE_FUNCTION",
	12:     "FEATURE_GROUP_BY_ROLLUP",
	13:     "FEATURE_TEMPLATE_FUNCTIONS",
	14:     "FEATURE_CREATE_TABLE_PARTITION_BY",
	15:     "FEATURE_CREATE_TABLE_CLUSTER_BY",
	16:     "FEATURE_NUMERIC_TYPE",
	17:     "FEATURE_CREATE_TABLE_NOT_NULL",
	18:     "FEATURE_CREATE_TABLE_FIELD_ANNOTATIONS",
	19:     "FEATURE_CREATE_TABLE_AS_SELECT_COLUMN_LIST",
	20:     "FEATURE_DISALLOW_NULL_PRIMARY_KEYS",
	21:     "FEATURE_DISALLOW_PRIMARY_KEY_UPDATES",
	22:     "FEATURE_TABLESAMPLE_FROM_TABLE_VALUED_FUNCTIONS",
	23:     "FEATURE_ENCRYPTION",
	25:     "FEATURE_GEOGRAPHY",
	26:     "FEATURE_STRATIFIED_RESERVOIR_TABLESAMPLE",
	27:     "FEATURE_FOREIGN_KEYS",
	28:     "FEATURE_BETWEEN_UINT64_INT64",
	29:     "FEATURE_CHECK_CONSTRAINT",
	30:     "FEATURE_PARAMETERS_IN_GRANTEE_LIST",
	31:     "FEATURE_NAMED_ARGUMENTS",
	32:     "FEATURE_ALLOW_LEGACY_ROW_ACCESS_POLICY_SYNTAX",
	33:     "FEATURE_CREATE_MATERIALIZED_VIEW_PARTITION_BY",
	34:     "FEATURE_CREATE_MATERIALIZED_VIEW_CLUSTER_BY",
	35:     "FEATURE_CREATE_EXTERNAL_TABLE_WITH_TABLE_ELEMENT_LIST",
	40:     "FEATURE_UNENFORCED_PRIMARY_KEYS",
	41:     "FEATURE_BIGNUMERIC_TYPE",
	42:     "FEATURE_EXTENDED_TYPES",
	43:     "FEATURE_JSON_TYPE",
	44:     "FEATURE_JSON_NO_VALIDATION",
	46:     "FEATURE_JSON_LEGACY_PARSE",
	47:     "FEATURE_CREATE_EXTERNAL_TABLE_WITH_PARTITION_COLUMNS",
	48:     "FEATURE_NO_ADVANCED_NUMERIC_MATH_SIGNATURES",
	49:     "FEATURE_INTERVAL_TYPE",
	11001:  "FEATURE_V_1_1_ORDER_BY_COLLATE",
	11002:  "FEATURE_V_1_1_WITH_ON_SUBQUERY",
	11003:  "FEATURE_V_1_1_SELECT_STAR_EXCEPT_REPLACE",
	11004:  "FEATURE_V_1_1_ORDER_BY_IN_AGGREGATE",
	11005:  "FEATURE_V_1_1_CAST_DIFFERENT_ARRAY_TYPES",
	11006:  "FEATURE_V_1_1_ARRAY_EQUALITY",
	11007:  "FEATURE_V_1_1_LIMIT_IN_AGGREGATE",
	11008:  "FEATURE_V_1_1_HAVING_IN_AGGREGATE",
	11009:  "FEATURE_V_1_1_NULL_HANDLING_MODIFIER_IN_ANALYTIC",
	11010:  "FEATURE_V_1_1_NULL_HANDLING_MODIFIER_IN_AGGREGATE",
	11011:  "FEATURE_V_1_1_FOR_SYSTEM_TIME_AS_OF",
	12001:  "FEATURE_V_1_2_CIVIL_TIME",
	12002:  "FEATURE_V_1_2_SAFE_FUNCTION_CALL",
	12003:  "FEATURE_V_1_2_GROUP_BY_STRUCT",
	12004:  "FEATURE_V_1_2_PROTO_EXTENSIONS_WITH_NEW",
	12005:  "FEATURE_V_1_2_GROUP_BY_ARRAY",
	12006:  "FEATURE_V_1_2_PROTO_EXTENSIONS_WITH_SET",
	12007:  "FEATURE_V_1_2_CORRELATED_REFS_IN_NESTED_DML",
	12008:  "FEATURE_V_1_2_WEEK_WITH_WEEKDAY",
	12009:  "FEATURE_V_1_2_ARRAY_ELEMENTS_WITH_SET",
	12010:  "FEATURE_V_1_2_NESTED_UPDATE_DELETE_WITH_OFFSET",
	12011:  "FEATURE_V_1_2_GENERATED_COLUMNS",
	13001:  "FEATURE_V_1_3_PROTO_DEFAULT_IF_NULL",
	13002:  "FEATURE_V_1_3_EXTRACT_FROM_PROTO",
	13003:  "FEATURE_V_1_3_DISALLOW_PROTO3_HAS_SCALAR_FIELD",
	13004:  "FEATURE_V_1_3_ARRAY_ORDERING",
	13005:  "FEATURE_V_1_3_OMIT_INSERT_COLUMN_LIST",
	13006:  "FEATURE_V_1_3_IGNORE_PROTO3_USE_DEFAULTS",
	13007:  "FEATURE_V_1_3_REPLACE_FIELDS",
	13008:  "FEATURE_V_1_3_NULLS_FIRST_LAST_IN_ORDER_BY",
	13009:  "FEATURE_V_1_3_ALLOW_DASHES_IN_TABLE_NAME",
	13010:  "FEATURE_V_1_3_CONCAT_MIXED_TYPES",
	13011:  "FEATURE_V_1_3_WITH_RECURSIVE",
	13012:  "FEATURE_V_1_3_PROTO_MAPS",
	13013:  "FEATURE_V_1_3_ENUM_VALUE_DESCRIPTOR_PROTO",
	13014:  "FEATURE_V_1_3_DECIMAL_ALIAS",
	13015:  "FEATURE_V_1_3_UNNEST_AND_FLATTEN_ARRAYS",
	13016:  "FEATURE_V_1_3_ALLOW_CONSECUTIVE_ON",
	13017:  "FEATURE_V_1_3_ALLOW_REGEXP_EXTRACT_OPTIONALS",
	13018:  "FEATURE_V_1_3_DATE_TIME_CONSTRUCTORS",
	13019:  "FEATURE_V_1_3_DATE_ARITHMETICS",
	13020:  "FEATURE_V_1_3_ADDITIONAL_STRING_FUNCTIONS",
	13021:  "FEATURE_V_1_3_WITH_GROUP_ROWS",
	13022:  "FEATURE_V_1_3_EXTENDED_DATE_TIME_SIGNATURES",
	13023:  "FEATURE_V_1_3_EXTENDED_GEOGRAPHY_PARSERS",
	13024:  "FEATURE_V_1_3_INLINE_LAMBDA_ARGUMENT",
	999002: "FEATURE_EXPERIMENTAL_MODULES",
	999991: "FEATURE_TEST_IDEALLY_ENABLED_BUT_IN_DEVELOPMENT",
	999992: "FEATURE_TEST_IDEALLY_DISABLED",
	999993: "FEATURE_TEST_IDEALLY_DISABLED_AND_IN_DEVELOPMENT",
	-1:     "__LanguageFeature__switch_must_have_a_default__",
}

var LanguageFeature_value = map[string]int32{
	"FEATURE_ANALYTIC_FUNCTIONS":                            1,
	"FEATURE_TABLESAMPLE":                                   2,
	"FEATURE_DISALLOW_GROUP_BY_FLOAT":                       3,
	"FEATURE_TIMESTAMP_NANOS":                               5,
	"FEATURE_DML_UPDATE_WITH_JOIN":                          6,
	"FEATURE_TABLE_VALUED_FUNCTIONS":                        8,
	"FEATURE_CREATE_AGGREGATE_FUNCTION":                     9,
	"FEATURE_CREATE_TABLE_FUNCTION":                         10,
	"FEATURE_GROUP_BY_ROLLUP":                               12,
	"FEATURE_TEMPLATE_FUNCTIONS":                            13,
	"FEATURE_CREATE_TABLE_PARTITION_BY":                     14,
	"FEATURE_CREATE_TABLE_CLUSTER_BY":                       15,
	"FEATURE_NUMERIC_TYPE":                                  16,
	"FEATURE_CREATE_TABLE_NOT_NULL":                         17,
	"FEATURE_CREATE_TABLE_FIELD_ANNOTATIONS":                18,
	"FEATURE_CREATE_TABLE_AS_SELECT_COLUMN_LIST":            19,
	"FEATURE_DISALLOW_NULL_PRIMARY_KEYS":                    20,
	"FEATURE_DISALLOW_PRIMARY_KEY_UPDATES":                  21,
	"FEATURE_TABLESAMPLE_FROM_TABLE_VALUED_FUNCTIONS":       22,
	"FEATURE_ENCRYPTION":                                    23,
	"FEATURE_GEOGRAPHY":                                     25,
	"FEATURE_STRATIFIED_RESERVOIR_TABLESAMPLE":              26,
	"FEATURE_FOREIGN_KEYS":                                  27,
	"FEATURE_BETWEEN_UINT64_INT64":                          28,
	"FEATURE_CHECK_CONSTRAINT":                              29,
	"FEATURE_PARAMETERS_IN_GRANTEE_LIST":                    30,
	"FEATURE_NAMED_ARGUMENTS":                               31,
	"FEATURE_ALLOW_LEGACY_ROW_ACCESS_POLICY_SYNTAX":         32,
	"FEATURE_CREATE_MATERIALIZED_VIEW_PARTITION_BY":         33,
	"FEATURE_CREATE_MATERIALIZED_VIEW_CLUSTER_BY":           34,
	"FEATURE_CREATE_EXTERNAL_TABLE_WITH_TABLE_ELEMENT_LIST": 35,
	"FEATURE_UNENFORCED_PRIMARY_KEYS":                       40,
	"FEATURE_BIGNUMERIC_TYPE":                               41,
	"FEATURE_EXTENDED_TYPES":                                42,
	"FEATURE_JSON_TYPE":                                     43,
	"FEATURE_JSON_NO_VALIDATION":                            44,
	"FEATURE_JSON_LEGACY_PARSE":                             46,
	"FEATURE_CREATE_EXTERNAL_TABLE_WITH_PARTITION_COLUMNS":  47,
	"FEATURE_NO_ADVANCED_NUMERIC_MATH_SIGNATURES":           48,
	"FEATURE_INTERVAL_TYPE":                                 49,
	"FEATURE_V_1_1_ORDER_BY_COLLATE":                        11001,
	"FEATURE_V_1_1_WITH_ON_SUBQUERY":                        11002,
	"FEATURE_V_1_1_SELECT_STAR_EXCEPT_REPLACE":              11003,
	"FEATURE_V_1_1_ORDER_BY_IN_AGGREGATE":                   11004,
	"FEATURE_V_1_1_CAST_DIFFERENT_ARRAY_TYPES":              11005,
	"FEATURE_V_1_1_ARRAY_EQUALITY":                          11006,
	"FEATURE_V_1_1_LIMIT_IN_AGGREGATE":                      11007,
	"FEATURE_V_1_1_HAVING_IN_AGGREGATE":                     11008,
	"FEATURE_V_1_1_NULL_HANDLING_MODIFIER_IN_ANALYTIC":      11009,
	"FEATURE_V_1_1_NULL_HANDLING_MODIFIER_IN_AGGREGATE":     11010,
	"FEATURE_V_1_1_FOR_SYSTEM_TIME_AS_OF":                   11011,
	"FEATURE_V_1_2_CIVIL_TIME":                              12001,
	"FEATURE_V_1_2_SAFE_FUNCTION_CALL":                      12002,
	"FEATURE_V_1_2_GROUP_BY_STRUCT":                         12003,
	"FEATURE_V_1_2_PROTO_EXTENSIONS_WITH_NEW":               12004,
	"FEATURE_V_1_2_GROUP_BY_ARRAY":                          12005,
	"FEATURE_V_1_2_PROTO_EXTENSIONS_WITH_SET":               12006,
	"FEATURE_V_1_2_CORRELATED_REFS_IN_NESTED_DML":           12007,
	"FEATURE_V_1_2_WEEK_WITH_WEEKDAY":                       12008,
	"FEATURE_V_1_2_ARRAY_ELEMENTS_WITH_SET":                 12009,
	"FEATURE_V_1_2_NESTED_UPDATE_DELETE_WITH_OFFSET":        12010,
	"FEATURE_V_1_2_GENERATED_COLUMNS":                       12011,
	"FEATURE_V_1_3_PROTO_DEFAULT_IF_NULL":                   13001,
	"FEATURE_V_1_3_EXTRACT_FROM_PROTO":                      13002,
	"FEATURE_V_1_3_DISALLOW_PROTO3_HAS_SCALAR_FIELD":        13003,
	"FEATURE_V_1_3_ARRAY_ORDERING":                          13004,
	"FEATURE_V_1_3_OMIT_INSERT_COLUMN_LIST":                 13005,
	"FEATURE_V_1_3_IGNORE_PROTO3_USE_DEFAULTS":              13006,
	"FEATURE_V_1_3_REPLACE_FIELDS":                          13007,
	"FEATURE_V_1_3_NULLS_FIRST_LAST_IN_ORDER_BY":            13008,
	"FEATURE_V_1_3_ALLOW_DASHES_IN_TABLE_NAME":              13009,
	"FEATURE_V_1_3_CONCAT_MIXED_TYPES":                      13010,
	"FEATURE_V_1_3_WITH_RECURSIVE":                          13011,
	"FEATURE_V_1_3_PROTO_MAPS":                              13012,
	"FEATURE_V_1_3_ENUM_VALUE_DESCRIPTOR_PROTO":             13013,
	"FEATURE_V_1_3_DECIMAL_ALIAS":                           13014,
	"FEATURE_V_1_3_UNNEST_AND_FLATTEN_ARRAYS":               13015,
	"FEATURE_V_1_3_ALLOW_CONSECUTIVE_ON":                    13016,
	"FEATURE_V_1_3_ALLOW_REGEXP_EXTRACT_OPTIONALS":          13017,
	"FEATURE_V_1_3_DATE_TIME_CONSTRUCTORS":                  13018,
	"FEATURE_V_1_3_DATE_ARITHMETICS":                        13019,
	"FEATURE_V_1_3_ADDITIONAL_STRING_FUNCTIONS":             13020,
	"FEATURE_V_1_3_WITH_GROUP_ROWS":                         13021,
	"FEATURE_V_1_3_EXTENDED_DATE_TIME_SIGNATURES":           13022,
	"FEATURE_V_1_3_EXTENDED_GEOGRAPHY_PARSERS":              13023,
	"FEATURE_V_1_3_INLINE_LAMBDA_ARGUMENT":                  13024,
	"FEATURE_EXPERIMENTAL_MODULES":                          999002,
	"FEATURE_TEST_IDEALLY_ENABLED_BUT_IN_DEVELOPMENT":       999991,
	"FEATURE_TEST_IDEALLY_DISABLED":                         999992,
	"FEATURE_TEST_IDEALLY_DISABLED_AND_IN_DEVELOPMENT":      999993,
	"__LanguageFeature__switch_must_have_a_default__":       -1,
}

func (x LanguageFeature) Enum() *LanguageFeature {
	p := new(LanguageFeature)
	*p = x
	return p
}

func (x LanguageFeature) String() string {
	return proto.EnumName(LanguageFeature_name, int32(x))
}

func (x *LanguageFeature) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LanguageFeature_value, data, "LanguageFeature")
	if err != nil {
		return err
	}
	*x = LanguageFeature(value)
	return nil
}

func (LanguageFeature) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{1}
}

type ResolvedASTRewrite int32

const (
	ResolvedASTRewrite_REWRITE_INVALID_DO_NOT_USE ResolvedASTRewrite = 0
	ResolvedASTRewrite_REWRITE_FLATTEN            ResolvedASTRewrite = 1
)

var ResolvedASTRewrite_name = map[int32]string{
	0: "REWRITE_INVALID_DO_NOT_USE",
	1: "REWRITE_FLATTEN",
}

var ResolvedASTRewrite_value = map[string]int32{
	"REWRITE_INVALID_DO_NOT_USE": 0,
	"REWRITE_FLATTEN":            1,
}

func (x ResolvedASTRewrite) Enum() *ResolvedASTRewrite {
	p := new(ResolvedASTRewrite)
	*p = x
	return p
}

func (x ResolvedASTRewrite) String() string {
	return proto.EnumName(ResolvedASTRewrite_name, int32(x))
}

func (x *ResolvedASTRewrite) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedASTRewrite_value, data, "ResolvedASTRewrite")
	if err != nil {
		return err
	}
	*x = ResolvedASTRewrite(value)
	return nil
}

func (ResolvedASTRewrite) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{2}
}

type NameResolutionMode int32

const (
	NameResolutionMode_NAME_RESOLUTION_DEFAULT NameResolutionMode = 0
	NameResolutionMode_NAME_RESOLUTION_STRICT  NameResolutionMode = 1
)

var NameResolutionMode_name = map[int32]string{
	0: "NAME_RESOLUTION_DEFAULT",
	1: "NAME_RESOLUTION_STRICT",
}

var NameResolutionMode_value = map[string]int32{
	"NAME_RESOLUTION_DEFAULT": 0,
	"NAME_RESOLUTION_STRICT":  1,
}

func (x NameResolutionMode) Enum() *NameResolutionMode {
	p := new(NameResolutionMode)
	*p = x
	return p
}

func (x NameResolutionMode) String() string {
	return proto.EnumName(NameResolutionMode_name, int32(x))
}

func (x *NameResolutionMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(NameResolutionMode_value, data, "NameResolutionMode")
	if err != nil {
		return err
	}
	*x = NameResolutionMode(value)
	return nil
}

func (NameResolutionMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{3}
}

type ProductMode int32

const (
	ProductMode_PRODUCT_INTERNAL ProductMode = 0
	ProductMode_PRODUCT_EXTERNAL ProductMode = 1
)

var ProductMode_name = map[int32]string{
	0: "PRODUCT_INTERNAL",
	1: "PRODUCT_EXTERNAL",
}

var ProductMode_value = map[string]int32{
	"PRODUCT_INTERNAL": 0,
	"PRODUCT_EXTERNAL": 1,
}

func (x ProductMode) Enum() *ProductMode {
	p := new(ProductMode)
	*p = x
	return p
}

func (x ProductMode) String() string {
	return proto.EnumName(ProductMode_name, int32(x))
}

func (x *ProductMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ProductMode_value, data, "ProductMode")
	if err != nil {
		return err
	}
	*x = ProductMode(value)
	return nil
}

func (ProductMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{4}
}

type StatementContext int32

const (
	StatementContext_CONTEXT_DEFAULT StatementContext = 0
	StatementContext_CONTEXT_MODULE  StatementContext = 1
)

var StatementContext_name = map[int32]string{
	0: "CONTEXT_DEFAULT",
	1: "CONTEXT_MODULE",
}

var StatementContext_value = map[string]int32{
	"CONTEXT_DEFAULT": 0,
	"CONTEXT_MODULE":  1,
}

func (x StatementContext) Enum() *StatementContext {
	p := new(StatementContext)
	*p = x
	return p
}

func (x StatementContext) String() string {
	return proto.EnumName(StatementContext_name, int32(x))
}

func (x *StatementContext) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatementContext_value, data, "StatementContext")
	if err != nil {
		return err
	}
	*x = StatementContext(value)
	return nil
}

func (StatementContext) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{5}
}

type ErrorMessageMode int32

const (
	ErrorMessageMode_ERROR_MESSAGE_WITH_PAYLOAD          ErrorMessageMode = 0
	ErrorMessageMode_ERROR_MESSAGE_ONE_LINE              ErrorMessageMode = 1
	ErrorMessageMode_ERROR_MESSAGE_MULTI_LINE_WITH_CARET ErrorMessageMode = 2
)

var ErrorMessageMode_name = map[int32]string{
	0: "ERROR_MESSAGE_WITH_PAYLOAD",
	1: "ERROR_MESSAGE_ONE_LINE",
	2: "ERROR_MESSAGE_MULTI_LINE_WITH_CARET",
}

var ErrorMessageMode_value = map[string]int32{
	"ERROR_MESSAGE_WITH_PAYLOAD":          0,
	"ERROR_MESSAGE_ONE_LINE":              1,
	"ERROR_MESSAGE_MULTI_LINE_WITH_CARET": 2,
}

func (x ErrorMessageMode) Enum() *ErrorMessageMode {
	p := new(ErrorMessageMode)
	*p = x
	return p
}

func (x ErrorMessageMode) String() string {
	return proto.EnumName(ErrorMessageMode_name, int32(x))
}

func (x *ErrorMessageMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorMessageMode_value, data, "ErrorMessageMode")
	if err != nil {
		return err
	}
	*x = ErrorMessageMode(value)
	return nil
}

func (ErrorMessageMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{6}
}

type ParameterMode int32

const (
	ParameterMode_PARAMETER_NAMED      ParameterMode = 0
	ParameterMode_PARAMETER_POSITIONAL ParameterMode = 1
	ParameterMode_PARAMETER_NONE       ParameterMode = 2
)

var ParameterMode_name = map[int32]string{
	0: "PARAMETER_NAMED",
	1: "PARAMETER_POSITIONAL",
	2: "PARAMETER_NONE",
}

var ParameterMode_value = map[string]int32{
	"PARAMETER_NAMED":      0,
	"PARAMETER_POSITIONAL": 1,
	"PARAMETER_NONE":       2,
}

func (x ParameterMode) Enum() *ParameterMode {
	p := new(ParameterMode)
	*p = x
	return p
}

func (x ParameterMode) String() string {
	return proto.EnumName(ParameterMode_name, int32(x))
}

func (x *ParameterMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ParameterMode_value, data, "ParameterMode")
	if err != nil {
		return err
	}
	*x = ParameterMode(value)
	return nil
}

func (ParameterMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{7}
}

type LanguageFeatureOptions struct {
	IdeallyEnabled       *bool    `protobuf:"varint,1,opt,name=ideally_enabled,json=ideallyEnabled,def=1" json:"ideally_enabled,omitempty"`
	InDevelopment        *bool    `protobuf:"varint,2,opt,name=in_development,json=inDevelopment,def=0" json:"in_development,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LanguageFeatureOptions) Reset()         { *m = LanguageFeatureOptions{} }
func (m *LanguageFeatureOptions) String() string { return proto.CompactTextString(m) }
func (*LanguageFeatureOptions) ProtoMessage()    {}
func (*LanguageFeatureOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{0}
}

func (m *LanguageFeatureOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LanguageFeatureOptions.Unmarshal(m, b)
}
func (m *LanguageFeatureOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LanguageFeatureOptions.Marshal(b, m, deterministic)
}
func (m *LanguageFeatureOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LanguageFeatureOptions.Merge(m, src)
}
func (m *LanguageFeatureOptions) XXX_Size() int {
	return xxx_messageInfo_LanguageFeatureOptions.Size(m)
}
func (m *LanguageFeatureOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_LanguageFeatureOptions.DiscardUnknown(m)
}

var xxx_messageInfo_LanguageFeatureOptions proto.InternalMessageInfo

const Default_LanguageFeatureOptions_IdeallyEnabled bool = true
const Default_LanguageFeatureOptions_InDevelopment bool = false

func (m *LanguageFeatureOptions) GetIdeallyEnabled() bool {
	if m != nil && m.IdeallyEnabled != nil {
		return *m.IdeallyEnabled
	}
	return Default_LanguageFeatureOptions_IdeallyEnabled
}

func (m *LanguageFeatureOptions) GetInDevelopment() bool {
	if m != nil && m.InDevelopment != nil {
		return *m.InDevelopment
	}
	return Default_LanguageFeatureOptions_InDevelopment
}

type ResolvedASTRewriteOptions struct {
	DefaultEnabled       *bool    `protobuf:"varint,1,opt,name=default_enabled,json=defaultEnabled" json:"default_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedASTRewriteOptions) Reset()         { *m = ResolvedASTRewriteOptions{} }
func (m *ResolvedASTRewriteOptions) String() string { return proto.CompactTextString(m) }
func (*ResolvedASTRewriteOptions) ProtoMessage()    {}
func (*ResolvedASTRewriteOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_61302f5f7ae8ff85, []int{1}
}

func (m *ResolvedASTRewriteOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedASTRewriteOptions.Unmarshal(m, b)
}
func (m *ResolvedASTRewriteOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedASTRewriteOptions.Marshal(b, m, deterministic)
}
func (m *ResolvedASTRewriteOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedASTRewriteOptions.Merge(m, src)
}
func (m *ResolvedASTRewriteOptions) XXX_Size() int {
	return xxx_messageInfo_ResolvedASTRewriteOptions.Size(m)
}
func (m *ResolvedASTRewriteOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedASTRewriteOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedASTRewriteOptions proto.InternalMessageInfo

func (m *ResolvedASTRewriteOptions) GetDefaultEnabled() bool {
	if m != nil && m.DefaultEnabled != nil {
		return *m.DefaultEnabled
	}
	return false
}

var E_LanguageFeatureOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*LanguageFeatureOptions)(nil),
	Field:         170219291,
	Name:          "zetasql.language_feature_options",
	Tag:           "bytes,170219291,opt,name=language_feature_options",
	Filename:      "zetasql/public/options.proto",
}

var E_RewriteOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*ResolvedASTRewriteOptions)(nil),
	Field:         336783472,
	Name:          "zetasql.rewrite_options",
	Tag:           "bytes,336783472,opt,name=rewrite_options",
	Filename:      "zetasql/public/options.proto",
}

func init() {
	proto.RegisterEnum("zetasql.LanguageVersion", LanguageVersion_name, LanguageVersion_value)
	proto.RegisterEnum("zetasql.LanguageFeature", LanguageFeature_name, LanguageFeature_value)
	proto.RegisterEnum("zetasql.ResolvedASTRewrite", ResolvedASTRewrite_name, ResolvedASTRewrite_value)
	proto.RegisterEnum("zetasql.NameResolutionMode", NameResolutionMode_name, NameResolutionMode_value)
	proto.RegisterEnum("zetasql.ProductMode", ProductMode_name, ProductMode_value)
	proto.RegisterEnum("zetasql.StatementContext", StatementContext_name, StatementContext_value)
	proto.RegisterEnum("zetasql.ErrorMessageMode", ErrorMessageMode_name, ErrorMessageMode_value)
	proto.RegisterEnum("zetasql.ParameterMode", ParameterMode_name, ParameterMode_value)
	proto.RegisterType((*LanguageFeatureOptions)(nil), "zetasql.LanguageFeatureOptions")
	proto.RegisterType((*ResolvedASTRewriteOptions)(nil), "zetasql.ResolvedASTRewriteOptions")
	proto.RegisterExtension(E_LanguageFeatureOptions)
	proto.RegisterExtension(E_RewriteOptions)
}

func init() { proto.RegisterFile("zetasql/public/options.proto", fileDescriptor_61302f5f7ae8ff85) }

var fileDescriptor_61302f5f7ae8ff85 = []byte{
	// 2305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0x4b, 0x70, 0x1c, 0x47,
	0xdd, 0xd7, 0xfa, 0x73, 0xbe, 0x4f, 0x5f, 0xe7, 0x8b, 0xd4, 0x69, 0x27, 0x8e, 0xa2, 0xf8, 0x21,
	0xcb, 0x76, 0xec, 0x28, 0x96, 0x64, 0x5b, 0x49, 0xaa, 0xf2, 0xaa, 0xaf, 0x5a, 0x33, 0xff, 0x5d,
	0x75, 0xd2, 0xd3, 0x3d, 0xee, 0xee, 0x59, 0x69, 0x53, 0xa5, 0xea, 0x5a, 0x5b, 0x6d, 0x47, 0x55,
	0x2b, 0xad, 0x59, 0xed, 0x26, 0xc0, 0x05, 0x08, 0xa9, 0xa2, 0xb8, 0x71, 0xe1, 0xc4, 0x85, 0x33,
	0x45, 0x71, 0x05, 0xee, 0x1c, 0x80, 0xf0, 0x08, 0x6f, 0x08, 0x04, 0xc2, 0xfb, 0x75, 0x81, 0x1b,
	0x8f, 0x40, 0xa8, 0x9e, 0x99, 0xdd, 0x99, 0x59, 0xad, 0x0b, 0xa3, 0x83, 0x6a, 0xb6, 0xfb, 0xf7,
	0x7f, 0xf4, 0xff, 0xdd, 0x8d, 0x4e, 0x7c, 0xd0, 0xf5, 0xdb, 0x07, 0xef, 0xeb, 0xac, 0xde, 0x1e,
	0x5c, 0xef, 0xec, 0xde, 0x58, 0xed, 0xde, 0xee, 0xef, 0x76, 0xf7, 0x0f, 0x56, 0x6e, 0xf7, 0xba,
	0xfd, 0x2e, 0xf9, 0x9f, 0x7c, 0x77, 0x7e, 0xe1, 0x56, 0xb7, 0x7b, 0xab, 0xe3, 0x56, 0xd3, 0xe5,
	0xeb, 0x83, 0x9b, 0xab, 0x3b, 0xee, 0xe0, 0x46, 0x6f, 0xf7, 0x76, 0xbf, 0xdb, 0xcb, 0xa0, 0x8b,
	0x03, 0x74, 0x9c, 0xb7, 0xf7, 0x6f, 0x0d, 0xda, 0xb7, 0x5c, 0xdd, 0xb5, 0xfb, 0x83, 0x9e, 0x93,
	0x19, 0x2b, 0xb2, 0x8c, 0x66, 0x77, 0x77, 0x5c, 0xbb, 0xd3, 0xf9, 0x80, 0x75, 0xfb, 0xed, 0xeb,
	0x1d, 0xb7, 0x33, 0x57, 0x5b, 0xa8, 0x5d, 0x9c, 0x7e, 0xe6, 0x68, 0xbf, 0x37, 0x70, 0x6a, 0x26,
	0xdf, 0x84, 0x6c, 0x8f, 0x5c, 0x42, 0x33, 0xbb, 0xfb, 0x76, 0xc7, 0xbd, 0xe2, 0x3a, 0xdd, 0xdb,
	0x7b, 0x6e, 0xbf, 0x3f, 0x77, 0x24, 0x45, 0xdf, 0x73, 0xb3, 0xdd, 0x39, 0x70, 0xea, 0xbe, 0xdd,
	0xfd, 0xb0, 0xd8, 0x5b, 0x0c, 0xd1, 0xc3, 0xca, 0x1d, 0x74, 0x3b, 0xaf, 0xb8, 0x1d, 0xaa, 0x8d,
	0x72, 0xaf, 0xf6, 0x76, 0xfb, 0x23, 0xc9, 0x17, 0xd0, 0xec, 0x8e, 0xbb, 0xd9, 0x1e, 0x74, 0xfa,
	0x55, 0xc9, 0x6a, 0x26, 0x5f, 0xce, 0x65, 0x2e, 0x7d, 0xb6, 0x86, 0x66, 0x87, 0xda, 0x37, 0x5d,
	0xef, 0x60, 0xb7, 0xbb, 0x4f, 0x8e, 0xa1, 0xd9, 0x26, 0x28, 0xcd, 0xa4, 0xb0, 0x41, 0xa2, 0x14,
	0x08, 0x83, 0x6b, 0x04, 0xa3, 0x7b, 0x87, 0x8b, 0x57, 0xec, 0x65, 0xfc, 0x09, 0x51, 0x5d, 0xb9,
	0x82, 0xff, 0x92, 0x54, 0x57, 0xae, 0xe2, 0x77, 0xb6, 0xab, 0x2b, 0x6b, 0xf8, 0xcb, 0x8e, 0x3c,
	0x87, 0x56, 0xad, 0x1d, 0x93, 0x68, 0xed, 0xc1, 0xab, 0xbb, 0xfd, 0x1b, 0x2f, 0xdb, 0xbd, 0xc1,
	0x41, 0xdf, 0xbe, 0xdc, 0x7e, 0xc5, 0xd9, 0xb6, 0x1d, 0xea, 0x6f, 0xf1, 0x7b, 0xc3, 0xbf, 0xda,
	0xd2, 0x97, 0x4e, 0x15, 0xea, 0xe6, 0xc6, 0x26, 0xa7, 0xd0, 0x7c, 0x1d, 0xa8, 0x49, 0x14, 0x58,
	0x2a, 0x28, 0x6f, 0x19, 0x16, 0xd8, 0x7a, 0x22, 0x02, 0xc3, 0xa4, 0xd0, 0xb8, 0x46, 0x1e, 0x42,
	0xc7, 0x86, 0xfb, 0x86, 0xae, 0x73, 0xd0, 0x34, 0x8a, 0x39, 0xe0, 0x23, 0x64, 0x19, 0x9d, 0x1e,
	0x6e, 0x84, 0x4c, 0x53, 0xce, 0xe5, 0xa6, 0x6d, 0x28, 0x99, 0xc4, 0x76, 0xbd, 0x65, 0xeb, 0x5c,
	0x52, 0x83, 0xff, 0x6b, 0x7e, 0xfa, 0xad, 0x3f, 0x7f, 0xe6, 0xe3, 0xf7, 0x1c, 0x99, 0x9e, 0x22,
	0x8f, 0xa0, 0x87, 0x46, 0x7c, 0x58, 0x04, 0xda, 0xd0, 0x28, 0xb6, 0x82, 0x0a, 0xa9, 0xf1, 0x3d,
	0x64, 0x01, 0x9d, 0x18, 0xf1, 0x8a, 0xb8, 0x4d, 0xe2, 0x90, 0x1a, 0xb0, 0x9b, 0xcc, 0x6c, 0xd8,
	0x17, 0x24, 0x13, 0xf8, 0xbf, 0xc9, 0x22, 0x3a, 0x55, 0x51, 0xc3, 0x36, 0x29, 0x4f, 0x20, 0x2c,
	0xa9, 0x3a, 0x4d, 0xce, 0xa3, 0x33, 0x43, 0x4c, 0xa0, 0xc0, 0x73, 0xa0, 0x8d, 0x86, 0x82, 0x86,
	0xff, 0x1a, 0xe2, 0xf0, 0xff, 0x92, 0x33, 0xe8, 0xe4, 0x18, 0x2c, 0xe3, 0x38, 0x82, 0xa0, 0xb2,
	0xb2, 0xa3, 0x23, 0x29, 0xc9, 0x79, 0x12, 0xe3, 0xff, 0x2b, 0x5b, 0xcc, 0x40, 0x14, 0xf3, 0x32,
	0x7b, 0x8d, 0xef, 0x9b, 0xa0, 0x46, 0xc6, 0x3f, 0xa6, 0xca, 0x30, 0x0f, 0xb2, 0xeb, 0x2d, 0x3c,
	0x43, 0xce, 0x16, 0xf6, 0xab, 0xc0, 0x02, 0x9e, 0x68, 0x03, 0xca, 0x83, 0x66, 0xc9, 0x1c, 0x7a,
	0x60, 0x08, 0x12, 0x49, 0x04, 0x8a, 0x05, 0xd6, 0xb4, 0x62, 0xc0, 0xf8, 0x8e, 0xa7, 0x10, 0xd2,
	0x58, 0x91, 0x70, 0x8e, 0xef, 0x27, 0x4b, 0xe8, 0xd1, 0xc9, 0x07, 0x65, 0xc0, 0x43, 0x4b, 0x85,
	0x90, 0x86, 0x66, 0x4a, 0x13, 0xb2, 0x82, 0x96, 0x26, 0x62, 0xa9, 0xb6, 0x1a, 0x38, 0x04, 0xc6,
	0x06, 0x92, 0x27, 0x91, 0xb0, 0x9c, 0x69, 0x83, 0x8f, 0x91, 0xcb, 0x68, 0xf1, 0x90, 0xf7, 0xbd,
	0x58, 0x1b, 0x2b, 0x16, 0x51, 0xd5, 0xb2, 0x2f, 0x42, 0x4b, 0xe3, 0x07, 0x4a, 0x01, 0x70, 0x15,
	0x9d, 0x3b, 0x44, 0x51, 0x02, 0xe7, 0x4e, 0xd7, 0xf8, 0xc1, 0x12, 0xcd, 0x1a, 0x5a, 0x9d, 0x10,
	0x7c, 0xb6, 0xae, 0x64, 0x74, 0xa7, 0x30, 0x38, 0x4e, 0x8e, 0x23, 0x32, 0x24, 0x02, 0x11, 0xa8,
	0x56, 0x9c, 0x3a, 0xf5, 0x21, 0xf2, 0x20, 0xba, 0x7f, 0xe4, 0x54, 0x90, 0x0d, 0x45, 0xe3, 0x8d,
	0x16, 0x7e, 0x98, 0x5c, 0x42, 0x17, 0x87, 0xcb, 0xda, 0x28, 0x6a, 0x58, 0x9d, 0x41, 0x68, 0x15,
	0x68, 0x50, 0x4d, 0xc9, 0x54, 0x25, 0xea, 0xe7, 0xcb, 0x0e, 0xa9, 0x4b, 0x05, 0xac, 0x21, 0xb2,
	0x93, 0x3e, 0x42, 0x96, 0x8a, 0x18, 0x5e, 0x07, 0xb3, 0x09, 0x20, 0x6c, 0xc2, 0x84, 0x79, 0xea,
	0x09, 0x9b, 0xfe, 0xc7, 0x27, 0x86, 0xe7, 0xc2, 0x35, 0x72, 0x02, 0xcd, 0x8d, 0xac, 0xbd, 0x01,
	0xc1, 0x8b, 0x36, 0x90, 0xc2, 0x0b, 0x67, 0xc2, 0xe0, 0x93, 0xe4, 0xd1, 0xc2, 0xb6, 0x31, 0x55,
	0x34, 0x02, 0x03, 0x4a, 0x5b, 0x26, 0x6c, 0x43, 0x51, 0x61, 0x00, 0x32, 0x1f, 0x9c, 0x2a, 0x47,
	0xa9, 0xa0, 0x11, 0x84, 0x96, 0xaa, 0x46, 0x12, 0x81, 0x30, 0x1a, 0x9f, 0x26, 0x57, 0xd0, 0xf2,
	0x28, 0xaf, 0x53, 0x5b, 0x73, 0x68, 0xd0, 0xc0, 0x87, 0xf1, 0xa6, 0xa5, 0x41, 0x00, 0x5a, 0xdb,
	0x58, 0x72, 0x16, 0xb4, 0xac, 0x6e, 0x09, 0x43, 0xb7, 0xf0, 0x42, 0x99, 0x24, 0x8f, 0x81, 0x88,
	0x1a, 0x50, 0x8c, 0x72, 0xf6, 0x12, 0x84, 0xb6, 0xc9, 0x60, 0xb3, 0x1a, 0xc4, 0x67, 0xc8, 0x2a,
	0x7a, 0xfc, 0xdf, 0x92, 0x94, 0x02, 0x7a, 0x91, 0x3c, 0x8d, 0x9e, 0x1c, 0x23, 0x80, 0x2d, 0x03,
	0x4a, 0x50, 0x9e, 0x3b, 0x34, 0x4d, 0xfa, 0xec, 0x13, 0x38, 0xf8, 0xd3, 0x64, 0xc7, 0x3d, 0x5b,
	0x4e, 0x98, 0x44, 0x80, 0xa8, 0x4b, 0x15, 0x40, 0x58, 0x8d, 0xb7, 0x8b, 0xe4, 0x7c, 0x61, 0x93,
	0x75, 0xd6, 0xa8, 0xe4, 0xcc, 0x63, 0x25, 0x07, 0x9c, 0x43, 0xc7, 0x47, 0x31, 0xb2, 0x65, 0x40,
	0x84, 0x10, 0xa6, 0x20, 0x8d, 0x97, 0x4a, 0xa8, 0xd3, 0x45, 0xc4, 0xbc, 0xa0, 0xa5, 0xc8, 0xd8,
	0x3c, 0x5e, 0x02, 0x5c, 0x2c, 0x4a, 0x41, 0x0a, 0x10, 0xd2, 0x07, 0x24, 0x0b, 0xd3, 0xb4, 0xc2,
	0x97, 0x4a, 0xc8, 0x0b, 0xe8, 0xe1, 0x0a, 0x32, 0xf7, 0x46, 0x4c, 0x95, 0x06, 0xbc, 0x52, 0x02,
	0xae, 0xa3, 0x27, 0xee, 0xc2, 0x40, 0x85, 0x1b, 0xb2, 0xb4, 0xd4, 0x78, 0xb5, 0xc4, 0xe3, 0xe9,
	0xc2, 0x2b, 0x42, 0x5a, 0x1a, 0x36, 0xa9, 0xf0, 0xa6, 0x1a, 0x5a, 0x23, 0xa2, 0x66, 0xc3, 0x6a,
	0xd6, 0x10, 0x29, 0x44, 0xe3, 0xcb, 0x25, 0xd2, 0xb3, 0xe8, 0xc1, 0x21, 0x29, 0x13, 0x06, 0x54,
	0xd3, 0xcb, 0xf5, 0xc7, 0xbe, 0x52, 0x01, 0x8d, 0x8a, 0x71, 0xd3, 0x77, 0x2f, 0x2b, 0x55, 0x98,
	0x3a, 0xd8, 0x6b, 0xe3, 0xeb, 0x21, 0xfe, 0x6b, 0x72, 0x18, 0x94, 0x2a, 0x2e, 0x85, 0xd5, 0xc9,
	0xfa, 0xb5, 0x04, 0x54, 0x0b, 0xff, 0x2d, 0x21, 0xcb, 0x45, 0xf2, 0x65, 0xa0, 0xbc, 0xd8, 0x68,
	0x43, 0x95, 0x85, 0xad, 0x00, 0x62, 0x63, 0x15, 0xc4, 0x9c, 0x06, 0x80, 0xff, 0x9e, 0x90, 0x8b,
	0xe8, 0xec, 0x1d, 0x04, 0x33, 0x51, 0x14, 0x7b, 0xfc, 0xee, 0x04, 0xc6, 0x01, 0xd5, 0xc6, 0x86,
	0xac, 0x5e, 0x07, 0xdf, 0x92, 0x2d, 0x55, 0x8a, 0xb6, 0x72, 0x97, 0xff, 0x23, 0x21, 0x67, 0x8a,
	0xe4, 0xcd, 0xe0, 0xd9, 0x3e, 0x5c, 0x4b, 0x28, 0x67, 0xa6, 0x85, 0xff, 0x99, 0x90, 0xf3, 0x68,
	0xa1, 0x0a, 0xe1, 0x2c, 0x62, 0xa6, 0x2a, 0xf8, 0xbd, 0x84, 0x3c, 0x5a, 0x54, 0xff, 0x0c, 0xb6,
	0x41, 0x9b, 0x4c, 0x34, 0xaa, 0xb8, 0x0f, 0x37, 0xc9, 0x93, 0xe8, 0x72, 0x15, 0x97, 0x56, 0xcf,
	0x0d, 0x2a, 0x42, 0xee, 0xe1, 0x91, 0x0c, 0x7d, 0x21, 0x52, 0x29, 0x5d, 0xde, 0x97, 0xf1, 0x47,
	0x9a, 0xe4, 0x29, 0x74, 0xe5, 0xae, 0xc9, 0x46, 0xe2, 0x5e, 0x6b, 0x1e, 0xb6, 0x5c, 0x5d, 0x2a,
	0xab, 0x5b, 0xda, 0x40, 0x94, 0xf6, 0x63, 0x5f, 0xe8, 0x65, 0x1d, 0x7f, 0xb4, 0x49, 0x4e, 0x16,
	0xb5, 0xc9, 0x23, 0xaf, 0xda, 0x80, 0x35, 0x19, 0x4f, 0x41, 0xf8, 0xe7, 0xdb, 0xe3, 0x66, 0xb8,
	0x6a, 0x35, 0xad, 0x17, 0xfd, 0xcf, 0x06, 0x94, 0x73, 0xfc, 0x8b, 0x6d, 0xb2, 0x58, 0xb4, 0xa7,
	0x0c, 0x36, 0xea, 0xa3, 0xda, 0xa8, 0x24, 0x30, 0xf8, 0x97, 0xdb, 0xe4, 0x12, 0xba, 0x50, 0xc5,
	0xc4, 0x4a, 0x1a, 0x99, 0x25, 0xa4, 0x1f, 0x7a, 0x74, 0x16, 0x32, 0x02, 0x36, 0xf1, 0xaf, 0xb6,
	0xc7, 0x5d, 0x54, 0xe2, 0x98, 0xfa, 0x0a, 0xff, 0xfa, 0xae, 0x19, 0x6a, 0x30, 0xf8, 0x37, 0xdb,
	0xe4, 0x72, 0x91, 0x25, 0xf9, 0x41, 0xa5, 0x52, 0xe0, 0xc3, 0xd7, 0x97, 0xff, 0x7a, 0x5a, 0x71,
	0x05, 0x68, 0xff, 0x33, 0x8c, 0x38, 0xfe, 0xed, 0x36, 0x39, 0x57, 0x54, 0xa0, 0x8c, 0x62, 0x13,
	0xe0, 0xc5, 0x8c, 0xa7, 0xff, 0x0a, 0x69, 0x0b, 0xff, 0x6e, 0x9b, 0x2c, 0xa1, 0xf3, 0x55, 0x54,
	0x1e, 0x4b, 0x59, 0x35, 0x2b, 0xe9, 0xf0, 0xfb, 0x6d, 0xb2, 0x86, 0x56, 0xaa, 0xd8, 0x5c, 0x60,
	0x3e, 0x01, 0x85, 0xc0, 0x61, 0x38, 0x08, 0xc9, 0x7a, 0xdd, 0x13, 0xfd, 0x61, 0x82, 0x1a, 0x0d,
	0x10, 0xa0, 0x52, 0xbd, 0x87, 0xd5, 0xe0, 0x8f, 0xdb, 0xe3, 0x1e, 0x5f, 0xcb, 0x8d, 0x11, 0x42,
	0x9d, 0x26, 0xdc, 0x58, 0x56, 0xcf, 0xc6, 0x84, 0xaf, 0xb8, 0x71, 0x97, 0xae, 0x79, 0x83, 0x29,
	0x1a, 0x98, 0xac, 0xcf, 0xa6, 0x64, 0xf8, 0xab, 0x6e, 0x5c, 0xd7, 0xb5, 0x72, 0x1b, 0x97, 0x46,
	0xae, 0xd9, 0x0d, 0x3f, 0x2c, 0x04, 0x94, 0x53, 0x95, 0x8d, 0x18, 0xf8, 0x0d, 0x37, 0xee, 0xb5,
	0xb5, 0xdc, 0x18, 0x69, 0xde, 0x32, 0xd1, 0xc0, 0x5f, 0x73, 0xe3, 0xf6, 0x5a, 0xb3, 0x32, 0xcb,
	0x2b, 0x0d, 0xaa, 0x3a, 0x75, 0x7c, 0xdd, 0x8d, 0xa7, 0xf5, 0x9a, 0x65, 0x0d, 0x21, 0x7d, 0x9f,
	0xcc, 0x34, 0x48, 0x34, 0x0c, 0x0f, 0xa8, 0xf1, 0x37, 0x1c, 0x79, 0x7c, 0x5c, 0x7a, 0x5e, 0x4b,
	0x32, 0xfd, 0x34, 0xfe, 0xa6, 0x2b, 0x55, 0xb5, 0xd5, 0x62, 0x04, 0xca, 0xc0, 0xde, 0x3e, 0xda,
	0xd6, 0x99, 0xd2, 0xc6, 0x72, 0x5f, 0x3e, 0x98, 0x18, 0x15, 0x1c, 0xfc, 0xe6, 0x04, 0x65, 0x32,
	0x6b, 0x84, 0x54, 0x6f, 0x40, 0x1a, 0x3d, 0xf9, 0x44, 0x46, 0x23, 0xc0, 0xdf, 0x72, 0x64, 0x75,
	0xdc, 0xcc, 0x81, 0x14, 0x01, 0x35, 0x36, 0x62, 0x5b, 0xa3, 0xee, 0xf3, 0x6d, 0x57, 0x9a, 0x7e,
	0x0e, 0x69, 0x9f, 0xc6, 0x81, 0x82, 0x20, 0x51, 0x9a, 0x35, 0x01, 0x7f, 0xc7, 0x55, 0x1a, 0xcc,
	0xdc, 0x24, 0x77, 0x47, 0x34, 0xd6, 0xf8, 0xbb, 0x65, 0xe0, 0x0a, 0x7a, 0x6c, 0xcc, 0xdb, 0x22,
	0x89, 0xb2, 0x39, 0xca, 0x86, 0xa0, 0x03, 0xc5, 0x62, 0x23, 0x55, 0xee, 0xf6, 0xef, 0x39, 0xb2,
	0x80, 0x1e, 0x19, 0x73, 0x3b, 0x04, 0x2c, 0xa2, 0xdc, 0x52, 0xce, 0xa8, 0xc6, 0xdf, 0x77, 0xe3,
	0x69, 0xb7, 0x66, 0x13, 0xe1, 0xc3, 0xd8, 0x52, 0x11, 0xda, 0x3a, 0xa7, 0xc6, 0x80, 0xc8, 0xdc,
	0xae, 0xf1, 0x0f, 0x1c, 0xb9, 0x50, 0x4c, 0x37, 0x65, 0xab, 0xf9, 0x09, 0x08, 0x82, 0xc4, 0xb0,
	0x26, 0x58, 0x29, 0xf0, 0x0f, 0x1d, 0x79, 0x16, 0x5d, 0x9a, 0x04, 0x54, 0xd0, 0x80, 0xad, 0x78,
	0x14, 0xa3, 0x32, 0x1d, 0xef, 0x28, 0xd7, 0xf8, 0x47, 0xe5, 0x53, 0x3e, 0x56, 0x4c, 0x9b, 0xb9,
	0xd6, 0xe9, 0x4c, 0xeb, 0x2b, 0x5d, 0x36, 0x6b, 0x25, 0x81, 0x91, 0x4a, 0xe3, 0xb7, 0xdc, 0x78,
	0xa3, 0xca, 0xa1, 0x54, 0x31, 0xb3, 0x11, 0x81, 0x61, 0x81, 0xc6, 0x3f, 0x76, 0x87, 0xad, 0x46,
	0xc3, 0x90, 0x65, 0x92, 0x7d, 0x45, 0xf3, 0xb5, 0xb7, 0x98, 0x41, 0x7f, 0xe2, 0xc6, 0xeb, 0x5f,
	0xee, 0xbb, 0xac, 0x64, 0x29, 0xb9, 0xa9, 0xf1, 0xdb, 0x6e, 0xbc, 0x00, 0xad, 0x15, 0xa3, 0x48,
	0xa1, 0x6c, 0xa9, 0x4d, 0xff, 0x74, 0x42, 0xc4, 0x8d, 0x28, 0x46, 0x13, 0x6d, 0x36, 0x52, 0x28,
	0x8d, 0x7f, 0xe6, 0x0e, 0x1b, 0x81, 0x09, 0xce, 0x04, 0x58, 0x4e, 0xa3, 0xf5, 0x90, 0x8e, 0xc6,
	0x45, 0xfc, 0x8e, 0xf7, 0xe1, 0x89, 0x62, 0x20, 0x8a, 0x41, 0x31, 0xbf, 0x41, 0xb9, 0x6f, 0x28,
	0x09, 0x07, 0x8d, 0xdf, 0x7a, 0xf7, 0xb9, 0x92, 0x75, 0xff, 0xbf, 0x34, 0x97, 0x7b, 0x4f, 0xb3,
	0x10, 0x28, 0xe7, 0x2d, 0x0b, 0xc2, 0x47, 0x7c, 0x68, 0xd7, 0x93, 0x34, 0x59, 0x42, 0x68, 0x02,
	0x97, 0x71, 0x2a, 0xe3, 0xf3, 0xaf, 0x3f, 0x5f, 0x62, 0xb0, 0x5c, 0x98, 0xa7, 0xc2, 0xc0, 0x97,
	0x14, 0xcf, 0x01, 0x7f, 0xa1, 0x80, 0x4f, 0x4f, 0x91, 0xf5, 0xa2, 0x59, 0x4e, 0x84, 0xa7, 0xa1,
	0x36, 0x26, 0xf0, 0x8b, 0xaf, 0x3f, 0x3f, 0x8f, 0x52, 0x0e, 0x47, 0xa7, 0xa7, 0x70, 0xad, 0x7a,
	0x75, 0xce, 0x6f, 0xbf, 0x77, 0x7d, 0x75, 0x5e, 0x3c, 0x3a, 0x7d, 0x0e, 0x5f, 0x58, 0x3c, 0x3a,
	0xbd, 0x8c, 0x97, 0x97, 0x34, 0x22, 0x87, 0xdf, 0x0e, 0xfc, 0xb5, 0x50, 0xc1, 0xa6, 0x62, 0xc6,
	0x4f, 0x4e, 0xe9, 0x14, 0x68, 0x43, 0x99, 0x5e, 0xc7, 0x12, 0x0d, 0x78, 0x8a, 0x9c, 0x44, 0xb3,
	0xc3, 0xfd, 0x3c, 0x29, 0x70, 0x6d, 0x7e, 0xfa, 0xb5, 0x8f, 0xbd, 0xfd, 0x3a, 0x3a, 0x32, 0x5d,
	0x5b, 0x8a, 0x10, 0x11, 0xed, 0x3d, 0x97, 0x32, 0x1e, 0xf4, 0x77, 0xbb, 0xfb, 0x51, 0x77, 0xc7,
	0xf9, 0x11, 0xdf, 0x97, 0x0f, 0x7f, 0x1d, 0x91, 0x3c, 0x49, 0x3b, 0x6c, 0x5e, 0xdf, 0xf0, 0x14,
	0x99, 0x47, 0xc7, 0xc7, 0x37, 0x7d, 0x28, 0x06, 0x06, 0xd7, 0x96, 0x9e, 0x46, 0xf7, 0xc6, 0xbd,
	0xee, 0xce, 0xe0, 0x46, 0x3f, 0xe5, 0xf3, 0x00, 0xc2, 0xb1, 0x92, 0x61, 0x12, 0x98, 0x6c, 0xac,
	0x13, 0x94, 0xe3, 0xa9, 0xf2, 0xea, 0x70, 0xc8, 0xc4, 0xb5, 0xa5, 0x67, 0x11, 0xd6, 0xfd, 0x76,
	0xdf, 0xed, 0xb9, 0xfd, 0x7e, 0xd0, 0xdd, 0xef, 0xbb, 0xf7, 0xf7, 0xc9, 0x31, 0x34, 0x1b, 0x48,
	0x61, 0x60, 0xcb, 0x94, 0xe4, 0x13, 0x34, 0x33, 0x5c, 0xcc, 0xc2, 0x04, 0xd7, 0x96, 0x5e, 0x45,
	0x18, 0x7a, 0xbd, 0x6e, 0x2f, 0x72, 0x07, 0x07, 0xed, 0x5b, 0x2e, 0x15, 0x7e, 0x0a, 0xcd, 0x83,
	0x52, 0x52, 0xd9, 0x08, 0xb4, 0xa6, 0x8d, 0xd1, 0x08, 0xdb, 0xe2, 0x92, 0x86, 0xd9, 0x39, 0xaa,
	0xfb, 0xd2, 0xc7, 0x28, 0x13, 0x90, 0x96, 0xb5, 0xb3, 0xd5, 0xbd, 0x28, 0xe1, 0x86, 0xa5, 0xbb,
	0x19, 0x9b, 0x80, 0x2a, 0x30, 0xf8, 0xc8, 0x92, 0x42, 0xf7, 0xc5, 0xed, 0x5e, 0x7b, 0xcf, 0xf5,
	0x5d, 0x2f, 0x95, 0x7a, 0x0c, 0xcd, 0x8e, 0x6e, 0x4f, 0xd9, 0xfd, 0x08, 0x4f, 0xf9, 0xeb, 0x5b,
	0xb1, 0x18, 0x4b, 0x9d, 0xa7, 0x30, 0xae, 0xf9, 0xc3, 0x94, 0xe0, 0x52, 0x00, 0x3e, 0xf2, 0xcc,
	0x87, 0xd0, 0x5c, 0x27, 0x0f, 0x18, 0x7b, 0x33, 0x8f, 0x98, 0xfc, 0xa1, 0x8b, 0x9c, 0x59, 0xc9,
	0x9e, 0xb6, 0x56, 0x86, 0x4f, 0x5b, 0x2b, 0xb0, 0x3f, 0xd8, 0x6b, 0xb6, 0x3b, 0x83, 0xe1, 0x33,
	0xd2, 0xdc, 0xa7, 0x3e, 0xf7, 0xc9, 0x6b, 0x0b, 0xb5, 0x8b, 0xf7, 0x5e, 0x3d, 0xbd, 0x92, 0xbf,
	0x87, 0xad, 0x4c, 0x7e, 0xea, 0x52, 0xc7, 0x3b, 0x13, 0xd7, 0x9f, 0xe9, 0xa1, 0xd9, 0x5e, 0x16,
	0x5e, 0xff, 0x89, 0xdc, 0x3f, 0xbd, 0xf9, 0xc6, 0xa7, 0x6b, 0xa9, 0xe0, 0xc5, 0x91, 0xe0, 0x3b,
	0x3e, 0x76, 0xa9, 0x99, 0x5e, 0xe5, 0xf7, 0x7a, 0x03, 0x91, 0x1b, 0xdd, 0xbd, 0xa1, 0x94, 0x9c,
	0x7e, 0x7d, 0xe6, 0x25, 0xd7, 0x6f, 0xeb, 0x6b, 0x3c, 0x47, 0xbd, 0x74, 0xe6, 0xd6, 0x6e, 0xff,
	0xe5, 0xc1, 0xf5, 0x95, 0x1b, 0xdd, 0xbd, 0xd5, 0xf6, 0xed, 0x83, 0xfe, 0xfe, 0xce, 0xf5, 0xd5,
	0xea, 0x93, 0xe0, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x91, 0x3c, 0xde, 0x0c, 0x23, 0x14, 0x00,
	0x00,
}
