// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/proto/function.proto

package proto

import (
	fmt "fmt"
	deprecation_warningpb "github.com/apstndb/go-zetasql-genproto/zetasql/public/deprecation_warningpb"
	functionpb "github.com/apstndb/go-zetasql-genproto/zetasql/public/functionpb"
	optionspb "github.com/apstndb/go-zetasql-genproto/zetasql/public/optionspb"
	parse_location_rangepb "github.com/apstndb/go-zetasql-genproto/zetasql/public/parse_location_rangepb"
	parse_resume_locationpb "github.com/apstndb/go-zetasql-genproto/zetasql/public/parse_resume_locationpb"
	typepb "github.com/apstndb/go-zetasql-genproto/zetasql/public/typepb"
	valuepb "github.com/apstndb/go-zetasql-genproto/zetasql/public/valuepb"
	serializationpb "github.com/apstndb/go-zetasql-genproto/zetasql/resolved_ast/serializationpb"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TVFRelationColumnProto struct {
	Name                   *string                                         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Type                   *typepb.TypeProto                               `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	IsPseudoColumn         *bool                                           `protobuf:"varint,3,opt,name=is_pseudo_column,json=isPseudoColumn" json:"is_pseudo_column,omitempty"`
	NameParseLocationRange *parse_location_rangepb.ParseLocationRangeProto `protobuf:"bytes,4,opt,name=name_parse_location_range,json=nameParseLocationRange" json:"name_parse_location_range,omitempty"`
	TypeParseLocationRange *parse_location_rangepb.ParseLocationRangeProto `protobuf:"bytes,5,opt,name=type_parse_location_range,json=typeParseLocationRange" json:"type_parse_location_range,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                                        `json:"-"`
	XXX_unrecognized       []byte                                          `json:"-"`
	XXX_sizecache          int32                                           `json:"-"`
}

func (m *TVFRelationColumnProto) Reset()         { *m = TVFRelationColumnProto{} }
func (m *TVFRelationColumnProto) String() string { return proto.CompactTextString(m) }
func (*TVFRelationColumnProto) ProtoMessage()    {}
func (*TVFRelationColumnProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{0}
}

func (m *TVFRelationColumnProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TVFRelationColumnProto.Unmarshal(m, b)
}
func (m *TVFRelationColumnProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TVFRelationColumnProto.Marshal(b, m, deterministic)
}
func (m *TVFRelationColumnProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TVFRelationColumnProto.Merge(m, src)
}
func (m *TVFRelationColumnProto) XXX_Size() int {
	return xxx_messageInfo_TVFRelationColumnProto.Size(m)
}
func (m *TVFRelationColumnProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TVFRelationColumnProto.DiscardUnknown(m)
}

var xxx_messageInfo_TVFRelationColumnProto proto.InternalMessageInfo

func (m *TVFRelationColumnProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TVFRelationColumnProto) GetType() *typepb.TypeProto {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *TVFRelationColumnProto) GetIsPseudoColumn() bool {
	if m != nil && m.IsPseudoColumn != nil {
		return *m.IsPseudoColumn
	}
	return false
}

func (m *TVFRelationColumnProto) GetNameParseLocationRange() *parse_location_rangepb.ParseLocationRangeProto {
	if m != nil {
		return m.NameParseLocationRange
	}
	return nil
}

func (m *TVFRelationColumnProto) GetTypeParseLocationRange() *parse_location_rangepb.ParseLocationRangeProto {
	if m != nil {
		return m.TypeParseLocationRange
	}
	return nil
}

type TVFRelationProto struct {
	Column               []*TVFRelationColumnProto `protobuf:"bytes,1,rep,name=column" json:"column,omitempty"`
	IsValueTable         *bool                     `protobuf:"varint,2,opt,name=is_value_table,json=isValueTable,def=0" json:"is_value_table,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TVFRelationProto) Reset()         { *m = TVFRelationProto{} }
func (m *TVFRelationProto) String() string { return proto.CompactTextString(m) }
func (*TVFRelationProto) ProtoMessage()    {}
func (*TVFRelationProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{1}
}

func (m *TVFRelationProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TVFRelationProto.Unmarshal(m, b)
}
func (m *TVFRelationProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TVFRelationProto.Marshal(b, m, deterministic)
}
func (m *TVFRelationProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TVFRelationProto.Merge(m, src)
}
func (m *TVFRelationProto) XXX_Size() int {
	return xxx_messageInfo_TVFRelationProto.Size(m)
}
func (m *TVFRelationProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TVFRelationProto.DiscardUnknown(m)
}

var xxx_messageInfo_TVFRelationProto proto.InternalMessageInfo

const Default_TVFRelationProto_IsValueTable bool = false

func (m *TVFRelationProto) GetColumn() []*TVFRelationColumnProto {
	if m != nil {
		return m.Column
	}
	return nil
}

func (m *TVFRelationProto) GetIsValueTable() bool {
	if m != nil && m.IsValueTable != nil {
		return *m.IsValueTable
	}
	return Default_TVFRelationProto_IsValueTable
}

type TVFModelProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FullName             *string  `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TVFModelProto) Reset()         { *m = TVFModelProto{} }
func (m *TVFModelProto) String() string { return proto.CompactTextString(m) }
func (*TVFModelProto) ProtoMessage()    {}
func (*TVFModelProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{2}
}

func (m *TVFModelProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TVFModelProto.Unmarshal(m, b)
}
func (m *TVFModelProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TVFModelProto.Marshal(b, m, deterministic)
}
func (m *TVFModelProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TVFModelProto.Merge(m, src)
}
func (m *TVFModelProto) XXX_Size() int {
	return xxx_messageInfo_TVFModelProto.Size(m)
}
func (m *TVFModelProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TVFModelProto.DiscardUnknown(m)
}

var xxx_messageInfo_TVFModelProto proto.InternalMessageInfo

func (m *TVFModelProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TVFModelProto) GetFullName() string {
	if m != nil && m.FullName != nil {
		return *m.FullName
	}
	return ""
}

type TVFConnectionProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FullName             *string  `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TVFConnectionProto) Reset()         { *m = TVFConnectionProto{} }
func (m *TVFConnectionProto) String() string { return proto.CompactTextString(m) }
func (*TVFConnectionProto) ProtoMessage()    {}
func (*TVFConnectionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{3}
}

func (m *TVFConnectionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TVFConnectionProto.Unmarshal(m, b)
}
func (m *TVFConnectionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TVFConnectionProto.Marshal(b, m, deterministic)
}
func (m *TVFConnectionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TVFConnectionProto.Merge(m, src)
}
func (m *TVFConnectionProto) XXX_Size() int {
	return xxx_messageInfo_TVFConnectionProto.Size(m)
}
func (m *TVFConnectionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TVFConnectionProto.DiscardUnknown(m)
}

var xxx_messageInfo_TVFConnectionProto proto.InternalMessageInfo

func (m *TVFConnectionProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TVFConnectionProto) GetFullName() string {
	if m != nil && m.FullName != nil {
		return *m.FullName
	}
	return ""
}

type TVFDescriptorProto struct {
	ColumnName           []string `protobuf:"bytes,1,rep,name=column_name,json=columnName" json:"column_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TVFDescriptorProto) Reset()         { *m = TVFDescriptorProto{} }
func (m *TVFDescriptorProto) String() string { return proto.CompactTextString(m) }
func (*TVFDescriptorProto) ProtoMessage()    {}
func (*TVFDescriptorProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{4}
}

func (m *TVFDescriptorProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TVFDescriptorProto.Unmarshal(m, b)
}
func (m *TVFDescriptorProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TVFDescriptorProto.Marshal(b, m, deterministic)
}
func (m *TVFDescriptorProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TVFDescriptorProto.Merge(m, src)
}
func (m *TVFDescriptorProto) XXX_Size() int {
	return xxx_messageInfo_TVFDescriptorProto.Size(m)
}
func (m *TVFDescriptorProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TVFDescriptorProto.DiscardUnknown(m)
}

var xxx_messageInfo_TVFDescriptorProto proto.InternalMessageInfo

func (m *TVFDescriptorProto) GetColumnName() []string {
	if m != nil {
		return m.ColumnName
	}
	return nil
}

type FunctionArgumentTypeOptionsProto struct {
	Cardinality                      *functionpb.FunctionEnums_ArgumentCardinality   `protobuf:"varint,1,opt,name=cardinality,enum=zetasql.FunctionEnums_ArgumentCardinality" json:"cardinality,omitempty"`
	MustBeConstant                   *bool                                           `protobuf:"varint,2,opt,name=must_be_constant,json=mustBeConstant" json:"must_be_constant,omitempty"`
	MustBeNonNull                    *bool                                           `protobuf:"varint,3,opt,name=must_be_non_null,json=mustBeNonNull" json:"must_be_non_null,omitempty"`
	IsNotAggregate                   *bool                                           `protobuf:"varint,4,opt,name=is_not_aggregate,json=isNotAggregate" json:"is_not_aggregate,omitempty"`
	MustSupportEquality              *bool                                           `protobuf:"varint,5,opt,name=must_support_equality,json=mustSupportEquality" json:"must_support_equality,omitempty"`
	MustSupportOrdering              *bool                                           `protobuf:"varint,6,opt,name=must_support_ordering,json=mustSupportOrdering" json:"must_support_ordering,omitempty"`
	MinValue                         *int64                                          `protobuf:"varint,7,opt,name=min_value,json=minValue" json:"min_value,omitempty"`
	MaxValue                         *int64                                          `protobuf:"varint,8,opt,name=max_value,json=maxValue" json:"max_value,omitempty"`
	ExtraRelationInputColumnsAllowed *bool                                           `protobuf:"varint,9,opt,name=extra_relation_input_columns_allowed,json=extraRelationInputColumnsAllowed" json:"extra_relation_input_columns_allowed,omitempty"`
	RelationInputSchema              *TVFRelationProto                               `protobuf:"bytes,10,opt,name=relation_input_schema,json=relationInputSchema" json:"relation_input_schema,omitempty"`
	ArgumentName                     *string                                         `protobuf:"bytes,11,opt,name=argument_name,json=argumentName" json:"argument_name,omitempty"`
	ArgumentNameParseLocation        *parse_location_rangepb.ParseLocationRangeProto `protobuf:"bytes,12,opt,name=argument_name_parse_location,json=argumentNameParseLocation" json:"argument_name_parse_location,omitempty"`
	ArgumentTypeParseLocation        *parse_location_rangepb.ParseLocationRangeProto `protobuf:"bytes,13,opt,name=argument_type_parse_location,json=argumentTypeParseLocation" json:"argument_type_parse_location,omitempty"`
	ProcedureArgumentMode            *functionpb.FunctionEnums_ProcedureArgumentMode `protobuf:"varint,14,opt,name=procedure_argument_mode,json=procedureArgumentMode,enum=zetasql.FunctionEnums_ProcedureArgumentMode" json:"procedure_argument_mode,omitempty"`
	ArgumentNameIsMandatory          *bool                                           `protobuf:"varint,15,opt,name=argument_name_is_mandatory,json=argumentNameIsMandatory,def=0" json:"argument_name_is_mandatory,omitempty"`
	DescriptorResolutionTableOffset  *int32                                          `protobuf:"varint,16,opt,name=descriptor_resolution_table_offset,json=descriptorResolutionTableOffset,def=-1" json:"descriptor_resolution_table_offset,omitempty"`
	DefaultValue                     *valuepb.ValueProto                             `protobuf:"bytes,17,opt,name=default_value,json=defaultValue" json:"default_value,omitempty"`
	DefaultValueType                 *typepb.TypeProto                               `protobuf:"bytes,18,opt,name=default_value_type,json=defaultValueType" json:"default_value_type,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                                        `json:"-"`
	XXX_unrecognized                 []byte                                          `json:"-"`
	XXX_sizecache                    int32                                           `json:"-"`
}

func (m *FunctionArgumentTypeOptionsProto) Reset()         { *m = FunctionArgumentTypeOptionsProto{} }
func (m *FunctionArgumentTypeOptionsProto) String() string { return proto.CompactTextString(m) }
func (*FunctionArgumentTypeOptionsProto) ProtoMessage()    {}
func (*FunctionArgumentTypeOptionsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{5}
}

func (m *FunctionArgumentTypeOptionsProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionArgumentTypeOptionsProto.Unmarshal(m, b)
}
func (m *FunctionArgumentTypeOptionsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionArgumentTypeOptionsProto.Marshal(b, m, deterministic)
}
func (m *FunctionArgumentTypeOptionsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionArgumentTypeOptionsProto.Merge(m, src)
}
func (m *FunctionArgumentTypeOptionsProto) XXX_Size() int {
	return xxx_messageInfo_FunctionArgumentTypeOptionsProto.Size(m)
}
func (m *FunctionArgumentTypeOptionsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionArgumentTypeOptionsProto.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionArgumentTypeOptionsProto proto.InternalMessageInfo

const Default_FunctionArgumentTypeOptionsProto_ArgumentNameIsMandatory bool = false
const Default_FunctionArgumentTypeOptionsProto_DescriptorResolutionTableOffset int32 = -1

func (m *FunctionArgumentTypeOptionsProto) GetCardinality() functionpb.FunctionEnums_ArgumentCardinality {
	if m != nil && m.Cardinality != nil {
		return *m.Cardinality
	}
	return functionpb.FunctionEnums_REQUIRED
}

func (m *FunctionArgumentTypeOptionsProto) GetMustBeConstant() bool {
	if m != nil && m.MustBeConstant != nil {
		return *m.MustBeConstant
	}
	return false
}

func (m *FunctionArgumentTypeOptionsProto) GetMustBeNonNull() bool {
	if m != nil && m.MustBeNonNull != nil {
		return *m.MustBeNonNull
	}
	return false
}

func (m *FunctionArgumentTypeOptionsProto) GetIsNotAggregate() bool {
	if m != nil && m.IsNotAggregate != nil {
		return *m.IsNotAggregate
	}
	return false
}

func (m *FunctionArgumentTypeOptionsProto) GetMustSupportEquality() bool {
	if m != nil && m.MustSupportEquality != nil {
		return *m.MustSupportEquality
	}
	return false
}

func (m *FunctionArgumentTypeOptionsProto) GetMustSupportOrdering() bool {
	if m != nil && m.MustSupportOrdering != nil {
		return *m.MustSupportOrdering
	}
	return false
}

func (m *FunctionArgumentTypeOptionsProto) GetMinValue() int64 {
	if m != nil && m.MinValue != nil {
		return *m.MinValue
	}
	return 0
}

func (m *FunctionArgumentTypeOptionsProto) GetMaxValue() int64 {
	if m != nil && m.MaxValue != nil {
		return *m.MaxValue
	}
	return 0
}

func (m *FunctionArgumentTypeOptionsProto) GetExtraRelationInputColumnsAllowed() bool {
	if m != nil && m.ExtraRelationInputColumnsAllowed != nil {
		return *m.ExtraRelationInputColumnsAllowed
	}
	return false
}

func (m *FunctionArgumentTypeOptionsProto) GetRelationInputSchema() *TVFRelationProto {
	if m != nil {
		return m.RelationInputSchema
	}
	return nil
}

func (m *FunctionArgumentTypeOptionsProto) GetArgumentName() string {
	if m != nil && m.ArgumentName != nil {
		return *m.ArgumentName
	}
	return ""
}

func (m *FunctionArgumentTypeOptionsProto) GetArgumentNameParseLocation() *parse_location_rangepb.ParseLocationRangeProto {
	if m != nil {
		return m.ArgumentNameParseLocation
	}
	return nil
}

func (m *FunctionArgumentTypeOptionsProto) GetArgumentTypeParseLocation() *parse_location_rangepb.ParseLocationRangeProto {
	if m != nil {
		return m.ArgumentTypeParseLocation
	}
	return nil
}

func (m *FunctionArgumentTypeOptionsProto) GetProcedureArgumentMode() functionpb.FunctionEnums_ProcedureArgumentMode {
	if m != nil && m.ProcedureArgumentMode != nil {
		return *m.ProcedureArgumentMode
	}
	return functionpb.FunctionEnums_NOT_SET
}

func (m *FunctionArgumentTypeOptionsProto) GetArgumentNameIsMandatory() bool {
	if m != nil && m.ArgumentNameIsMandatory != nil {
		return *m.ArgumentNameIsMandatory
	}
	return Default_FunctionArgumentTypeOptionsProto_ArgumentNameIsMandatory
}

func (m *FunctionArgumentTypeOptionsProto) GetDescriptorResolutionTableOffset() int32 {
	if m != nil && m.DescriptorResolutionTableOffset != nil {
		return *m.DescriptorResolutionTableOffset
	}
	return Default_FunctionArgumentTypeOptionsProto_DescriptorResolutionTableOffset
}

func (m *FunctionArgumentTypeOptionsProto) GetDefaultValue() *valuepb.ValueProto {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *FunctionArgumentTypeOptionsProto) GetDefaultValueType() *typepb.TypeProto {
	if m != nil {
		return m.DefaultValueType
	}
	return nil
}

type ArgumentTypeLambdaProto struct {
	Argument             []*FunctionArgumentTypeProto `protobuf:"bytes,5,rep,name=argument" json:"argument,omitempty"`
	Body                 *FunctionArgumentTypeProto   `protobuf:"bytes,6,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ArgumentTypeLambdaProto) Reset()         { *m = ArgumentTypeLambdaProto{} }
func (m *ArgumentTypeLambdaProto) String() string { return proto.CompactTextString(m) }
func (*ArgumentTypeLambdaProto) ProtoMessage()    {}
func (*ArgumentTypeLambdaProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{6}
}

func (m *ArgumentTypeLambdaProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArgumentTypeLambdaProto.Unmarshal(m, b)
}
func (m *ArgumentTypeLambdaProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArgumentTypeLambdaProto.Marshal(b, m, deterministic)
}
func (m *ArgumentTypeLambdaProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArgumentTypeLambdaProto.Merge(m, src)
}
func (m *ArgumentTypeLambdaProto) XXX_Size() int {
	return xxx_messageInfo_ArgumentTypeLambdaProto.Size(m)
}
func (m *ArgumentTypeLambdaProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ArgumentTypeLambdaProto.DiscardUnknown(m)
}

var xxx_messageInfo_ArgumentTypeLambdaProto proto.InternalMessageInfo

func (m *ArgumentTypeLambdaProto) GetArgument() []*FunctionArgumentTypeProto {
	if m != nil {
		return m.Argument
	}
	return nil
}

func (m *ArgumentTypeLambdaProto) GetBody() *FunctionArgumentTypeProto {
	if m != nil {
		return m.Body
	}
	return nil
}

type FunctionArgumentTypeProto struct {
	Kind                 *functionpb.SignatureArgumentKind `protobuf:"varint,1,opt,name=kind,enum=zetasql.SignatureArgumentKind" json:"kind,omitempty"`
	Type                 *typepb.TypeProto                 `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	NumOccurrences       *int32                            `protobuf:"varint,4,opt,name=num_occurrences,json=numOccurrences" json:"num_occurrences,omitempty"`
	Options              *FunctionArgumentTypeOptionsProto `protobuf:"bytes,3,opt,name=options" json:"options,omitempty"`
	Lambda               *ArgumentTypeLambdaProto          `protobuf:"bytes,5,opt,name=lambda" json:"lambda,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *FunctionArgumentTypeProto) Reset()         { *m = FunctionArgumentTypeProto{} }
func (m *FunctionArgumentTypeProto) String() string { return proto.CompactTextString(m) }
func (*FunctionArgumentTypeProto) ProtoMessage()    {}
func (*FunctionArgumentTypeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{7}
}

func (m *FunctionArgumentTypeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionArgumentTypeProto.Unmarshal(m, b)
}
func (m *FunctionArgumentTypeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionArgumentTypeProto.Marshal(b, m, deterministic)
}
func (m *FunctionArgumentTypeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionArgumentTypeProto.Merge(m, src)
}
func (m *FunctionArgumentTypeProto) XXX_Size() int {
	return xxx_messageInfo_FunctionArgumentTypeProto.Size(m)
}
func (m *FunctionArgumentTypeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionArgumentTypeProto.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionArgumentTypeProto proto.InternalMessageInfo

func (m *FunctionArgumentTypeProto) GetKind() functionpb.SignatureArgumentKind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return functionpb.SignatureArgumentKind_ARG_TYPE_FIXED
}

func (m *FunctionArgumentTypeProto) GetType() *typepb.TypeProto {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *FunctionArgumentTypeProto) GetNumOccurrences() int32 {
	if m != nil && m.NumOccurrences != nil {
		return *m.NumOccurrences
	}
	return 0
}

func (m *FunctionArgumentTypeProto) GetOptions() *FunctionArgumentTypeOptionsProto {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *FunctionArgumentTypeProto) GetLambda() *ArgumentTypeLambdaProto {
	if m != nil {
		return m.Lambda
	}
	return nil
}

type FunctionSignatureOptionsProto struct {
	IsDeprecated                 *bool                                                   `protobuf:"varint,2,opt,name=is_deprecated,json=isDeprecated,def=0" json:"is_deprecated,omitempty"`
	AdditionalDeprecationWarning []*deprecation_warningpb.FreestandingDeprecationWarning `protobuf:"bytes,3,rep,name=additional_deprecation_warning,json=additionalDeprecationWarning" json:"additional_deprecation_warning,omitempty"`
	RequiredLanguageFeature      []optionspb.LanguageFeature                             `protobuf:"varint,4,rep,name=required_language_feature,json=requiredLanguageFeature,enum=zetasql.LanguageFeature" json:"required_language_feature,omitempty"`
	IsAliasedSignature           *bool                                                   `protobuf:"varint,5,opt,name=is_aliased_signature,json=isAliasedSignature,def=0" json:"is_aliased_signature,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                                                `json:"-"`
	XXX_unrecognized             []byte                                                  `json:"-"`
	XXX_sizecache                int32                                                   `json:"-"`
}

func (m *FunctionSignatureOptionsProto) Reset()         { *m = FunctionSignatureOptionsProto{} }
func (m *FunctionSignatureOptionsProto) String() string { return proto.CompactTextString(m) }
func (*FunctionSignatureOptionsProto) ProtoMessage()    {}
func (*FunctionSignatureOptionsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{8}
}

func (m *FunctionSignatureOptionsProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionSignatureOptionsProto.Unmarshal(m, b)
}
func (m *FunctionSignatureOptionsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionSignatureOptionsProto.Marshal(b, m, deterministic)
}
func (m *FunctionSignatureOptionsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionSignatureOptionsProto.Merge(m, src)
}
func (m *FunctionSignatureOptionsProto) XXX_Size() int {
	return xxx_messageInfo_FunctionSignatureOptionsProto.Size(m)
}
func (m *FunctionSignatureOptionsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionSignatureOptionsProto.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionSignatureOptionsProto proto.InternalMessageInfo

const Default_FunctionSignatureOptionsProto_IsDeprecated bool = false
const Default_FunctionSignatureOptionsProto_IsAliasedSignature bool = false

func (m *FunctionSignatureOptionsProto) GetIsDeprecated() bool {
	if m != nil && m.IsDeprecated != nil {
		return *m.IsDeprecated
	}
	return Default_FunctionSignatureOptionsProto_IsDeprecated
}

func (m *FunctionSignatureOptionsProto) GetAdditionalDeprecationWarning() []*deprecation_warningpb.FreestandingDeprecationWarning {
	if m != nil {
		return m.AdditionalDeprecationWarning
	}
	return nil
}

func (m *FunctionSignatureOptionsProto) GetRequiredLanguageFeature() []optionspb.LanguageFeature {
	if m != nil {
		return m.RequiredLanguageFeature
	}
	return nil
}

func (m *FunctionSignatureOptionsProto) GetIsAliasedSignature() bool {
	if m != nil && m.IsAliasedSignature != nil {
		return *m.IsAliasedSignature
	}
	return Default_FunctionSignatureOptionsProto_IsAliasedSignature
}

type FunctionSignatureProto struct {
	Argument             []*FunctionArgumentTypeProto   `protobuf:"bytes,1,rep,name=argument" json:"argument,omitempty"`
	ReturnType           *FunctionArgumentTypeProto     `protobuf:"bytes,2,opt,name=return_type,json=returnType" json:"return_type,omitempty"`
	ContextId            *int64                         `protobuf:"varint,3,opt,name=context_id,json=contextId" json:"context_id,omitempty"`
	Options              *FunctionSignatureOptionsProto `protobuf:"bytes,4,opt,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *FunctionSignatureProto) Reset()         { *m = FunctionSignatureProto{} }
func (m *FunctionSignatureProto) String() string { return proto.CompactTextString(m) }
func (*FunctionSignatureProto) ProtoMessage()    {}
func (*FunctionSignatureProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{9}
}

func (m *FunctionSignatureProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionSignatureProto.Unmarshal(m, b)
}
func (m *FunctionSignatureProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionSignatureProto.Marshal(b, m, deterministic)
}
func (m *FunctionSignatureProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionSignatureProto.Merge(m, src)
}
func (m *FunctionSignatureProto) XXX_Size() int {
	return xxx_messageInfo_FunctionSignatureProto.Size(m)
}
func (m *FunctionSignatureProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionSignatureProto.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionSignatureProto proto.InternalMessageInfo

func (m *FunctionSignatureProto) GetArgument() []*FunctionArgumentTypeProto {
	if m != nil {
		return m.Argument
	}
	return nil
}

func (m *FunctionSignatureProto) GetReturnType() *FunctionArgumentTypeProto {
	if m != nil {
		return m.ReturnType
	}
	return nil
}

func (m *FunctionSignatureProto) GetContextId() int64 {
	if m != nil && m.ContextId != nil {
		return *m.ContextId
	}
	return 0
}

func (m *FunctionSignatureProto) GetOptions() *FunctionSignatureOptionsProto {
	if m != nil {
		return m.Options
	}
	return nil
}

type FunctionOptionsProto struct {
	SupportsOverClause           *bool                                        `protobuf:"varint,1,opt,name=supports_over_clause,json=supportsOverClause,def=0" json:"supports_over_clause,omitempty"`
	WindowOrderingSupport        *functionpb.FunctionEnums_WindowOrderSupport `protobuf:"varint,2,opt,name=window_ordering_support,json=windowOrderingSupport,enum=zetasql.FunctionEnums_WindowOrderSupport,def=0" json:"window_ordering_support,omitempty"`
	SupportsWindowFraming        *bool                                        `protobuf:"varint,3,opt,name=supports_window_framing,json=supportsWindowFraming,def=0" json:"supports_window_framing,omitempty"`
	ArgumentsAreCoercible        *bool                                        `protobuf:"varint,4,opt,name=arguments_are_coercible,json=argumentsAreCoercible,def=1" json:"arguments_are_coercible,omitempty"`
	IsDeprecated                 *bool                                        `protobuf:"varint,5,opt,name=is_deprecated,json=isDeprecated,def=0" json:"is_deprecated,omitempty"`
	AliasName                    *string                                      `protobuf:"bytes,6,opt,name=alias_name,json=aliasName" json:"alias_name,omitempty"`
	SqlName                      *string                                      `protobuf:"bytes,7,opt,name=sql_name,json=sqlName" json:"sql_name,omitempty"`
	AllowExternalUsage           *bool                                        `protobuf:"varint,8,opt,name=allow_external_usage,json=allowExternalUsage,def=1" json:"allow_external_usage,omitempty"`
	Volatility                   *functionpb.FunctionEnums_Volatility         `protobuf:"varint,9,opt,name=volatility,enum=zetasql.FunctionEnums_Volatility,def=0" json:"volatility,omitempty"`
	SupportsOrderBy              *bool                                        `protobuf:"varint,10,opt,name=supports_order_by,json=supportsOrderBy,def=0" json:"supports_order_by,omitempty"`
	RequiredLanguageFeature      []optionspb.LanguageFeature                  `protobuf:"varint,11,rep,name=required_language_feature,json=requiredLanguageFeature,enum=zetasql.LanguageFeature" json:"required_language_feature,omitempty"`
	SupportsLimit                *bool                                        `protobuf:"varint,12,opt,name=supports_limit,json=supportsLimit,def=0" json:"supports_limit,omitempty"`
	SupportsNullHandlingModifier *bool                                        `protobuf:"varint,13,opt,name=supports_null_handling_modifier,json=supportsNullHandlingModifier,def=0" json:"supports_null_handling_modifier,omitempty"`
	SupportsSafeErrorMode        *bool                                        `protobuf:"varint,14,opt,name=supports_safe_error_mode,json=supportsSafeErrorMode,def=1" json:"supports_safe_error_mode,omitempty"`
	SupportsHavingModifier       *bool                                        `protobuf:"varint,15,opt,name=supports_having_modifier,json=supportsHavingModifier,def=1" json:"supports_having_modifier,omitempty"`
	UsesUpperCaseSqlName         *bool                                        `protobuf:"varint,17,opt,name=uses_upper_case_sql_name,json=usesUpperCaseSqlName,def=1" json:"uses_upper_case_sql_name,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                                     `json:"-"`
	XXX_unrecognized             []byte                                       `json:"-"`
	XXX_sizecache                int32                                        `json:"-"`
}

func (m *FunctionOptionsProto) Reset()         { *m = FunctionOptionsProto{} }
func (m *FunctionOptionsProto) String() string { return proto.CompactTextString(m) }
func (*FunctionOptionsProto) ProtoMessage()    {}
func (*FunctionOptionsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{10}
}

func (m *FunctionOptionsProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionOptionsProto.Unmarshal(m, b)
}
func (m *FunctionOptionsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionOptionsProto.Marshal(b, m, deterministic)
}
func (m *FunctionOptionsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionOptionsProto.Merge(m, src)
}
func (m *FunctionOptionsProto) XXX_Size() int {
	return xxx_messageInfo_FunctionOptionsProto.Size(m)
}
func (m *FunctionOptionsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionOptionsProto.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionOptionsProto proto.InternalMessageInfo

const Default_FunctionOptionsProto_SupportsOverClause bool = false
const Default_FunctionOptionsProto_WindowOrderingSupport functionpb.FunctionEnums_WindowOrderSupport = functionpb.FunctionEnums_ORDER_UNSUPPORTED
const Default_FunctionOptionsProto_SupportsWindowFraming bool = false
const Default_FunctionOptionsProto_ArgumentsAreCoercible bool = true
const Default_FunctionOptionsProto_IsDeprecated bool = false
const Default_FunctionOptionsProto_AllowExternalUsage bool = true
const Default_FunctionOptionsProto_Volatility functionpb.FunctionEnums_Volatility = functionpb.FunctionEnums_IMMUTABLE
const Default_FunctionOptionsProto_SupportsOrderBy bool = false
const Default_FunctionOptionsProto_SupportsLimit bool = false
const Default_FunctionOptionsProto_SupportsNullHandlingModifier bool = false
const Default_FunctionOptionsProto_SupportsSafeErrorMode bool = true
const Default_FunctionOptionsProto_SupportsHavingModifier bool = true
const Default_FunctionOptionsProto_UsesUpperCaseSqlName bool = true

func (m *FunctionOptionsProto) GetSupportsOverClause() bool {
	if m != nil && m.SupportsOverClause != nil {
		return *m.SupportsOverClause
	}
	return Default_FunctionOptionsProto_SupportsOverClause
}

func (m *FunctionOptionsProto) GetWindowOrderingSupport() functionpb.FunctionEnums_WindowOrderSupport {
	if m != nil && m.WindowOrderingSupport != nil {
		return *m.WindowOrderingSupport
	}
	return Default_FunctionOptionsProto_WindowOrderingSupport
}

func (m *FunctionOptionsProto) GetSupportsWindowFraming() bool {
	if m != nil && m.SupportsWindowFraming != nil {
		return *m.SupportsWindowFraming
	}
	return Default_FunctionOptionsProto_SupportsWindowFraming
}

func (m *FunctionOptionsProto) GetArgumentsAreCoercible() bool {
	if m != nil && m.ArgumentsAreCoercible != nil {
		return *m.ArgumentsAreCoercible
	}
	return Default_FunctionOptionsProto_ArgumentsAreCoercible
}

func (m *FunctionOptionsProto) GetIsDeprecated() bool {
	if m != nil && m.IsDeprecated != nil {
		return *m.IsDeprecated
	}
	return Default_FunctionOptionsProto_IsDeprecated
}

func (m *FunctionOptionsProto) GetAliasName() string {
	if m != nil && m.AliasName != nil {
		return *m.AliasName
	}
	return ""
}

func (m *FunctionOptionsProto) GetSqlName() string {
	if m != nil && m.SqlName != nil {
		return *m.SqlName
	}
	return ""
}

func (m *FunctionOptionsProto) GetAllowExternalUsage() bool {
	if m != nil && m.AllowExternalUsage != nil {
		return *m.AllowExternalUsage
	}
	return Default_FunctionOptionsProto_AllowExternalUsage
}

func (m *FunctionOptionsProto) GetVolatility() functionpb.FunctionEnums_Volatility {
	if m != nil && m.Volatility != nil {
		return *m.Volatility
	}
	return Default_FunctionOptionsProto_Volatility
}

func (m *FunctionOptionsProto) GetSupportsOrderBy() bool {
	if m != nil && m.SupportsOrderBy != nil {
		return *m.SupportsOrderBy
	}
	return Default_FunctionOptionsProto_SupportsOrderBy
}

func (m *FunctionOptionsProto) GetRequiredLanguageFeature() []optionspb.LanguageFeature {
	if m != nil {
		return m.RequiredLanguageFeature
	}
	return nil
}

func (m *FunctionOptionsProto) GetSupportsLimit() bool {
	if m != nil && m.SupportsLimit != nil {
		return *m.SupportsLimit
	}
	return Default_FunctionOptionsProto_SupportsLimit
}

func (m *FunctionOptionsProto) GetSupportsNullHandlingModifier() bool {
	if m != nil && m.SupportsNullHandlingModifier != nil {
		return *m.SupportsNullHandlingModifier
	}
	return Default_FunctionOptionsProto_SupportsNullHandlingModifier
}

func (m *FunctionOptionsProto) GetSupportsSafeErrorMode() bool {
	if m != nil && m.SupportsSafeErrorMode != nil {
		return *m.SupportsSafeErrorMode
	}
	return Default_FunctionOptionsProto_SupportsSafeErrorMode
}

func (m *FunctionOptionsProto) GetSupportsHavingModifier() bool {
	if m != nil && m.SupportsHavingModifier != nil {
		return *m.SupportsHavingModifier
	}
	return Default_FunctionOptionsProto_SupportsHavingModifier
}

func (m *FunctionOptionsProto) GetUsesUpperCaseSqlName() bool {
	if m != nil && m.UsesUpperCaseSqlName != nil {
		return *m.UsesUpperCaseSqlName
	}
	return Default_FunctionOptionsProto_UsesUpperCaseSqlName
}

type FunctionProto struct {
	NamePath                         []string                                          `protobuf:"bytes,1,rep,name=name_path,json=namePath" json:"name_path,omitempty"`
	Group                            *string                                           `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	Mode                             *functionpb.FunctionEnums_Mode                    `protobuf:"varint,3,opt,name=mode,enum=zetasql.FunctionEnums_Mode" json:"mode,omitempty"`
	Signature                        []*FunctionSignatureProto                         `protobuf:"bytes,4,rep,name=signature" json:"signature,omitempty"`
	Options                          *FunctionOptionsProto                             `protobuf:"bytes,5,opt,name=options" json:"options,omitempty"`
	ParseResumeLocation              *parse_resume_locationpb.ParseResumeLocationProto `protobuf:"bytes,8,opt,name=parse_resume_location,json=parseResumeLocation" json:"parse_resume_location,omitempty"`
	TemplatedSqlFunctionArgumentName []string                                          `protobuf:"bytes,7,rep,name=templated_sql_function_argument_name,json=templatedSqlFunctionArgumentName" json:"templated_sql_function_argument_name,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}                                          `json:"-"`
	XXX_unrecognized                 []byte                                            `json:"-"`
	XXX_sizecache                    int32                                             `json:"-"`
}

func (m *FunctionProto) Reset()         { *m = FunctionProto{} }
func (m *FunctionProto) String() string { return proto.CompactTextString(m) }
func (*FunctionProto) ProtoMessage()    {}
func (*FunctionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{11}
}

func (m *FunctionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionProto.Unmarshal(m, b)
}
func (m *FunctionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionProto.Marshal(b, m, deterministic)
}
func (m *FunctionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionProto.Merge(m, src)
}
func (m *FunctionProto) XXX_Size() int {
	return xxx_messageInfo_FunctionProto.Size(m)
}
func (m *FunctionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionProto.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionProto proto.InternalMessageInfo

func (m *FunctionProto) GetNamePath() []string {
	if m != nil {
		return m.NamePath
	}
	return nil
}

func (m *FunctionProto) GetGroup() string {
	if m != nil && m.Group != nil {
		return *m.Group
	}
	return ""
}

func (m *FunctionProto) GetMode() functionpb.FunctionEnums_Mode {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return functionpb.FunctionEnums_SCALAR
}

func (m *FunctionProto) GetSignature() []*FunctionSignatureProto {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *FunctionProto) GetOptions() *FunctionOptionsProto {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *FunctionProto) GetParseResumeLocation() *parse_resume_locationpb.ParseResumeLocationProto {
	if m != nil {
		return m.ParseResumeLocation
	}
	return nil
}

func (m *FunctionProto) GetTemplatedSqlFunctionArgumentName() []string {
	if m != nil {
		return m.TemplatedSqlFunctionArgumentName
	}
	return nil
}

type ResolvedFunctionCallInfoProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedFunctionCallInfoProto) Reset()         { *m = ResolvedFunctionCallInfoProto{} }
func (m *ResolvedFunctionCallInfoProto) String() string { return proto.CompactTextString(m) }
func (*ResolvedFunctionCallInfoProto) ProtoMessage()    {}
func (*ResolvedFunctionCallInfoProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{12}
}

func (m *ResolvedFunctionCallInfoProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedFunctionCallInfoProto.Unmarshal(m, b)
}
func (m *ResolvedFunctionCallInfoProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedFunctionCallInfoProto.Marshal(b, m, deterministic)
}
func (m *ResolvedFunctionCallInfoProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedFunctionCallInfoProto.Merge(m, src)
}
func (m *ResolvedFunctionCallInfoProto) XXX_Size() int {
	return xxx_messageInfo_ResolvedFunctionCallInfoProto.Size(m)
}
func (m *ResolvedFunctionCallInfoProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedFunctionCallInfoProto.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedFunctionCallInfoProto proto.InternalMessageInfo

type TableValuedFunctionProto struct {
	NamePath             []string                                          `protobuf:"bytes,1,rep,name=name_path,json=namePath" json:"name_path,omitempty"`
	Signature            *FunctionSignatureProto                           `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	Type                 *functionpb.FunctionEnums_TableValuedFunctionType `protobuf:"varint,3,opt,name=type,enum=zetasql.FunctionEnums_TableValuedFunctionType" json:"type,omitempty"`
	Volatility           *functionpb.FunctionEnums_Volatility              `protobuf:"varint,8,opt,name=volatility,enum=zetasql.FunctionEnums_Volatility" json:"volatility,omitempty"`
	ParseResumeLocation  *parse_resume_locationpb.ParseResumeLocationProto `protobuf:"bytes,6,opt,name=parse_resume_location,json=parseResumeLocation" json:"parse_resume_location,omitempty"`
	ArgumentName         []string                                          `protobuf:"bytes,5,rep,name=argument_name,json=argumentName" json:"argument_name,omitempty"`
	CustomContext        *string                                           `protobuf:"bytes,7,opt,name=custom_context,json=customContext" json:"custom_context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                          `json:"-"`
	XXX_unrecognized     []byte                                            `json:"-"`
	XXX_sizecache        int32                                             `json:"-"`
}

func (m *TableValuedFunctionProto) Reset()         { *m = TableValuedFunctionProto{} }
func (m *TableValuedFunctionProto) String() string { return proto.CompactTextString(m) }
func (*TableValuedFunctionProto) ProtoMessage()    {}
func (*TableValuedFunctionProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{13}
}

func (m *TableValuedFunctionProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TableValuedFunctionProto.Unmarshal(m, b)
}
func (m *TableValuedFunctionProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TableValuedFunctionProto.Marshal(b, m, deterministic)
}
func (m *TableValuedFunctionProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableValuedFunctionProto.Merge(m, src)
}
func (m *TableValuedFunctionProto) XXX_Size() int {
	return xxx_messageInfo_TableValuedFunctionProto.Size(m)
}
func (m *TableValuedFunctionProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TableValuedFunctionProto.DiscardUnknown(m)
}

var xxx_messageInfo_TableValuedFunctionProto proto.InternalMessageInfo

func (m *TableValuedFunctionProto) GetNamePath() []string {
	if m != nil {
		return m.NamePath
	}
	return nil
}

func (m *TableValuedFunctionProto) GetSignature() *FunctionSignatureProto {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TableValuedFunctionProto) GetType() functionpb.FunctionEnums_TableValuedFunctionType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return functionpb.FunctionEnums_INVALID
}

func (m *TableValuedFunctionProto) GetVolatility() functionpb.FunctionEnums_Volatility {
	if m != nil && m.Volatility != nil {
		return *m.Volatility
	}
	return functionpb.FunctionEnums_IMMUTABLE
}

func (m *TableValuedFunctionProto) GetParseResumeLocation() *parse_resume_locationpb.ParseResumeLocationProto {
	if m != nil {
		return m.ParseResumeLocation
	}
	return nil
}

func (m *TableValuedFunctionProto) GetArgumentName() []string {
	if m != nil {
		return m.ArgumentName
	}
	return nil
}

func (m *TableValuedFunctionProto) GetCustomContext() string {
	if m != nil && m.CustomContext != nil {
		return *m.CustomContext
	}
	return ""
}

type TVFArgumentProto struct {
	ScalarArgument       *serializationpb.ValueWithTypeProto `protobuf:"bytes,1,opt,name=scalar_argument,json=scalarArgument" json:"scalar_argument,omitempty"`
	RelationArgument     *TVFRelationProto                   `protobuf:"bytes,2,opt,name=relation_argument,json=relationArgument" json:"relation_argument,omitempty"`
	ModelArgument        *TVFModelProto                      `protobuf:"bytes,3,opt,name=model_argument,json=modelArgument" json:"model_argument,omitempty"`
	ConnectionArgument   *TVFConnectionProto                 `protobuf:"bytes,4,opt,name=connection_argument,json=connectionArgument" json:"connection_argument,omitempty"`
	DescriptorArgument   *TVFDescriptorProto                 `protobuf:"bytes,5,opt,name=descriptor_argument,json=descriptorArgument" json:"descriptor_argument,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *TVFArgumentProto) Reset()         { *m = TVFArgumentProto{} }
func (m *TVFArgumentProto) String() string { return proto.CompactTextString(m) }
func (*TVFArgumentProto) ProtoMessage()    {}
func (*TVFArgumentProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{14}
}

func (m *TVFArgumentProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TVFArgumentProto.Unmarshal(m, b)
}
func (m *TVFArgumentProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TVFArgumentProto.Marshal(b, m, deterministic)
}
func (m *TVFArgumentProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TVFArgumentProto.Merge(m, src)
}
func (m *TVFArgumentProto) XXX_Size() int {
	return xxx_messageInfo_TVFArgumentProto.Size(m)
}
func (m *TVFArgumentProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TVFArgumentProto.DiscardUnknown(m)
}

var xxx_messageInfo_TVFArgumentProto proto.InternalMessageInfo

func (m *TVFArgumentProto) GetScalarArgument() *serializationpb.ValueWithTypeProto {
	if m != nil {
		return m.ScalarArgument
	}
	return nil
}

func (m *TVFArgumentProto) GetRelationArgument() *TVFRelationProto {
	if m != nil {
		return m.RelationArgument
	}
	return nil
}

func (m *TVFArgumentProto) GetModelArgument() *TVFModelProto {
	if m != nil {
		return m.ModelArgument
	}
	return nil
}

func (m *TVFArgumentProto) GetConnectionArgument() *TVFConnectionProto {
	if m != nil {
		return m.ConnectionArgument
	}
	return nil
}

func (m *TVFArgumentProto) GetDescriptorArgument() *TVFDescriptorProto {
	if m != nil {
		return m.DescriptorArgument
	}
	return nil
}

type TVFSignatureOptionsProto struct {
	AdditionalDeprecationWarning []*deprecation_warningpb.FreestandingDeprecationWarning `protobuf:"bytes,1,rep,name=additional_deprecation_warning,json=additionalDeprecationWarning" json:"additional_deprecation_warning,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                                                `json:"-"`
	XXX_unrecognized             []byte                                                  `json:"-"`
	XXX_sizecache                int32                                                   `json:"-"`
}

func (m *TVFSignatureOptionsProto) Reset()         { *m = TVFSignatureOptionsProto{} }
func (m *TVFSignatureOptionsProto) String() string { return proto.CompactTextString(m) }
func (*TVFSignatureOptionsProto) ProtoMessage()    {}
func (*TVFSignatureOptionsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{15}
}

func (m *TVFSignatureOptionsProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TVFSignatureOptionsProto.Unmarshal(m, b)
}
func (m *TVFSignatureOptionsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TVFSignatureOptionsProto.Marshal(b, m, deterministic)
}
func (m *TVFSignatureOptionsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TVFSignatureOptionsProto.Merge(m, src)
}
func (m *TVFSignatureOptionsProto) XXX_Size() int {
	return xxx_messageInfo_TVFSignatureOptionsProto.Size(m)
}
func (m *TVFSignatureOptionsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TVFSignatureOptionsProto.DiscardUnknown(m)
}

var xxx_messageInfo_TVFSignatureOptionsProto proto.InternalMessageInfo

func (m *TVFSignatureOptionsProto) GetAdditionalDeprecationWarning() []*deprecation_warningpb.FreestandingDeprecationWarning {
	if m != nil {
		return m.AdditionalDeprecationWarning
	}
	return nil
}

type TVFSignatureProto struct {
	Argument             []*TVFArgumentProto       `protobuf:"bytes,1,rep,name=argument" json:"argument,omitempty"`
	OutputSchema         *TVFRelationProto         `protobuf:"bytes,2,opt,name=output_schema,json=outputSchema" json:"output_schema,omitempty"`
	Options              *TVFSignatureOptionsProto `protobuf:"bytes,3,opt,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *TVFSignatureProto) Reset()         { *m = TVFSignatureProto{} }
func (m *TVFSignatureProto) String() string { return proto.CompactTextString(m) }
func (*TVFSignatureProto) ProtoMessage()    {}
func (*TVFSignatureProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{16}
}

func (m *TVFSignatureProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TVFSignatureProto.Unmarshal(m, b)
}
func (m *TVFSignatureProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TVFSignatureProto.Marshal(b, m, deterministic)
}
func (m *TVFSignatureProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TVFSignatureProto.Merge(m, src)
}
func (m *TVFSignatureProto) XXX_Size() int {
	return xxx_messageInfo_TVFSignatureProto.Size(m)
}
func (m *TVFSignatureProto) XXX_DiscardUnknown() {
	xxx_messageInfo_TVFSignatureProto.DiscardUnknown(m)
}

var xxx_messageInfo_TVFSignatureProto proto.InternalMessageInfo

func (m *TVFSignatureProto) GetArgument() []*TVFArgumentProto {
	if m != nil {
		return m.Argument
	}
	return nil
}

func (m *TVFSignatureProto) GetOutputSchema() *TVFRelationProto {
	if m != nil {
		return m.OutputSchema
	}
	return nil
}

func (m *TVFSignatureProto) GetOptions() *TVFSignatureOptionsProto {
	if m != nil {
		return m.Options
	}
	return nil
}

type ProcedureProto struct {
	NamePath             []string                `protobuf:"bytes,1,rep,name=name_path,json=namePath" json:"name_path,omitempty"`
	Signature            *FunctionSignatureProto `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ProcedureProto) Reset()         { *m = ProcedureProto{} }
func (m *ProcedureProto) String() string { return proto.CompactTextString(m) }
func (*ProcedureProto) ProtoMessage()    {}
func (*ProcedureProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f7014610af86dc7, []int{17}
}

func (m *ProcedureProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcedureProto.Unmarshal(m, b)
}
func (m *ProcedureProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcedureProto.Marshal(b, m, deterministic)
}
func (m *ProcedureProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcedureProto.Merge(m, src)
}
func (m *ProcedureProto) XXX_Size() int {
	return xxx_messageInfo_ProcedureProto.Size(m)
}
func (m *ProcedureProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcedureProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProcedureProto proto.InternalMessageInfo

func (m *ProcedureProto) GetNamePath() []string {
	if m != nil {
		return m.NamePath
	}
	return nil
}

func (m *ProcedureProto) GetSignature() *FunctionSignatureProto {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*TVFRelationColumnProto)(nil), "zetasql.TVFRelationColumnProto")
	proto.RegisterType((*TVFRelationProto)(nil), "zetasql.TVFRelationProto")
	proto.RegisterType((*TVFModelProto)(nil), "zetasql.TVFModelProto")
	proto.RegisterType((*TVFConnectionProto)(nil), "zetasql.TVFConnectionProto")
	proto.RegisterType((*TVFDescriptorProto)(nil), "zetasql.TVFDescriptorProto")
	proto.RegisterType((*FunctionArgumentTypeOptionsProto)(nil), "zetasql.FunctionArgumentTypeOptionsProto")
	proto.RegisterType((*ArgumentTypeLambdaProto)(nil), "zetasql.ArgumentTypeLambdaProto")
	proto.RegisterType((*FunctionArgumentTypeProto)(nil), "zetasql.FunctionArgumentTypeProto")
	proto.RegisterType((*FunctionSignatureOptionsProto)(nil), "zetasql.FunctionSignatureOptionsProto")
	proto.RegisterType((*FunctionSignatureProto)(nil), "zetasql.FunctionSignatureProto")
	proto.RegisterType((*FunctionOptionsProto)(nil), "zetasql.FunctionOptionsProto")
	proto.RegisterType((*FunctionProto)(nil), "zetasql.FunctionProto")
	proto.RegisterType((*ResolvedFunctionCallInfoProto)(nil), "zetasql.ResolvedFunctionCallInfoProto")
	proto.RegisterType((*TableValuedFunctionProto)(nil), "zetasql.TableValuedFunctionProto")
	proto.RegisterType((*TVFArgumentProto)(nil), "zetasql.TVFArgumentProto")
	proto.RegisterType((*TVFSignatureOptionsProto)(nil), "zetasql.TVFSignatureOptionsProto")
	proto.RegisterType((*TVFSignatureProto)(nil), "zetasql.TVFSignatureProto")
	proto.RegisterType((*ProcedureProto)(nil), "zetasql.ProcedureProto")
}

func init() { proto.RegisterFile("zetasql/proto/function.proto", fileDescriptor_3f7014610af86dc7) }

var fileDescriptor_3f7014610af86dc7 = []byte{
	// 2051 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xeb, 0x4e, 0x23, 0xc9,
	0x15, 0x96, 0xb1, 0x19, 0xf0, 0x61, 0xec, 0x19, 0x6a, 0x60, 0x68, 0x66, 0x60, 0xf1, 0x3a, 0xc9,
	0xae, 0x77, 0xb2, 0x01, 0x2d, 0xd2, 0xee, 0xac, 0xc8, 0xce, 0x68, 0xc0, 0x80, 0x16, 0x85, 0x9b,
	0x1a, 0xc3, 0x48, 0xc9, 0x8f, 0x52, 0xd1, 0x5d, 0x36, 0xad, 0xf4, 0xc5, 0x54, 0x75, 0x73, 0xd9,
	0x37, 0xc8, 0xbf, 0x24, 0x2f, 0x90, 0x3c, 0x46, 0xde, 0x20, 0xca, 0xdb, 0xe4, 0x7f, 0xa4, 0x28,
	0xaa, 0x53, 0xd5, 0x17, 0xdf, 0x76, 0x98, 0x4d, 0xf2, 0xcf, 0xae, 0xf3, 0x9d, 0x53, 0x55, 0xe7,
	0xfa, 0x55, 0xc3, 0xca, 0x0f, 0x3c, 0x66, 0xf2, 0xda, 0xdf, 0xe8, 0x8b, 0x28, 0x8e, 0x36, 0xba,
	0x49, 0xe8, 0xc4, 0x5e, 0x14, 0xae, 0xe3, 0x5f, 0x32, 0x63, 0xa4, 0x2f, 0x5a, 0x19, 0x2c, 0xb9,
	0xf4, 0x3d, 0x67, 0xc3, 0xe5, 0x7d, 0xc1, 0x1d, 0xa6, 0xa0, 0xf4, 0x96, 0x89, 0xd0, 0x0b, 0x7b,
	0x5a, 0xe5, 0xc5, 0xea, 0x10, 0x72, 0xd0, 0xe2, 0x8b, 0x95, 0x21, 0x71, 0xd4, 0x57, 0x42, 0x69,
	0xa4, 0x5f, 0x0c, 0x49, 0xfb, 0x4c, 0x48, 0x4e, 0xfd, 0xc8, 0xec, 0x24, 0x58, 0xd8, 0xe3, 0x06,
	0xfa, 0x6a, 0x2c, 0x54, 0x70, 0x99, 0x04, 0xb9, 0x86, 0xc1, 0x2e, 0x0f, 0x61, 0xe3, 0xfb, 0x7e,
	0x6a, 0xe6, 0xc5, 0x90, 0xe8, 0x86, 0xf9, 0x49, 0x2a, 0xcb, 0x2e, 0x2d, 0xb8, 0x8c, 0xfc, 0x1b,
	0xee, 0x52, 0x26, 0xe3, 0x0d, 0xc9, 0x85, 0xc7, 0x7c, 0xef, 0x87, 0xc2, 0x06, 0xcd, 0xbf, 0x4d,
	0xc1, 0xf3, 0xce, 0xc5, 0xbe, 0xcd, 0x7d, 0x5c, 0x6d, 0x47, 0x7e, 0x12, 0x84, 0xa7, 0xe8, 0x42,
	0x02, 0x95, 0x90, 0x05, 0xdc, 0x2a, 0x35, 0x4a, 0xad, 0xaa, 0x8d, 0xbf, 0xc9, 0x67, 0x50, 0x51,
	0x47, 0xb0, 0xa6, 0x1a, 0xa5, 0xd6, 0xdc, 0x26, 0x59, 0x37, 0xfb, 0xac, 0x77, 0xee, 0xfb, 0x1c,
	0xb5, 0x6c, 0x94, 0x93, 0x16, 0x3c, 0xf5, 0x24, 0xed, 0x4b, 0x9e, 0xb8, 0x11, 0x75, 0xd0, 0xa8,
	0x55, 0x6e, 0x94, 0x5a, 0xb3, 0x76, 0xdd, 0x93, 0xa7, 0xb8, 0xac, 0xb7, 0x22, 0xbf, 0x83, 0x65,
	0x65, 0x99, 0x8e, 0x73, 0x98, 0x55, 0xc1, 0x6d, 0x1a, 0xd9, 0x36, 0xa7, 0x0a, 0x74, 0x68, 0x30,
	0xb6, 0x82, 0xe8, 0x4d, 0x9f, 0x2b, 0x13, 0xa3, 0x42, 0x65, 0x5c, 0x1d, 0x67, 0xbc, 0xf1, 0xe9,
	0x87, 0x1a, 0x57, 0x26, 0x46, 0x85, 0xcd, 0x3b, 0x78, 0x5a, 0xf0, 0x9c, 0xf6, 0xd9, 0x6b, 0x78,
	0x64, 0x6e, 0x5b, 0x6a, 0x94, 0x5b, 0x73, 0x9b, 0x6b, 0xb9, 0x87, 0xc6, 0x3a, 0xd9, 0x36, 0x70,
	0xf2, 0x4b, 0xa8, 0x7b, 0x92, 0x62, 0x0c, 0x69, 0xcc, 0x2e, 0x7d, 0xed, 0xe2, 0xd9, 0xad, 0xe9,
	0x2e, 0xf3, 0x25, 0xb7, 0x1f, 0x7b, 0xf2, 0x42, 0xc9, 0x3a, 0x4a, 0xd4, 0x7c, 0x07, 0xb5, 0xce,
	0xc5, 0xfe, 0x51, 0xe4, 0x72, 0x7f, 0x72, 0xa8, 0x5e, 0x42, 0xb5, 0x9b, 0xf8, 0x3e, 0x45, 0xc1,
	0x14, 0x0a, 0x66, 0xd5, 0xc2, 0x31, 0x0b, 0x78, 0x73, 0x0f, 0x48, 0xe7, 0x62, 0xbf, 0x1d, 0x85,
	0x21, 0x77, 0xf2, 0xd3, 0x7f, 0xb4, 0x99, 0xaf, 0xd1, 0xcc, 0x2e, 0x97, 0x8e, 0xf0, 0xfa, 0x71,
	0x24, 0xb4, 0x99, 0x35, 0x98, 0xd3, 0xb7, 0xa2, 0xc6, 0x5a, 0xb9, 0x55, 0xb5, 0x41, 0x2f, 0xa1,
	0xda, 0x1f, 0xab, 0xd0, 0xd8, 0x37, 0xd5, 0xb5, 0x2d, 0x7a, 0x49, 0xc0, 0xc3, 0x58, 0x65, 0xd0,
	0x89, 0x2e, 0x29, 0x6d, 0xe5, 0x10, 0xe6, 0x1c, 0x26, 0x5c, 0x2f, 0x64, 0xbe, 0x17, 0xdf, 0xe3,
	0x99, 0xea, 0x9b, 0xaf, 0x32, 0x7f, 0xa6, 0xfa, 0x7b, 0x61, 0x12, 0xc8, 0xf5, 0xd4, 0x4a, 0x3b,
	0xd7, 0xb0, 0x8b, 0xea, 0x2a, 0x21, 0x83, 0x44, 0xc6, 0xf4, 0x92, 0x53, 0x27, 0x0a, 0x65, 0xcc,
	0xc2, 0x58, 0x7b, 0xd8, 0xae, 0xab, 0xf5, 0x1d, 0xde, 0x36, 0xab, 0xe4, 0xf3, 0x1c, 0x19, 0x46,
	0x21, 0x0d, 0x13, 0xdf, 0x37, 0xa9, 0x5b, 0xd3, 0xc8, 0xe3, 0x28, 0x3c, 0x4e, 0x7c, 0xdf, 0xe4,
	0x78, 0x18, 0xc5, 0x94, 0xf5, 0x7a, 0x82, 0xf7, 0x58, 0xac, 0x13, 0x16, 0x73, 0xfc, 0x38, 0x8a,
	0xb7, 0xd3, 0x55, 0xb2, 0x09, 0x8b, 0x68, 0x52, 0x26, 0xfd, 0x7e, 0x24, 0x62, 0xca, 0xaf, 0x13,
	0x7d, 0xa9, 0x69, 0x84, 0x3f, 0x53, 0xc2, 0x33, 0x2d, 0xdb, 0x33, 0xa2, 0x11, 0x9d, 0x48, 0xb8,
	0x5c, 0x78, 0x61, 0xcf, 0x7a, 0x34, 0xa2, 0x73, 0x62, 0x44, 0x2a, 0x56, 0x81, 0x17, 0xea, 0x2c,
	0xb2, 0x66, 0x1a, 0xa5, 0x56, 0xd9, 0x9e, 0x0d, 0xbc, 0x10, 0x33, 0x07, 0x85, 0xec, 0xce, 0x08,
	0x67, 0x8d, 0x90, 0xdd, 0x69, 0xe1, 0x31, 0xfc, 0x9c, 0xdf, 0xc5, 0x82, 0x51, 0x61, 0x72, 0x94,
	0x7a, 0x61, 0x3f, 0x89, 0x4d, 0xe9, 0x4a, 0xca, 0x7c, 0x3f, 0xba, 0xe5, 0xae, 0x55, 0xc5, 0xcd,
	0x1b, 0x88, 0x4d, 0xd3, 0xf9, 0x40, 0x21, 0x75, 0x4e, 0xcb, 0x6d, 0x8d, 0x23, 0x47, 0xb0, 0x38,
	0x64, 0x49, 0x3a, 0x57, 0x3c, 0x60, 0x16, 0x60, 0xd1, 0x2d, 0x8f, 0x2b, 0x0b, 0x5d, 0x10, 0xcf,
	0x44, 0xd1, 0xec, 0x19, 0x6a, 0x91, 0x9f, 0x41, 0x8d, 0x99, 0x08, 0xeb, 0x9c, 0x9a, 0xc3, 0x44,
	0x7c, 0x9c, 0x2e, 0xaa, 0xac, 0x22, 0x0c, 0x56, 0x06, 0x40, 0x43, 0x55, 0x6f, 0x3d, 0x7e, 0x60,
	0xbd, 0x2f, 0x17, 0xad, 0x0e, 0x80, 0x06, 0xb6, 0x18, 0xd3, 0x58, 0xac, 0xda, 0xc7, 0x6e, 0xd1,
	0x19, 0x6e, 0x2d, 0xc4, 0x85, 0xa5, 0xbe, 0x88, 0x1c, 0xee, 0x26, 0x82, 0xd3, 0x6c, 0xb3, 0x20,
	0x72, 0xb9, 0x55, 0xc7, 0x12, 0xf8, 0x72, 0x42, 0x09, 0x9c, 0xa6, 0x5a, 0x69, 0x2d, 0xa8, 0xfe,
	0x60, 0x2f, 0xf6, 0xc7, 0x2d, 0x93, 0x1d, 0x78, 0x31, 0xe8, 0x2b, 0x4f, 0xd2, 0x80, 0x85, 0x2e,
	0x8b, 0x23, 0x71, 0x6f, 0x3d, 0x29, 0xb6, 0x9e, 0xa5, 0xa2, 0x3b, 0x0e, 0xe4, 0x51, 0x8a, 0x22,
	0x27, 0xd0, 0x74, 0xb3, 0xca, 0xa7, 0x38, 0x69, 0x12, 0x0c, 0x38, 0xf6, 0x2f, 0x1a, 0x75, 0xbb,
	0x92, 0xc7, 0xd6, 0xd3, 0x46, 0xa9, 0x35, 0xbd, 0x35, 0xf5, 0xab, 0xaf, 0xec, 0xb5, 0x1c, 0x6d,
	0x67, 0x60, 0x6c, 0x68, 0x27, 0x08, 0x25, 0xdf, 0x42, 0xcd, 0xe5, 0x5d, 0x96, 0xf8, 0xb1, 0xc9,
	0xd2, 0x79, 0x74, 0xe7, 0xb3, 0xec, 0xc2, 0x98, 0xab, 0xda, 0x83, 0x8f, 0x0d, 0x52, 0xa7, 0xef,
	0x3b, 0x20, 0x03, 0x9a, 0x18, 0x1c, 0x8b, 0x4c, 0x1c, 0x52, 0x4f, 0x8b, 0xda, 0x6a, 0xb9, 0xf9,
	0xa7, 0x12, 0x2c, 0x15, 0x5b, 0xd1, 0x21, 0x0b, 0x2e, 0x5d, 0xa6, 0x3b, 0xd1, 0x5b, 0x98, 0x4d,
	0x7d, 0x60, 0x4d, 0x63, 0x5b, 0x6f, 0x8e, 0xc4, 0xa0, 0xa8, 0xab, 0xf7, 0xc8, 0x74, 0xc8, 0x37,
	0x50, 0xb9, 0x8c, 0xdc, 0x7b, 0xac, 0xdc, 0x87, 0xe9, 0x22, 0xbe, 0xf9, 0x97, 0x29, 0x58, 0x9e,
	0x88, 0x21, 0x9b, 0x50, 0xf9, 0xbd, 0x17, 0xba, 0xa6, 0x31, 0x7e, 0x92, 0x59, 0x3d, 0xf3, 0x7a,
	0x21, 0x8b, 0x0b, 0x01, 0xff, 0x8d, 0x17, 0xba, 0x36, 0x62, 0x1f, 0x3c, 0xbe, 0x3f, 0x87, 0x27,
	0x61, 0x12, 0xd0, 0xc8, 0x71, 0x12, 0x21, 0x78, 0xe8, 0x70, 0x89, 0x9d, 0x6d, 0xda, 0xae, 0x87,
	0x49, 0x70, 0x92, 0xaf, 0x92, 0x36, 0xcc, 0x18, 0x1e, 0x84, 0x3d, 0x72, 0x6e, 0xf3, 0x8b, 0x1f,
	0xbd, 0x5d, 0xb1, 0xc1, 0xdb, 0xa9, 0x26, 0xf9, 0x16, 0x1e, 0xf9, 0xe8, 0xee, 0x91, 0x91, 0x3c,
	0x21, 0x22, 0xb6, 0xc1, 0x37, 0xff, 0x31, 0x05, 0xab, 0xe9, 0x3e, 0xd9, 0xbd, 0x07, 0xa6, 0xc8,
	0x2b, 0xa8, 0x79, 0x92, 0xa6, 0xa4, 0x8f, 0xbb, 0x23, 0x63, 0x75, 0x37, 0x13, 0x91, 0x00, 0x3e,
	0x61, 0xae, 0xeb, 0x29, 0x6d, 0xe6, 0xd3, 0x31, 0x44, 0xd1, 0x2a, 0x63, 0xf4, 0x3f, 0xcf, 0xef,
	0x28, 0x38, 0x57, 0x53, 0xc3, 0xf5, 0xc2, 0xde, 0x6e, 0x8e, 0x7f, 0xaf, 0xe1, 0xf6, 0x4a, 0x6e,
	0x6e, 0x54, 0x4a, 0x3a, 0xb0, 0x2c, 0xf8, 0x75, 0xe2, 0x09, 0xee, 0x52, 0x9f, 0x85, 0xbd, 0x84,
	0xf5, 0x38, 0xed, 0x72, 0xbc, 0x83, 0x55, 0x69, 0x94, 0x5b, 0xf5, 0x4d, 0x2b, 0xdb, 0xe9, 0xd0,
	0x00, 0xf6, 0xb5, 0xdc, 0x5e, 0x4a, 0x55, 0x87, 0x04, 0xe4, 0x35, 0x2c, 0x78, 0xaa, 0x5f, 0x7b,
	0x4c, 0x72, 0x97, 0xca, 0xd4, 0x29, 0x7a, 0xd4, 0xa4, 0xf7, 0x26, 0x9e, 0xdc, 0xd6, 0x88, 0xcc,
	0x6b, 0xcd, 0x7f, 0x97, 0xe0, 0xf9, 0x88, 0x2f, 0x47, 0x0b, 0xa0, 0xf4, 0x13, 0x0a, 0xa0, 0x0d,
	0x73, 0x82, 0xc7, 0x89, 0x08, 0x69, 0x21, 0xfb, 0x1e, 0x62, 0x02, 0xb4, 0x9a, 0x5a, 0x20, 0xab,
	0x00, 0x4e, 0x14, 0xc6, 0xfc, 0x2e, 0xa6, 0x9e, 0x8b, 0xd9, 0x56, 0xb6, 0xab, 0x66, 0xe5, 0xc0,
	0x25, 0xef, 0xf2, 0x4c, 0xd4, 0xac, 0xf1, 0xb3, 0x11, 0xfb, 0x63, 0x33, 0x24, 0x4b, 0xc3, 0xe6,
	0x3f, 0x67, 0x60, 0x21, 0x85, 0x0e, 0xe4, 0xd0, 0x6b, 0x58, 0x30, 0x53, 0x58, 0xd2, 0xe8, 0x86,
	0x0b, 0xea, 0xf8, 0x2c, 0x91, 0x9a, 0x26, 0xe5, 0x2e, 0x4d, 0x21, 0x27, 0x37, 0x5c, 0xb4, 0x11,
	0x40, 0x62, 0x58, 0xba, 0xf5, 0x42, 0x37, 0xba, 0xcd, 0xa6, 0x77, 0x3a, 0xce, 0xd1, 0x07, 0xf5,
	0x31, 0xd5, 0xa2, 0x7b, 0xf9, 0x7b, 0xd4, 0xc2, 0xb9, 0x6e, 0x66, 0xfc, 0xd6, 0xfc, 0x89, 0xbd,
	0xbb, 0x67, 0xd3, 0xf3, 0xe3, 0xb3, 0xf3, 0xd3, 0xd3, 0x13, 0xbb, 0xb3, 0xb7, 0x6b, 0x2f, 0xde,
	0xe6, 0x30, 0x2f, 0xec, 0x19, 0x24, 0x79, 0x03, 0x4b, 0xd9, 0x71, 0xcd, 0xf6, 0x5d, 0xc1, 0x02,
	0x9d, 0xbf, 0x85, 0x13, 0x2f, 0xa6, 0x28, 0xbd, 0xdb, 0xbe, 0xc6, 0x90, 0xef, 0x20, 0xeb, 0xf8,
	0x92, 0x32, 0xa1, 0xf8, 0x12, 0x17, 0x8e, 0xa7, 0x28, 0x29, 0xb2, 0x9b, 0xad, 0x4a, 0x2c, 0x12,
	0x6e, 0x2f, 0x66, 0xa0, 0x6d, 0xc1, 0xdb, 0x29, 0x64, 0xb4, 0xde, 0xa6, 0x27, 0xd7, 0xdb, 0x2a,
	0x00, 0xe6, 0xa9, 0x1e, 0xe9, 0x8f, 0x70, 0xa4, 0x57, 0x71, 0x05, 0xe7, 0xf9, 0x32, 0xcc, 0xca,
	0x6b, 0x43, 0x3c, 0x67, 0x50, 0x38, 0x23, 0xaf, 0x91, 0x77, 0x92, 0x6f, 0x60, 0x01, 0x19, 0x09,
	0xe5, 0x77, 0x31, 0x17, 0xaa, 0x5a, 0x13, 0xc9, 0x7a, 0x9a, 0xd6, 0xa4, 0x07, 0x24, 0x88, 0xd8,
	0x33, 0x80, 0x73, 0x25, 0x27, 0x87, 0x00, 0x37, 0x91, 0xa2, 0x17, 0xc8, 0xbe, 0xaa, 0x18, 0x83,
	0x4f, 0x27, 0xc4, 0xe0, 0x22, 0x03, 0x6e, 0x55, 0x0f, 0x8e, 0x8e, 0xce, 0x3b, 0xdb, 0x3b, 0x87,
	0x7b, 0x76, 0x41, 0x9f, 0x7c, 0x05, 0xf3, 0x79, 0x5e, 0xa8, 0x20, 0xd0, 0xcb, 0x7b, 0x24, 0x38,
	0xd9, 0x7d, 0x9f, 0x64, 0x49, 0xa1, 0xc4, 0x3b, 0xf7, 0x3f, 0x5e, 0xf3, 0x73, 0x3f, 0xb5, 0xe6,
	0xbf, 0x84, 0x7a, 0x76, 0x10, 0xdf, 0x0b, 0xbc, 0x18, 0xb9, 0x4e, 0x76, 0x8a, 0x5a, 0x2a, 0x3c,
	0x54, 0x32, 0x72, 0x08, 0x6b, 0x19, 0x5a, 0xb1, 0x5b, 0x7a, 0xc5, 0x42, 0xd7, 0x57, 0xc9, 0x19,
	0x44, 0xae, 0xd7, 0xf5, 0xb8, 0x40, 0x1e, 0x93, 0xa9, 0xaf, 0xa4, 0x68, 0xc5, 0x7a, 0xbf, 0x37,
	0xd8, 0x23, 0x03, 0x25, 0x6f, 0xc0, 0xca, 0xac, 0x49, 0xd6, 0xe5, 0x94, 0x0b, 0x11, 0x89, 0x9c,
	0xb0, 0x64, 0xf9, 0x92, 0xa2, 0xce, 0x58, 0x97, 0xef, 0x29, 0x0c, 0x12, 0x91, 0xb7, 0x05, 0xf5,
	0x2b, 0x76, 0x33, 0x70, 0x8a, 0x27, 0x05, 0xf5, 0xe7, 0x29, 0xea, 0x7b, 0x04, 0x65, 0xdb, 0x7f,
	0x07, 0x56, 0x22, 0xb9, 0xa4, 0x49, 0xbf, 0xaf, 0x0a, 0x93, 0x49, 0x4e, 0xb3, 0xa4, 0x99, 0x2f,
	0xe8, 0x2f, 0x28, 0xd4, 0xb9, 0x02, 0xb5, 0x99, 0xe4, 0x67, 0x3a, 0x8f, 0x9a, 0x7f, 0x2e, 0x43,
	0x2d, 0x8d, 0xba, 0xae, 0xf5, 0x97, 0x50, 0x35, 0xdc, 0x31, 0xbe, 0x32, 0x2f, 0x97, 0x59, 0xfd,
	0xb8, 0x8c, 0xaf, 0xc8, 0x02, 0x4c, 0xf7, 0x44, 0x94, 0xf4, 0xcd, 0x3b, 0x48, 0xff, 0x21, 0x1b,
	0x50, 0xc1, 0xdb, 0x96, 0x31, 0x9d, 0x5e, 0x4e, 0x48, 0x27, 0x64, 0x63, 0x08, 0x24, 0x6f, 0xa0,
	0x9a, 0xf7, 0xe5, 0xca, 0xd0, 0x3b, 0x71, 0x7c, 0x0b, 0xb6, 0x73, 0x0d, 0xf2, 0x3a, 0xef, 0x74,
	0x7a, 0x5e, 0xae, 0x8e, 0x28, 0x8f, 0x9f, 0xb3, 0xe7, 0xb0, 0x38, 0xf6, 0x5b, 0x03, 0x96, 0xcd,
	0x5c, 0xa1, 0x10, 0x90, 0x91, 0xda, 0x08, 0x4a, 0x79, 0xa9, 0x21, 0xe7, 0xfd, 0x51, 0x89, 0x7a,
	0x3b, 0xc4, 0x3c, 0xe8, 0xfb, 0xaa, 0xa6, 0xd1, 0xf9, 0xe9, 0x87, 0x13, 0x3a, 0xc8, 0xd9, 0x67,
	0xd0, 0x9b, 0x8d, 0x0c, 0x7b, 0x76, 0xed, 0x0f, 0x77, 0x7e, 0x0c, 0xca, 0x1a, 0xac, 0xda, 0xe6,
	0xb3, 0x45, 0x2a, 0x6f, 0x33, 0xdf, 0x3f, 0x08, 0xbb, 0x11, 0x9e, 0xa2, 0xf9, 0xd7, 0x32, 0x58,
	0xc8, 0x1b, 0x91, 0xbe, 0xb9, 0x1f, 0x11, 0xc0, 0x01, 0xcf, 0xeb, 0x31, 0xf4, 0x31, 0x9e, 0xdf,
	0x31, 0xf4, 0x49, 0x47, 0x7a, 0x7d, 0x42, 0xa4, 0xc7, 0x1c, 0x4d, 0x0d, 0x30, 0x43, 0xad, 0xb6,
	0x07, 0x5a, 0xd0, 0xec, 0x03, 0x5b, 0xd0, 0x40, 0xdf, 0x99, 0x18, 0xc7, 0x47, 0xff, 0x55, 0x1c,
	0x47, 0x1e, 0x59, 0xd3, 0xe8, 0xbd, 0xc1, 0x47, 0xd6, 0x2f, 0xa0, 0xee, 0x24, 0x32, 0x8e, 0x02,
	0x6a, 0x46, 0xaf, 0x69, 0xcd, 0x35, 0xbd, 0xda, 0xd6, 0x8b, 0xcd, 0x7f, 0x4d, 0xe1, 0xc7, 0x91,
	0x34, 0xae, 0x3a, 0x34, 0xbb, 0xf0, 0x44, 0x3a, 0xcc, 0x67, 0x82, 0x16, 0xd8, 0x84, 0x3a, 0xf1,
	0xcb, 0x41, 0x86, 0xff, 0xde, 0x8b, 0xaf, 0x72, 0x0e, 0x50, 0xd7, 0x3a, 0xa9, 0x29, 0xb2, 0x0f,
	0xf3, 0xd9, 0xd3, 0x32, 0xb3, 0x33, 0xf5, 0xa1, 0x67, 0xe5, 0xd3, 0x54, 0x27, 0xb3, 0xf3, 0x06,
	0xea, 0xaa, 0x1a, 0xfd, 0xdc, 0x88, 0x66, 0xb0, 0xcf, 0x8b, 0x46, 0xf2, 0x6f, 0x2c, 0x76, 0x0d,
	0xd1, 0x99, 0xfa, 0x21, 0x3c, 0x73, 0xb2, 0xcf, 0x27, 0xb9, 0x8d, 0xca, 0xd0, 0x85, 0x46, 0xbf,
	0xb2, 0xd8, 0x24, 0xd7, 0x2b, 0x5a, 0x2b, 0xbc, 0xa5, 0x0a, 0xaf, 0x8d, 0x11, 0x6b, 0x43, 0x1f,
	0x5b, 0x6c, 0x92, 0xeb, 0xa5, 0xd6, 0x9a, 0x7f, 0x28, 0x81, 0xd5, 0xb9, 0xd8, 0x1f, 0xcf, 0x88,
	0x3f, 0xcc, 0x72, 0x4b, 0xff, 0x43, 0x96, 0xdb, 0xfc, 0x7b, 0x09, 0xe6, 0x8b, 0x67, 0xd1, 0x87,
	0xf8, 0x7a, 0x84, 0x51, 0x0e, 0xc4, 0x6e, 0x20, 0x6f, 0x0a, 0x44, 0xf2, 0x2d, 0xd4, 0xa2, 0x24,
	0x2e, 0x7c, 0x4e, 0xf8, 0x60, 0xdc, 0x1f, 0x6b, 0xbc, 0xf9, 0x8e, 0xf0, 0xeb, 0xe1, 0xe7, 0xca,
	0xa7, 0x45, 0xcd, 0x0f, 0xf0, 0x43, 0x1f, 0xea, 0xd9, 0x1b, 0xfb, 0xff, 0xde, 0x6b, 0x76, 0xf6,
	0x81, 0x38, 0x51, 0xb0, 0xde, 0x8b, 0xa2, 0x9e, 0xcf, 0x53, 0xbd, 0x9d, 0xfa, 0x40, 0xb3, 0x93,
	0xbf, 0x6d, 0xf4, 0xbc, 0xf8, 0x2a, 0xb9, 0x5c, 0x77, 0xa2, 0x60, 0x83, 0xf5, 0x65, 0x1c, 0xba,
	0x97, 0x1b, 0x03, 0xdf, 0xc5, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xee, 0x9f, 0x4c, 0x27,
	0x17, 0x00, 0x00,
}
