// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/public/parse_location_range.proto

package public

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParseLocationRangeProto struct {
	Filename             *string  `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Start                *int32   `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End                  *int32   `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseLocationRangeProto) Reset()         { *m = ParseLocationRangeProto{} }
func (m *ParseLocationRangeProto) String() string { return proto.CompactTextString(m) }
func (*ParseLocationRangeProto) ProtoMessage()    {}
func (*ParseLocationRangeProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b8eec12614dd5a8, []int{0}
}

func (m *ParseLocationRangeProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseLocationRangeProto.Unmarshal(m, b)
}
func (m *ParseLocationRangeProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseLocationRangeProto.Marshal(b, m, deterministic)
}
func (m *ParseLocationRangeProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseLocationRangeProto.Merge(m, src)
}
func (m *ParseLocationRangeProto) XXX_Size() int {
	return xxx_messageInfo_ParseLocationRangeProto.Size(m)
}
func (m *ParseLocationRangeProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseLocationRangeProto.DiscardUnknown(m)
}

var xxx_messageInfo_ParseLocationRangeProto proto.InternalMessageInfo

func (m *ParseLocationRangeProto) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *ParseLocationRangeProto) GetStart() int32 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *ParseLocationRangeProto) GetEnd() int32 {
	if m != nil && m.End != nil {
		return *m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*ParseLocationRangeProto)(nil), "zetasql.ParseLocationRangeProto")
}

func init() {
	proto.RegisterFile("zetasql/public/parse_location_range.proto", fileDescriptor_9b8eec12614dd5a8)
}

var fileDescriptor_9b8eec12614dd5a8 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x71, 0xe2, 0xb2, 0xa8, 0x39, 0x49, 0x10, 0x2c, 0x7b, 0x5a, 0x3d, 0xad, 0x97, 0xe4,
	0x1d, 0xf6, 0xec, 0xa1, 0x54, 0xbc, 0x14, 0xa4, 0x4c, 0xd3, 0x31, 0x06, 0xd2, 0x4c, 0x9a, 0x4c,
	0x2f, 0x3e, 0xbd, 0xb4, 0x16, 0xa1, 0xb7, 0x7c, 0xe1, 0x07, 0x7f, 0x46, 0xbe, 0xfe, 0x20, 0x43,
	0x99, 0x82, 0x49, 0x73, 0x1f, 0xbc, 0x35, 0x09, 0x72, 0xc1, 0x2e, 0x90, 0x05, 0xf6, 0x14, 0xbb,
	0x0c, 0xd1, 0xa1, 0x4e, 0x99, 0x98, 0xd4, 0xed, 0x46, 0x5f, 0x3e, 0xe5, 0x53, 0xbd, 0xb0, 0xb7,
	0x4d, 0x35, 0x0b, 0xaa, 0x57, 0x73, 0x92, 0x77, 0x5f, 0x3e, 0x60, 0x84, 0x11, 0x2b, 0x71, 0x16,
	0x97, 0xfb, 0xe6, 0x7f, 0xab, 0x47, 0x79, 0x2c, 0x0c, 0x99, 0xab, 0x9b, 0xb3, 0xb8, 0x1c, 0x9b,
	0xbf, 0xa1, 0x1e, 0xe4, 0x01, 0xe3, 0x50, 0x1d, 0xd6, 0xbf, 0xe5, 0x79, 0xfd, 0x90, 0xca, 0xd2,
	0xa8, 0x1d, 0x91, 0x0b, 0xa8, 0xb7, 0xe8, 0xf5, 0xd4, 0x22, 0xc3, 0xfb, 0x14, 0x76, 0xe5, 0x35,
	0x5a, 0x6a, 0xd1, 0x3e, 0x3b, 0xcf, 0xdf, 0x73, 0xaf, 0x2d, 0x8d, 0x06, 0x52, 0xe1, 0x38, 0xf4,
	0x66, 0x7f, 0xd9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xbc, 0x7b, 0x28, 0xea, 0x00, 0x00,
	0x00,
}
