// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/public/error_location.proto

package public

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorLocation struct {
	Line                 *int32         `protobuf:"varint,1,opt,name=line,def=1" json:"line,omitempty"`
	Column               *int32         `protobuf:"varint,2,opt,name=column,def=1" json:"column,omitempty"`
	Filename             *string        `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
	ErrorSource          []*ErrorSource `protobuf:"bytes,4,rep,name=error_source,json=errorSource" json:"error_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ErrorLocation) Reset()         { *m = ErrorLocation{} }
func (m *ErrorLocation) String() string { return proto.CompactTextString(m) }
func (*ErrorLocation) ProtoMessage()    {}
func (*ErrorLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2518f6889f67388c, []int{0}
}

func (m *ErrorLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorLocation.Unmarshal(m, b)
}
func (m *ErrorLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorLocation.Marshal(b, m, deterministic)
}
func (m *ErrorLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorLocation.Merge(m, src)
}
func (m *ErrorLocation) XXX_Size() int {
	return xxx_messageInfo_ErrorLocation.Size(m)
}
func (m *ErrorLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorLocation.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorLocation proto.InternalMessageInfo

const Default_ErrorLocation_Line int32 = 1
const Default_ErrorLocation_Column int32 = 1

func (m *ErrorLocation) GetLine() int32 {
	if m != nil && m.Line != nil {
		return *m.Line
	}
	return Default_ErrorLocation_Line
}

func (m *ErrorLocation) GetColumn() int32 {
	if m != nil && m.Column != nil {
		return *m.Column
	}
	return Default_ErrorLocation_Column
}

func (m *ErrorLocation) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *ErrorLocation) GetErrorSource() []*ErrorSource {
	if m != nil {
		return m.ErrorSource
	}
	return nil
}

type ErrorSource struct {
	ErrorMessage            *string        `protobuf:"bytes,1,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	ErrorMessageCaretString *string        `protobuf:"bytes,2,opt,name=error_message_caret_string,json=errorMessageCaretString" json:"error_message_caret_string,omitempty"`
	ErrorLocation           *ErrorLocation `protobuf:"bytes,3,opt,name=error_location,json=errorLocation" json:"error_location,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}       `json:"-"`
	XXX_unrecognized        []byte         `json:"-"`
	XXX_sizecache           int32          `json:"-"`
}

func (m *ErrorSource) Reset()         { *m = ErrorSource{} }
func (m *ErrorSource) String() string { return proto.CompactTextString(m) }
func (*ErrorSource) ProtoMessage()    {}
func (*ErrorSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_2518f6889f67388c, []int{1}
}

func (m *ErrorSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorSource.Unmarshal(m, b)
}
func (m *ErrorSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorSource.Marshal(b, m, deterministic)
}
func (m *ErrorSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorSource.Merge(m, src)
}
func (m *ErrorSource) XXX_Size() int {
	return xxx_messageInfo_ErrorSource.Size(m)
}
func (m *ErrorSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorSource.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorSource proto.InternalMessageInfo

func (m *ErrorSource) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

func (m *ErrorSource) GetErrorMessageCaretString() string {
	if m != nil && m.ErrorMessageCaretString != nil {
		return *m.ErrorMessageCaretString
	}
	return ""
}

func (m *ErrorSource) GetErrorLocation() *ErrorLocation {
	if m != nil {
		return m.ErrorLocation
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorLocation)(nil), "zetasql.ErrorLocation")
	proto.RegisterType((*ErrorSource)(nil), "zetasql.ErrorSource")
}

func init() {
	proto.RegisterFile("zetasql/public/error_location.proto", fileDescriptor_2518f6889f67388c)
}

var fileDescriptor_2518f6889f67388c = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x65, 0x5a, 0xfe, 0xc4, 0xa1, 0x0c, 0x16, 0x7f, 0x42, 0xa7, 0xd0, 0x2e, 0x99, 0x12,
	0xd1, 0xa5, 0x12, 0x88, 0x05, 0xc4, 0x06, 0x8b, 0xbb, 0xb1, 0x44, 0x8e, 0x31, 0xc1, 0x92, 0xe3,
	0x0b, 0xb6, 0xb3, 0xf0, 0x20, 0x3c, 0x06, 0xcf, 0x88, 0x6a, 0x27, 0xb4, 0x19, 0xbf, 0xfb, 0xbe,
	0xbb, 0xfb, 0xf9, 0x8c, 0x97, 0xdf, 0xc2, 0x31, 0xfb, 0xa5, 0x8a, 0xb6, 0xab, 0x94, 0xe4, 0x85,
	0x30, 0x06, 0x4c, 0xa9, 0x80, 0x33, 0x27, 0x41, 0xe7, 0xad, 0x01, 0x07, 0xe4, 0xb8, 0x0f, 0x2d,
	0x7e, 0x10, 0x9e, 0x3d, 0x6f, 0x13, 0x2f, 0x7d, 0x80, 0x5c, 0xe0, 0xa9, 0x92, 0x5a, 0x24, 0x28,
	0x45, 0xd9, 0xe1, 0x1d, 0xba, 0xa5, 0x5e, 0x92, 0x6b, 0x7c, 0xc4, 0x41, 0x75, 0x8d, 0x4e, 0x0e,
	0x06, 0xa3, 0x2f, 0x90, 0x39, 0x3e, 0xf9, 0x90, 0x4a, 0x68, 0xd6, 0x88, 0x64, 0x92, 0xa2, 0x2c,
	0xa2, 0xff, 0x9a, 0xac, 0xf1, 0x69, 0x00, 0xb0, 0xd0, 0x19, 0x2e, 0x92, 0x69, 0x3a, 0xc9, 0xe2,
	0xd5, 0x79, 0xde, 0xef, 0xcf, 0xfd, 0xee, 0x8d, 0xf7, 0x68, 0x2c, 0x76, 0x62, 0xf1, 0x8b, 0x70,
	0xbc, 0x67, 0x92, 0x25, 0x9e, 0x85, 0x41, 0x8d, 0xb0, 0x96, 0xd5, 0x81, 0x2f, 0xa2, 0x61, 0xfa,
	0x6b, 0xa8, 0x91, 0x7b, 0x3c, 0x1f, 0x85, 0x4a, 0xce, 0x8c, 0x70, 0xa5, 0x75, 0x46, 0xea, 0xda,
	0x83, 0x47, 0xf4, 0x6a, 0xbf, 0xe3, 0x69, 0xeb, 0x6f, 0xbc, 0x4d, 0x1e, 0xf0, 0xd9, 0xf8, 0x56,
	0xfe, 0x31, 0xf1, 0xea, 0x72, 0x0c, 0x3b, 0x1c, 0x8a, 0x06, 0x9e, 0x41, 0x3e, 0xae, 0x31, 0xe1,
	0xd0, 0xe4, 0x35, 0x40, 0xad, 0xc4, 0xd0, 0xf2, 0x76, 0x53, 0x4b, 0xf7, 0xd9, 0x55, 0x39, 0x87,
	0xa6, 0x60, 0xad, 0x75, 0xfa, 0xbd, 0x2a, 0xc6, 0x1f, 0xf4, 0x17, 0x00, 0x00, 0xff, 0xff, 0x87,
	0x6d, 0x3c, 0x29, 0xb1, 0x01, 0x00, 0x00,
}
