// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/public/proto/type_annotation.proto

package zetasql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FieldFormat_Format int32

const (
	FieldFormat_DEFAULT_FORMAT                                   FieldFormat_Format = 0
	FieldFormat_DATE                                             FieldFormat_Format = 1
	FieldFormat_TIMESTAMP_SECONDS                                FieldFormat_Format = 2
	FieldFormat_TIMESTAMP_MILLIS                                 FieldFormat_Format = 3
	FieldFormat_TIMESTAMP_MICROS                                 FieldFormat_Format = 4
	FieldFormat_TIMESTAMP_NANOS                                  FieldFormat_Format = 5
	FieldFormat_DATE_DECIMAL                                     FieldFormat_Format = 6
	FieldFormat_TIME_MICROS                                      FieldFormat_Format = 7
	FieldFormat_DATETIME_MICROS                                  FieldFormat_Format = 8
	FieldFormat_ST_GEOGRAPHY_ENCODED                             FieldFormat_Format = 9
	FieldFormat_NUMERIC                                          FieldFormat_Format = 10
	FieldFormat_BIGNUMERIC                                       FieldFormat_Format = 11
	FieldFormat_JSON                                             FieldFormat_Format = 12
	FieldFormat_INTERVAL                                         FieldFormat_Format = 14
	FieldFormat___FieldFormat_Type__switch_must_have_a_default__ FieldFormat_Format = -1
)

var FieldFormat_Format_name = map[int32]string{
	0:  "DEFAULT_FORMAT",
	1:  "DATE",
	2:  "TIMESTAMP_SECONDS",
	3:  "TIMESTAMP_MILLIS",
	4:  "TIMESTAMP_MICROS",
	5:  "TIMESTAMP_NANOS",
	6:  "DATE_DECIMAL",
	7:  "TIME_MICROS",
	8:  "DATETIME_MICROS",
	9:  "ST_GEOGRAPHY_ENCODED",
	10: "NUMERIC",
	11: "BIGNUMERIC",
	12: "JSON",
	14: "INTERVAL",
	-1: "__FieldFormat_Type__switch_must_have_a_default__",
}

var FieldFormat_Format_value = map[string]int32{
	"DEFAULT_FORMAT":       0,
	"DATE":                 1,
	"TIMESTAMP_SECONDS":    2,
	"TIMESTAMP_MILLIS":     3,
	"TIMESTAMP_MICROS":     4,
	"TIMESTAMP_NANOS":      5,
	"DATE_DECIMAL":         6,
	"TIME_MICROS":          7,
	"DATETIME_MICROS":      8,
	"ST_GEOGRAPHY_ENCODED": 9,
	"NUMERIC":              10,
	"BIGNUMERIC":           11,
	"JSON":                 12,
	"INTERVAL":             14,
	"__FieldFormat_Type__switch_must_have_a_default__": -1,
}

func (x FieldFormat_Format) Enum() *FieldFormat_Format {
	p := new(FieldFormat_Format)
	*p = x
	return p
}

func (x FieldFormat_Format) String() string {
	return proto.EnumName(FieldFormat_Format_name, int32(x))
}

func (x *FieldFormat_Format) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FieldFormat_Format_value, data, "FieldFormat_Format")
	if err != nil {
		return err
	}
	*x = FieldFormat_Format(value)
	return nil
}

func (FieldFormat_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e931340aaef647c9, []int{0, 0}
}

type DeprecatedEncoding_Encoding int32

const (
	DeprecatedEncoding_DEFAULT_ENCODING                                     DeprecatedEncoding_Encoding = 0
	DeprecatedEncoding_DATE_PACKED32                                        DeprecatedEncoding_Encoding = 1
	DeprecatedEncoding_DATE_DECIMAL                                         DeprecatedEncoding_Encoding = 1
	DeprecatedEncoding___FieldFormat_Encoding__switch_must_have_a_default__ DeprecatedEncoding_Encoding = -1
)

var DeprecatedEncoding_Encoding_name = map[int32]string{
	0: "DEFAULT_ENCODING",
	1: "DATE_PACKED32",
	// Duplicate value: 1: "DATE_DECIMAL",
	-1: "__FieldFormat_Encoding__switch_must_have_a_default__",
}

var DeprecatedEncoding_Encoding_value = map[string]int32{
	"DEFAULT_ENCODING": 0,
	"DATE_PACKED32":    1,
	"DATE_DECIMAL":     1,
	"__FieldFormat_Encoding__switch_must_have_a_default__": -1,
}

func (x DeprecatedEncoding_Encoding) Enum() *DeprecatedEncoding_Encoding {
	p := new(DeprecatedEncoding_Encoding)
	*p = x
	return p
}

func (x DeprecatedEncoding_Encoding) String() string {
	return proto.EnumName(DeprecatedEncoding_Encoding_name, int32(x))
}

func (x *DeprecatedEncoding_Encoding) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DeprecatedEncoding_Encoding_value, data, "DeprecatedEncoding_Encoding")
	if err != nil {
		return err
	}
	*x = DeprecatedEncoding_Encoding(value)
	return nil
}

func (DeprecatedEncoding_Encoding) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e931340aaef647c9, []int{1, 0}
}

type FieldFormat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldFormat) Reset()         { *m = FieldFormat{} }
func (m *FieldFormat) String() string { return proto.CompactTextString(m) }
func (*FieldFormat) ProtoMessage()    {}
func (*FieldFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_e931340aaef647c9, []int{0}
}

func (m *FieldFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldFormat.Unmarshal(m, b)
}
func (m *FieldFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldFormat.Marshal(b, m, deterministic)
}
func (m *FieldFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldFormat.Merge(m, src)
}
func (m *FieldFormat) XXX_Size() int {
	return xxx_messageInfo_FieldFormat.Size(m)
}
func (m *FieldFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldFormat.DiscardUnknown(m)
}

var xxx_messageInfo_FieldFormat proto.InternalMessageInfo

type DeprecatedEncoding struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeprecatedEncoding) Reset()         { *m = DeprecatedEncoding{} }
func (m *DeprecatedEncoding) String() string { return proto.CompactTextString(m) }
func (*DeprecatedEncoding) ProtoMessage()    {}
func (*DeprecatedEncoding) Descriptor() ([]byte, []int) {
	return fileDescriptor_e931340aaef647c9, []int{1}
}

func (m *DeprecatedEncoding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeprecatedEncoding.Unmarshal(m, b)
}
func (m *DeprecatedEncoding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeprecatedEncoding.Marshal(b, m, deterministic)
}
func (m *DeprecatedEncoding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeprecatedEncoding.Merge(m, src)
}
func (m *DeprecatedEncoding) XXX_Size() int {
	return xxx_messageInfo_DeprecatedEncoding.Size(m)
}
func (m *DeprecatedEncoding) XXX_DiscardUnknown() {
	xxx_messageInfo_DeprecatedEncoding.DiscardUnknown(m)
}

var xxx_messageInfo_DeprecatedEncoding proto.InternalMessageInfo

var E_Format = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldFormat_Format)(nil),
	Field:         68711883,
	Name:          "zetasql.format",
	Tag:           "varint,68711883,opt,name=format,enum=zetasql.FieldFormat_Format",
	Filename:      "zetasql/public/proto/type_annotation.proto",
}

var E_Type = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldFormat_Format)(nil),
	Field:         49796453,
	Name:          "zetasql.type",
	Tag:           "varint,49796453,opt,name=type,enum=zetasql.FieldFormat_Format",
	Filename:      "zetasql/public/proto/type_annotation.proto",
}

var E_Encoding = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*DeprecatedEncoding_Encoding)(nil),
	Field:         62897319,
	Name:          "zetasql.encoding",
	Tag:           "varint,62897319,opt,name=encoding,enum=zetasql.DeprecatedEncoding_Encoding",
	Filename:      "zetasql/public/proto/type_annotation.proto",
}

var E_UseDefaults = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         49779519,
	Name:          "zetasql.use_defaults",
	Tag:           "varint,49779519,opt,name=use_defaults,def=1",
	Filename:      "zetasql/public/proto/type_annotation.proto",
}

var E_UseFieldDefaults = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         49659010,
	Name:          "zetasql.use_field_defaults",
	Tag:           "varint,49659010,opt,name=use_field_defaults,def=1",
	Filename:      "zetasql/public/proto/type_annotation.proto",
}

func init() {
	proto.RegisterEnum("zetasql.FieldFormat_Format", FieldFormat_Format_name, FieldFormat_Format_value)
	proto.RegisterEnum("zetasql.DeprecatedEncoding_Encoding", DeprecatedEncoding_Encoding_name, DeprecatedEncoding_Encoding_value)
	proto.RegisterType((*FieldFormat)(nil), "zetasql.FieldFormat")
	proto.RegisterType((*DeprecatedEncoding)(nil), "zetasql.DeprecatedEncoding")
	proto.RegisterExtension(E_Format)
	proto.RegisterExtension(E_Type)
	proto.RegisterExtension(E_Encoding)
	proto.RegisterExtension(E_UseDefaults)
	proto.RegisterExtension(E_UseFieldDefaults)
}

func init() {
	proto.RegisterFile("zetasql/public/proto/type_annotation.proto", fileDescriptor_e931340aaef647c9)
}

var fileDescriptor_e931340aaef647c9 = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x31, 0x6f, 0xd3, 0x4e,
	0x18, 0xc6, 0xeb, 0xfc, 0xf3, 0x6f, 0xc3, 0x9b, 0x90, 0x5e, 0xaf, 0x45, 0x54, 0x45, 0x15, 0x55,
	0xc4, 0x80, 0x10, 0x72, 0x50, 0x61, 0x8a, 0xc4, 0xe0, 0xda, 0x97, 0x60, 0x88, 0xed, 0x60, 0xbb,
	0x95, 0x98, 0x4e, 0xae, 0x73, 0x49, 0x2d, 0xa5, 0xb1, 0xb1, 0xcf, 0x20, 0x18, 0x99, 0xf9, 0x16,
	0x48, 0x20, 0xf1, 0x25, 0x58, 0xd8, 0x58, 0x11, 0x23, 0x88, 0x81, 0x89, 0x2f, 0x40, 0x17, 0x40,
	0x67, 0xe7, 0xda, 0x40, 0x87, 0x90, 0x25, 0x77, 0xaf, 0x9e, 0xfb, 0xbd, 0xef, 0x3d, 0xf7, 0xc8,
	0x70, 0xe3, 0x39, 0xe3, 0x41, 0xf6, 0x78, 0xd2, 0x4e, 0xf2, 0xc3, 0x49, 0x14, 0xb6, 0x93, 0x34,
	0xe6, 0x71, 0x9b, 0x3f, 0x4b, 0x18, 0x0d, 0xa6, 0xd3, 0x98, 0x07, 0x3c, 0x8a, 0xa7, 0x6a, 0x51,
	0xc5, 0x2b, 0x33, 0xed, 0xd6, 0xce, 0x38, 0x8e, 0xc7, 0x13, 0x56, 0x8a, 0x0f, 0xf3, 0x51, 0x7b,
	0xc8, 0xb2, 0x30, 0x8d, 0x12, 0x1e, 0xa7, 0xa5, 0xb4, 0xf5, 0xb1, 0x02, 0xf5, 0x6e, 0xc4, 0x26,
	0xc3, 0x6e, 0x9c, 0x1e, 0x07, 0xbc, 0xf5, 0xbe, 0x02, 0xcb, 0xe5, 0x12, 0x63, 0x68, 0x1a, 0xa4,
	0xab, 0xed, 0xf7, 0x7d, 0xda, 0x75, 0x5c, 0x4b, 0xf3, 0xd1, 0x12, 0xae, 0x41, 0xd5, 0xd0, 0x7c,
	0x82, 0x14, 0x7c, 0x09, 0xd6, 0x7c, 0xd3, 0x22, 0x9e, 0xaf, 0x59, 0x03, 0xea, 0x11, 0xdd, 0xb1,
	0x0d, 0x0f, 0x55, 0xf0, 0x06, 0xa0, 0xb3, 0xb2, 0x65, 0xf6, 0xfb, 0xa6, 0x87, 0xfe, 0xfb, 0xbb,
	0xaa, 0xbb, 0x8e, 0x87, 0xaa, 0x78, 0x1d, 0x56, 0xcf, 0xaa, 0xb6, 0x66, 0x3b, 0x1e, 0xfa, 0x1f,
	0x23, 0x68, 0x88, 0x0e, 0xd4, 0x20, 0xba, 0x69, 0x69, 0x7d, 0xb4, 0x8c, 0x57, 0xa1, 0x2e, 0x64,
	0xf2, 0xdc, 0x8a, 0x38, 0x27, 0x24, 0xf3, 0xc5, 0x1a, 0xde, 0x84, 0x0d, 0xcf, 0xa7, 0x3d, 0xe2,
	0xf4, 0x5c, 0x6d, 0x70, 0xef, 0x11, 0x25, 0xb6, 0xee, 0x18, 0xc4, 0x40, 0x17, 0x70, 0x1d, 0x56,
	0xec, 0x7d, 0x8b, 0xb8, 0xa6, 0x8e, 0x00, 0x37, 0x01, 0xf6, 0xcc, 0x9e, 0xdc, 0xd7, 0xc5, 0x85,
	0xee, 0x7b, 0x8e, 0x8d, 0x1a, 0xb8, 0x01, 0x35, 0xd3, 0xf6, 0x89, 0x7b, 0xa0, 0xf5, 0x51, 0x13,
	0xdf, 0x85, 0x5b, 0x94, 0xce, 0x19, 0x43, 0x7d, 0xe1, 0x34, 0xcd, 0x9e, 0x46, 0x3c, 0x3c, 0xa2,
	0xc7, 0x79, 0xc6, 0xe9, 0x51, 0xf0, 0x84, 0xd1, 0x80, 0x0e, 0xd9, 0x28, 0xc8, 0x27, 0x9c, 0x52,
	0xf4, 0x4b, 0xfe, 0x94, 0xd6, 0x2b, 0x05, 0xb0, 0xc1, 0x92, 0x94, 0x85, 0x01, 0x67, 0x43, 0x32,
	0x0d, 0xe3, 0x61, 0x34, 0x1d, 0xb7, 0x5e, 0x2a, 0x50, 0x93, 0x1b, 0x61, 0x8a, 0xf4, 0xb7, 0x18,
	0xd6, 0xb4, 0x7b, 0x68, 0x09, 0xaf, 0xc1, 0xc5, 0xe2, 0xfe, 0x03, 0x4d, 0x7f, 0x40, 0x8c, 0xdb,
	0xbb, 0x48, 0x39, 0x67, 0x89, 0x82, 0x35, 0xb8, 0xf3, 0xe7, 0x74, 0x12, 0xfa, 0xcf, 0x13, 0x6e,
	0x55, 0x90, 0xd2, 0xd9, 0x87, 0xe5, 0x51, 0xf9, 0xd6, 0xdb, 0x6a, 0x99, 0x14, 0x55, 0x26, 0x45,
	0x2d, 0xe8, 0x4e, 0x22, 0x52, 0x95, 0x6d, 0x7e, 0xf8, 0xfe, 0x75, 0x67, 0x47, 0xb9, 0xde, 0xdc,
	0xbd, 0xa2, 0xce, 0xa2, 0xa5, 0xce, 0x75, 0x57, 0xcb, 0x3f, 0x77, 0x06, 0xeb, 0x3c, 0x84, 0xaa,
	0xc8, 0xe5, 0x22, 0xe8, 0xb7, 0xb7, 0x5f, 0x2e, 0x2f, 0x86, 0x16, 0xa8, 0xce, 0x21, 0xd4, 0x98,
	0xf4, 0x6d, 0x01, 0xf6, 0xcd, 0xc9, 0xcf, 0xed, 0x02, 0x7b, 0xed, 0x14, 0x7b, 0xfe, 0x25, 0x54,
	0xb9, 0x70, 0x4f, 0xb9, 0x1d, 0x13, 0x1a, 0x79, 0xc6, 0xa4, 0x5b, 0xd9, 0xa2, 0x3e, 0xef, 0x5e,
	0x7f, 0x16, 0xe3, 0xd7, 0x3a, 0x55, 0x9e, 0xe6, 0xcc, 0xad, 0xe7, 0x19, 0x33, 0x66, 0x47, 0x3b,
	0x07, 0x80, 0x05, 0x6a, 0x24, 0xf4, 0x67, 0xc0, 0xab, 0xe7, 0x80, 0x16, 0xcb, 0xb2, 0x60, 0xcc,
	0x24, 0xf2, 0xc5, 0xc9, 0xa7, 0x79, 0x24, 0xca, 0x33, 0x56, 0xb4, 0x94, 0xdc, 0xbd, 0x9b, 0x80,
	0xc3, 0xf8, 0x58, 0x62, 0x66, 0xd7, 0xdb, 0x5b, 0x17, 0xd9, 0xd4, 0x4e, 0x3f, 0x02, 0x03, 0x41,
	0xff, 0xa1, 0x28, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x58, 0xb5, 0x74, 0x00, 0x33, 0x04, 0x00,
	0x00,
}
