load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")

package(default_visibility = ["//visibility:public"])

go_proto_library(
    name = "type_annotation_go_proto",
    importpath = "github.com/apstndb/go-zetasql-genproto/zetasql/public/proto/type_annotationpb",
    protos = ["@com_google_zetasql//zetasql/public/proto:type_annotation_proto"],
)
