// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/resolved_ast/resolved_ast_enums.proto

package resolved_ast

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResolvedSubqueryExprEnums_SubqueryType int32

const (
	ResolvedSubqueryExprEnums_SCALAR ResolvedSubqueryExprEnums_SubqueryType = 0
	ResolvedSubqueryExprEnums_ARRAY  ResolvedSubqueryExprEnums_SubqueryType = 1
	ResolvedSubqueryExprEnums_EXISTS ResolvedSubqueryExprEnums_SubqueryType = 2
	ResolvedSubqueryExprEnums_IN     ResolvedSubqueryExprEnums_SubqueryType = 3
)

var ResolvedSubqueryExprEnums_SubqueryType_name = map[int32]string{
	0: "SCALAR",
	1: "ARRAY",
	2: "EXISTS",
	3: "IN",
}

var ResolvedSubqueryExprEnums_SubqueryType_value = map[string]int32{
	"SCALAR": 0,
	"ARRAY":  1,
	"EXISTS": 2,
	"IN":     3,
}

func (x ResolvedSubqueryExprEnums_SubqueryType) Enum() *ResolvedSubqueryExprEnums_SubqueryType {
	p := new(ResolvedSubqueryExprEnums_SubqueryType)
	*p = x
	return p
}

func (x ResolvedSubqueryExprEnums_SubqueryType) String() string {
	return proto.EnumName(ResolvedSubqueryExprEnums_SubqueryType_name, int32(x))
}

func (x *ResolvedSubqueryExprEnums_SubqueryType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedSubqueryExprEnums_SubqueryType_value, data, "ResolvedSubqueryExprEnums_SubqueryType")
	if err != nil {
		return err
	}
	*x = ResolvedSubqueryExprEnums_SubqueryType(value)
	return nil
}

func (ResolvedSubqueryExprEnums_SubqueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{0, 0}
}

type ResolvedJoinScanEnums_JoinType int32

const (
	ResolvedJoinScanEnums_INNER ResolvedJoinScanEnums_JoinType = 0
	ResolvedJoinScanEnums_LEFT  ResolvedJoinScanEnums_JoinType = 1
	ResolvedJoinScanEnums_RIGHT ResolvedJoinScanEnums_JoinType = 2
	ResolvedJoinScanEnums_FULL  ResolvedJoinScanEnums_JoinType = 3
)

var ResolvedJoinScanEnums_JoinType_name = map[int32]string{
	0: "INNER",
	1: "LEFT",
	2: "RIGHT",
	3: "FULL",
}

var ResolvedJoinScanEnums_JoinType_value = map[string]int32{
	"INNER": 0,
	"LEFT":  1,
	"RIGHT": 2,
	"FULL":  3,
}

func (x ResolvedJoinScanEnums_JoinType) Enum() *ResolvedJoinScanEnums_JoinType {
	p := new(ResolvedJoinScanEnums_JoinType)
	*p = x
	return p
}

func (x ResolvedJoinScanEnums_JoinType) String() string {
	return proto.EnumName(ResolvedJoinScanEnums_JoinType_name, int32(x))
}

func (x *ResolvedJoinScanEnums_JoinType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedJoinScanEnums_JoinType_value, data, "ResolvedJoinScanEnums_JoinType")
	if err != nil {
		return err
	}
	*x = ResolvedJoinScanEnums_JoinType(value)
	return nil
}

func (ResolvedJoinScanEnums_JoinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{1, 0}
}

type ResolvedSetOperationScanEnums_SetOperationType int32

const (
	ResolvedSetOperationScanEnums_UNION_ALL          ResolvedSetOperationScanEnums_SetOperationType = 0
	ResolvedSetOperationScanEnums_UNION_DISTINCT     ResolvedSetOperationScanEnums_SetOperationType = 1
	ResolvedSetOperationScanEnums_INTERSECT_ALL      ResolvedSetOperationScanEnums_SetOperationType = 2
	ResolvedSetOperationScanEnums_INTERSECT_DISTINCT ResolvedSetOperationScanEnums_SetOperationType = 3
	ResolvedSetOperationScanEnums_EXCEPT_ALL         ResolvedSetOperationScanEnums_SetOperationType = 4
	ResolvedSetOperationScanEnums_EXCEPT_DISTINCT    ResolvedSetOperationScanEnums_SetOperationType = 5
)

var ResolvedSetOperationScanEnums_SetOperationType_name = map[int32]string{
	0: "UNION_ALL",
	1: "UNION_DISTINCT",
	2: "INTERSECT_ALL",
	3: "INTERSECT_DISTINCT",
	4: "EXCEPT_ALL",
	5: "EXCEPT_DISTINCT",
}

var ResolvedSetOperationScanEnums_SetOperationType_value = map[string]int32{
	"UNION_ALL":          0,
	"UNION_DISTINCT":     1,
	"INTERSECT_ALL":      2,
	"INTERSECT_DISTINCT": 3,
	"EXCEPT_ALL":         4,
	"EXCEPT_DISTINCT":    5,
}

func (x ResolvedSetOperationScanEnums_SetOperationType) Enum() *ResolvedSetOperationScanEnums_SetOperationType {
	p := new(ResolvedSetOperationScanEnums_SetOperationType)
	*p = x
	return p
}

func (x ResolvedSetOperationScanEnums_SetOperationType) String() string {
	return proto.EnumName(ResolvedSetOperationScanEnums_SetOperationType_name, int32(x))
}

func (x *ResolvedSetOperationScanEnums_SetOperationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedSetOperationScanEnums_SetOperationType_value, data, "ResolvedSetOperationScanEnums_SetOperationType")
	if err != nil {
		return err
	}
	*x = ResolvedSetOperationScanEnums_SetOperationType(value)
	return nil
}

func (ResolvedSetOperationScanEnums_SetOperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{2, 0}
}

type ResolvedRecursiveScanEnums_RecursiveSetOperationType int32

const (
	ResolvedRecursiveScanEnums_UNION_ALL      ResolvedRecursiveScanEnums_RecursiveSetOperationType = 0
	ResolvedRecursiveScanEnums_UNION_DISTINCT ResolvedRecursiveScanEnums_RecursiveSetOperationType = 1
)

var ResolvedRecursiveScanEnums_RecursiveSetOperationType_name = map[int32]string{
	0: "UNION_ALL",
	1: "UNION_DISTINCT",
}

var ResolvedRecursiveScanEnums_RecursiveSetOperationType_value = map[string]int32{
	"UNION_ALL":      0,
	"UNION_DISTINCT": 1,
}

func (x ResolvedRecursiveScanEnums_RecursiveSetOperationType) Enum() *ResolvedRecursiveScanEnums_RecursiveSetOperationType {
	p := new(ResolvedRecursiveScanEnums_RecursiveSetOperationType)
	*p = x
	return p
}

func (x ResolvedRecursiveScanEnums_RecursiveSetOperationType) String() string {
	return proto.EnumName(ResolvedRecursiveScanEnums_RecursiveSetOperationType_name, int32(x))
}

func (x *ResolvedRecursiveScanEnums_RecursiveSetOperationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedRecursiveScanEnums_RecursiveSetOperationType_value, data, "ResolvedRecursiveScanEnums_RecursiveSetOperationType")
	if err != nil {
		return err
	}
	*x = ResolvedRecursiveScanEnums_RecursiveSetOperationType(value)
	return nil
}

func (ResolvedRecursiveScanEnums_RecursiveSetOperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{3, 0}
}

type ResolvedSampleScanEnums_SampleUnit int32

const (
	ResolvedSampleScanEnums_ROWS    ResolvedSampleScanEnums_SampleUnit = 0
	ResolvedSampleScanEnums_PERCENT ResolvedSampleScanEnums_SampleUnit = 1
)

var ResolvedSampleScanEnums_SampleUnit_name = map[int32]string{
	0: "ROWS",
	1: "PERCENT",
}

var ResolvedSampleScanEnums_SampleUnit_value = map[string]int32{
	"ROWS":    0,
	"PERCENT": 1,
}

func (x ResolvedSampleScanEnums_SampleUnit) Enum() *ResolvedSampleScanEnums_SampleUnit {
	p := new(ResolvedSampleScanEnums_SampleUnit)
	*p = x
	return p
}

func (x ResolvedSampleScanEnums_SampleUnit) String() string {
	return proto.EnumName(ResolvedSampleScanEnums_SampleUnit_name, int32(x))
}

func (x *ResolvedSampleScanEnums_SampleUnit) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedSampleScanEnums_SampleUnit_value, data, "ResolvedSampleScanEnums_SampleUnit")
	if err != nil {
		return err
	}
	*x = ResolvedSampleScanEnums_SampleUnit(value)
	return nil
}

func (ResolvedSampleScanEnums_SampleUnit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{4, 0}
}

type ResolvedOrderByItemEnums_NullOrderMode int32

const (
	ResolvedOrderByItemEnums_ORDER_UNSPECIFIED ResolvedOrderByItemEnums_NullOrderMode = 0
	ResolvedOrderByItemEnums_NULLS_FIRST       ResolvedOrderByItemEnums_NullOrderMode = 1
	ResolvedOrderByItemEnums_NULLS_LAST        ResolvedOrderByItemEnums_NullOrderMode = 2
)

var ResolvedOrderByItemEnums_NullOrderMode_name = map[int32]string{
	0: "ORDER_UNSPECIFIED",
	1: "NULLS_FIRST",
	2: "NULLS_LAST",
}

var ResolvedOrderByItemEnums_NullOrderMode_value = map[string]int32{
	"ORDER_UNSPECIFIED": 0,
	"NULLS_FIRST":       1,
	"NULLS_LAST":        2,
}

func (x ResolvedOrderByItemEnums_NullOrderMode) Enum() *ResolvedOrderByItemEnums_NullOrderMode {
	p := new(ResolvedOrderByItemEnums_NullOrderMode)
	*p = x
	return p
}

func (x ResolvedOrderByItemEnums_NullOrderMode) String() string {
	return proto.EnumName(ResolvedOrderByItemEnums_NullOrderMode_name, int32(x))
}

func (x *ResolvedOrderByItemEnums_NullOrderMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedOrderByItemEnums_NullOrderMode_value, data, "ResolvedOrderByItemEnums_NullOrderMode")
	if err != nil {
		return err
	}
	*x = ResolvedOrderByItemEnums_NullOrderMode(value)
	return nil
}

func (ResolvedOrderByItemEnums_NullOrderMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{5, 0}
}

type ResolvedCreateStatementEnums_CreateScope int32

const (
	ResolvedCreateStatementEnums_CREATE_DEFAULT_SCOPE ResolvedCreateStatementEnums_CreateScope = 0
	ResolvedCreateStatementEnums_CREATE_PRIVATE       ResolvedCreateStatementEnums_CreateScope = 1
	ResolvedCreateStatementEnums_CREATE_PUBLIC        ResolvedCreateStatementEnums_CreateScope = 2
	ResolvedCreateStatementEnums_CREATE_TEMP          ResolvedCreateStatementEnums_CreateScope = 3
)

var ResolvedCreateStatementEnums_CreateScope_name = map[int32]string{
	0: "CREATE_DEFAULT_SCOPE",
	1: "CREATE_PRIVATE",
	2: "CREATE_PUBLIC",
	3: "CREATE_TEMP",
}

var ResolvedCreateStatementEnums_CreateScope_value = map[string]int32{
	"CREATE_DEFAULT_SCOPE": 0,
	"CREATE_PRIVATE":       1,
	"CREATE_PUBLIC":        2,
	"CREATE_TEMP":          3,
}

func (x ResolvedCreateStatementEnums_CreateScope) Enum() *ResolvedCreateStatementEnums_CreateScope {
	p := new(ResolvedCreateStatementEnums_CreateScope)
	*p = x
	return p
}

func (x ResolvedCreateStatementEnums_CreateScope) String() string {
	return proto.EnumName(ResolvedCreateStatementEnums_CreateScope_name, int32(x))
}

func (x *ResolvedCreateStatementEnums_CreateScope) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedCreateStatementEnums_CreateScope_value, data, "ResolvedCreateStatementEnums_CreateScope")
	if err != nil {
		return err
	}
	*x = ResolvedCreateStatementEnums_CreateScope(value)
	return nil
}

func (ResolvedCreateStatementEnums_CreateScope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{6, 0}
}

type ResolvedCreateStatementEnums_CreateMode int32

const (
	ResolvedCreateStatementEnums_CREATE_DEFAULT       ResolvedCreateStatementEnums_CreateMode = 0
	ResolvedCreateStatementEnums_CREATE_OR_REPLACE    ResolvedCreateStatementEnums_CreateMode = 1
	ResolvedCreateStatementEnums_CREATE_IF_NOT_EXISTS ResolvedCreateStatementEnums_CreateMode = 2
)

var ResolvedCreateStatementEnums_CreateMode_name = map[int32]string{
	0: "CREATE_DEFAULT",
	1: "CREATE_OR_REPLACE",
	2: "CREATE_IF_NOT_EXISTS",
}

var ResolvedCreateStatementEnums_CreateMode_value = map[string]int32{
	"CREATE_DEFAULT":       0,
	"CREATE_OR_REPLACE":    1,
	"CREATE_IF_NOT_EXISTS": 2,
}

func (x ResolvedCreateStatementEnums_CreateMode) Enum() *ResolvedCreateStatementEnums_CreateMode {
	p := new(ResolvedCreateStatementEnums_CreateMode)
	*p = x
	return p
}

func (x ResolvedCreateStatementEnums_CreateMode) String() string {
	return proto.EnumName(ResolvedCreateStatementEnums_CreateMode_name, int32(x))
}

func (x *ResolvedCreateStatementEnums_CreateMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedCreateStatementEnums_CreateMode_value, data, "ResolvedCreateStatementEnums_CreateMode")
	if err != nil {
		return err
	}
	*x = ResolvedCreateStatementEnums_CreateMode(value)
	return nil
}

func (ResolvedCreateStatementEnums_CreateMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{6, 1}
}

type ResolvedCreateStatementEnums_SqlSecurity int32

const (
	ResolvedCreateStatementEnums_SQL_SECURITY_UNSPECIFIED ResolvedCreateStatementEnums_SqlSecurity = 0
	ResolvedCreateStatementEnums_SQL_SECURITY_DEFINER     ResolvedCreateStatementEnums_SqlSecurity = 1
	ResolvedCreateStatementEnums_SQL_SECURITY_INVOKER     ResolvedCreateStatementEnums_SqlSecurity = 2
)

var ResolvedCreateStatementEnums_SqlSecurity_name = map[int32]string{
	0: "SQL_SECURITY_UNSPECIFIED",
	1: "SQL_SECURITY_DEFINER",
	2: "SQL_SECURITY_INVOKER",
}

var ResolvedCreateStatementEnums_SqlSecurity_value = map[string]int32{
	"SQL_SECURITY_UNSPECIFIED": 0,
	"SQL_SECURITY_DEFINER":     1,
	"SQL_SECURITY_INVOKER":     2,
}

func (x ResolvedCreateStatementEnums_SqlSecurity) Enum() *ResolvedCreateStatementEnums_SqlSecurity {
	p := new(ResolvedCreateStatementEnums_SqlSecurity)
	*p = x
	return p
}

func (x ResolvedCreateStatementEnums_SqlSecurity) String() string {
	return proto.EnumName(ResolvedCreateStatementEnums_SqlSecurity_name, int32(x))
}

func (x *ResolvedCreateStatementEnums_SqlSecurity) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedCreateStatementEnums_SqlSecurity_value, data, "ResolvedCreateStatementEnums_SqlSecurity")
	if err != nil {
		return err
	}
	*x = ResolvedCreateStatementEnums_SqlSecurity(value)
	return nil
}

func (ResolvedCreateStatementEnums_SqlSecurity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{6, 2}
}

type ResolvedCreateStatementEnums_DeterminismLevel int32

const (
	ResolvedCreateStatementEnums_DETERMINISM_UNSPECIFIED       ResolvedCreateStatementEnums_DeterminismLevel = 0
	ResolvedCreateStatementEnums_DETERMINISM_DETERMINISTIC     ResolvedCreateStatementEnums_DeterminismLevel = 1
	ResolvedCreateStatementEnums_DETERMINISM_NOT_DETERMINISTIC ResolvedCreateStatementEnums_DeterminismLevel = 2
	ResolvedCreateStatementEnums_DETERMINISM_IMMUTABLE         ResolvedCreateStatementEnums_DeterminismLevel = 3
	ResolvedCreateStatementEnums_DETERMINISM_STABLE            ResolvedCreateStatementEnums_DeterminismLevel = 4
	ResolvedCreateStatementEnums_DETERMINISM_VOLATILE          ResolvedCreateStatementEnums_DeterminismLevel = 5
)

var ResolvedCreateStatementEnums_DeterminismLevel_name = map[int32]string{
	0: "DETERMINISM_UNSPECIFIED",
	1: "DETERMINISM_DETERMINISTIC",
	2: "DETERMINISM_NOT_DETERMINISTIC",
	3: "DETERMINISM_IMMUTABLE",
	4: "DETERMINISM_STABLE",
	5: "DETERMINISM_VOLATILE",
}

var ResolvedCreateStatementEnums_DeterminismLevel_value = map[string]int32{
	"DETERMINISM_UNSPECIFIED":       0,
	"DETERMINISM_DETERMINISTIC":     1,
	"DETERMINISM_NOT_DETERMINISTIC": 2,
	"DETERMINISM_IMMUTABLE":         3,
	"DETERMINISM_STABLE":            4,
	"DETERMINISM_VOLATILE":          5,
}

func (x ResolvedCreateStatementEnums_DeterminismLevel) Enum() *ResolvedCreateStatementEnums_DeterminismLevel {
	p := new(ResolvedCreateStatementEnums_DeterminismLevel)
	*p = x
	return p
}

func (x ResolvedCreateStatementEnums_DeterminismLevel) String() string {
	return proto.EnumName(ResolvedCreateStatementEnums_DeterminismLevel_name, int32(x))
}

func (x *ResolvedCreateStatementEnums_DeterminismLevel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedCreateStatementEnums_DeterminismLevel_value, data, "ResolvedCreateStatementEnums_DeterminismLevel")
	if err != nil {
		return err
	}
	*x = ResolvedCreateStatementEnums_DeterminismLevel(value)
	return nil
}

func (ResolvedCreateStatementEnums_DeterminismLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{6, 3}
}

type ResolvedDropStmtEnums_DropMode int32

const (
	ResolvedDropStmtEnums_DROP_MODE_UNSPECIFIED ResolvedDropStmtEnums_DropMode = 0
	ResolvedDropStmtEnums_RESTRICT              ResolvedDropStmtEnums_DropMode = 1
	ResolvedDropStmtEnums_CASCADE               ResolvedDropStmtEnums_DropMode = 2
)

var ResolvedDropStmtEnums_DropMode_name = map[int32]string{
	0: "DROP_MODE_UNSPECIFIED",
	1: "RESTRICT",
	2: "CASCADE",
}

var ResolvedDropStmtEnums_DropMode_value = map[string]int32{
	"DROP_MODE_UNSPECIFIED": 0,
	"RESTRICT":              1,
	"CASCADE":               2,
}

func (x ResolvedDropStmtEnums_DropMode) Enum() *ResolvedDropStmtEnums_DropMode {
	p := new(ResolvedDropStmtEnums_DropMode)
	*p = x
	return p
}

func (x ResolvedDropStmtEnums_DropMode) String() string {
	return proto.EnumName(ResolvedDropStmtEnums_DropMode_name, int32(x))
}

func (x *ResolvedDropStmtEnums_DropMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedDropStmtEnums_DropMode_value, data, "ResolvedDropStmtEnums_DropMode")
	if err != nil {
		return err
	}
	*x = ResolvedDropStmtEnums_DropMode(value)
	return nil
}

func (ResolvedDropStmtEnums_DropMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{7, 0}
}

type ResolvedBeginStmtEnums_ReadWriteMode int32

const (
	ResolvedBeginStmtEnums_MODE_UNSPECIFIED ResolvedBeginStmtEnums_ReadWriteMode = 0
	ResolvedBeginStmtEnums_MODE_READ_ONLY   ResolvedBeginStmtEnums_ReadWriteMode = 1
	ResolvedBeginStmtEnums_MODE_READ_WRITE  ResolvedBeginStmtEnums_ReadWriteMode = 2
)

var ResolvedBeginStmtEnums_ReadWriteMode_name = map[int32]string{
	0: "MODE_UNSPECIFIED",
	1: "MODE_READ_ONLY",
	2: "MODE_READ_WRITE",
}

var ResolvedBeginStmtEnums_ReadWriteMode_value = map[string]int32{
	"MODE_UNSPECIFIED": 0,
	"MODE_READ_ONLY":   1,
	"MODE_READ_WRITE":  2,
}

func (x ResolvedBeginStmtEnums_ReadWriteMode) Enum() *ResolvedBeginStmtEnums_ReadWriteMode {
	p := new(ResolvedBeginStmtEnums_ReadWriteMode)
	*p = x
	return p
}

func (x ResolvedBeginStmtEnums_ReadWriteMode) String() string {
	return proto.EnumName(ResolvedBeginStmtEnums_ReadWriteMode_name, int32(x))
}

func (x *ResolvedBeginStmtEnums_ReadWriteMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedBeginStmtEnums_ReadWriteMode_value, data, "ResolvedBeginStmtEnums_ReadWriteMode")
	if err != nil {
		return err
	}
	*x = ResolvedBeginStmtEnums_ReadWriteMode(value)
	return nil
}

func (ResolvedBeginStmtEnums_ReadWriteMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{8, 0}
}

type ResolvedWindowFrameEnums_FrameUnit int32

const (
	ResolvedWindowFrameEnums_ROWS  ResolvedWindowFrameEnums_FrameUnit = 0
	ResolvedWindowFrameEnums_RANGE ResolvedWindowFrameEnums_FrameUnit = 1
)

var ResolvedWindowFrameEnums_FrameUnit_name = map[int32]string{
	0: "ROWS",
	1: "RANGE",
}

var ResolvedWindowFrameEnums_FrameUnit_value = map[string]int32{
	"ROWS":  0,
	"RANGE": 1,
}

func (x ResolvedWindowFrameEnums_FrameUnit) Enum() *ResolvedWindowFrameEnums_FrameUnit {
	p := new(ResolvedWindowFrameEnums_FrameUnit)
	*p = x
	return p
}

func (x ResolvedWindowFrameEnums_FrameUnit) String() string {
	return proto.EnumName(ResolvedWindowFrameEnums_FrameUnit_name, int32(x))
}

func (x *ResolvedWindowFrameEnums_FrameUnit) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedWindowFrameEnums_FrameUnit_value, data, "ResolvedWindowFrameEnums_FrameUnit")
	if err != nil {
		return err
	}
	*x = ResolvedWindowFrameEnums_FrameUnit(value)
	return nil
}

func (ResolvedWindowFrameEnums_FrameUnit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{9, 0}
}

type ResolvedWindowFrameExprEnums_BoundaryType int32

const (
	ResolvedWindowFrameExprEnums_UNBOUNDED_PRECEDING ResolvedWindowFrameExprEnums_BoundaryType = 0
	ResolvedWindowFrameExprEnums_OFFSET_PRECEDING    ResolvedWindowFrameExprEnums_BoundaryType = 1
	ResolvedWindowFrameExprEnums_CURRENT_ROW         ResolvedWindowFrameExprEnums_BoundaryType = 2
	ResolvedWindowFrameExprEnums_OFFSET_FOLLOWING    ResolvedWindowFrameExprEnums_BoundaryType = 3
	ResolvedWindowFrameExprEnums_UNBOUNDED_FOLLOWING ResolvedWindowFrameExprEnums_BoundaryType = 4
)

var ResolvedWindowFrameExprEnums_BoundaryType_name = map[int32]string{
	0: "UNBOUNDED_PRECEDING",
	1: "OFFSET_PRECEDING",
	2: "CURRENT_ROW",
	3: "OFFSET_FOLLOWING",
	4: "UNBOUNDED_FOLLOWING",
}

var ResolvedWindowFrameExprEnums_BoundaryType_value = map[string]int32{
	"UNBOUNDED_PRECEDING": 0,
	"OFFSET_PRECEDING":    1,
	"CURRENT_ROW":         2,
	"OFFSET_FOLLOWING":    3,
	"UNBOUNDED_FOLLOWING": 4,
}

func (x ResolvedWindowFrameExprEnums_BoundaryType) Enum() *ResolvedWindowFrameExprEnums_BoundaryType {
	p := new(ResolvedWindowFrameExprEnums_BoundaryType)
	*p = x
	return p
}

func (x ResolvedWindowFrameExprEnums_BoundaryType) String() string {
	return proto.EnumName(ResolvedWindowFrameExprEnums_BoundaryType_name, int32(x))
}

func (x *ResolvedWindowFrameExprEnums_BoundaryType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedWindowFrameExprEnums_BoundaryType_value, data, "ResolvedWindowFrameExprEnums_BoundaryType")
	if err != nil {
		return err
	}
	*x = ResolvedWindowFrameExprEnums_BoundaryType(value)
	return nil
}

func (ResolvedWindowFrameExprEnums_BoundaryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{10, 0}
}

type ResolvedInsertStmtEnums_InsertMode int32

const (
	ResolvedInsertStmtEnums_OR_ERROR   ResolvedInsertStmtEnums_InsertMode = 0
	ResolvedInsertStmtEnums_OR_IGNORE  ResolvedInsertStmtEnums_InsertMode = 1
	ResolvedInsertStmtEnums_OR_REPLACE ResolvedInsertStmtEnums_InsertMode = 2
	ResolvedInsertStmtEnums_OR_UPDATE  ResolvedInsertStmtEnums_InsertMode = 3
)

var ResolvedInsertStmtEnums_InsertMode_name = map[int32]string{
	0: "OR_ERROR",
	1: "OR_IGNORE",
	2: "OR_REPLACE",
	3: "OR_UPDATE",
}

var ResolvedInsertStmtEnums_InsertMode_value = map[string]int32{
	"OR_ERROR":   0,
	"OR_IGNORE":  1,
	"OR_REPLACE": 2,
	"OR_UPDATE":  3,
}

func (x ResolvedInsertStmtEnums_InsertMode) Enum() *ResolvedInsertStmtEnums_InsertMode {
	p := new(ResolvedInsertStmtEnums_InsertMode)
	*p = x
	return p
}

func (x ResolvedInsertStmtEnums_InsertMode) String() string {
	return proto.EnumName(ResolvedInsertStmtEnums_InsertMode_name, int32(x))
}

func (x *ResolvedInsertStmtEnums_InsertMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedInsertStmtEnums_InsertMode_value, data, "ResolvedInsertStmtEnums_InsertMode")
	if err != nil {
		return err
	}
	*x = ResolvedInsertStmtEnums_InsertMode(value)
	return nil
}

func (ResolvedInsertStmtEnums_InsertMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{11, 0}
}

type ResolvedMergeWhenEnums_MatchType int32

const (
	ResolvedMergeWhenEnums_MATCHED               ResolvedMergeWhenEnums_MatchType = 0
	ResolvedMergeWhenEnums_NOT_MATCHED_BY_SOURCE ResolvedMergeWhenEnums_MatchType = 1
	ResolvedMergeWhenEnums_NOT_MATCHED_BY_TARGET ResolvedMergeWhenEnums_MatchType = 2
)

var ResolvedMergeWhenEnums_MatchType_name = map[int32]string{
	0: "MATCHED",
	1: "NOT_MATCHED_BY_SOURCE",
	2: "NOT_MATCHED_BY_TARGET",
}

var ResolvedMergeWhenEnums_MatchType_value = map[string]int32{
	"MATCHED":               0,
	"NOT_MATCHED_BY_SOURCE": 1,
	"NOT_MATCHED_BY_TARGET": 2,
}

func (x ResolvedMergeWhenEnums_MatchType) Enum() *ResolvedMergeWhenEnums_MatchType {
	p := new(ResolvedMergeWhenEnums_MatchType)
	*p = x
	return p
}

func (x ResolvedMergeWhenEnums_MatchType) String() string {
	return proto.EnumName(ResolvedMergeWhenEnums_MatchType_name, int32(x))
}

func (x *ResolvedMergeWhenEnums_MatchType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedMergeWhenEnums_MatchType_value, data, "ResolvedMergeWhenEnums_MatchType")
	if err != nil {
		return err
	}
	*x = ResolvedMergeWhenEnums_MatchType(value)
	return nil
}

func (ResolvedMergeWhenEnums_MatchType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{12, 0}
}

type ResolvedMergeWhenEnums_ActionType int32

const (
	ResolvedMergeWhenEnums_INSERT ResolvedMergeWhenEnums_ActionType = 0
	ResolvedMergeWhenEnums_UPDATE ResolvedMergeWhenEnums_ActionType = 1
	ResolvedMergeWhenEnums_DELETE ResolvedMergeWhenEnums_ActionType = 2
)

var ResolvedMergeWhenEnums_ActionType_name = map[int32]string{
	0: "INSERT",
	1: "UPDATE",
	2: "DELETE",
}

var ResolvedMergeWhenEnums_ActionType_value = map[string]int32{
	"INSERT": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x ResolvedMergeWhenEnums_ActionType) Enum() *ResolvedMergeWhenEnums_ActionType {
	p := new(ResolvedMergeWhenEnums_ActionType)
	*p = x
	return p
}

func (x ResolvedMergeWhenEnums_ActionType) String() string {
	return proto.EnumName(ResolvedMergeWhenEnums_ActionType_name, int32(x))
}

func (x *ResolvedMergeWhenEnums_ActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedMergeWhenEnums_ActionType_value, data, "ResolvedMergeWhenEnums_ActionType")
	if err != nil {
		return err
	}
	*x = ResolvedMergeWhenEnums_ActionType(value)
	return nil
}

func (ResolvedMergeWhenEnums_ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{12, 1}
}

type ResolvedArgumentDefEnums_ArgumentKind int32

const (
	ResolvedArgumentDefEnums_SCALAR        ResolvedArgumentDefEnums_ArgumentKind = 0
	ResolvedArgumentDefEnums_AGGREGATE     ResolvedArgumentDefEnums_ArgumentKind = 1
	ResolvedArgumentDefEnums_NOT_AGGREGATE ResolvedArgumentDefEnums_ArgumentKind = 2
)

var ResolvedArgumentDefEnums_ArgumentKind_name = map[int32]string{
	0: "SCALAR",
	1: "AGGREGATE",
	2: "NOT_AGGREGATE",
}

var ResolvedArgumentDefEnums_ArgumentKind_value = map[string]int32{
	"SCALAR":        0,
	"AGGREGATE":     1,
	"NOT_AGGREGATE": 2,
}

func (x ResolvedArgumentDefEnums_ArgumentKind) Enum() *ResolvedArgumentDefEnums_ArgumentKind {
	p := new(ResolvedArgumentDefEnums_ArgumentKind)
	*p = x
	return p
}

func (x ResolvedArgumentDefEnums_ArgumentKind) String() string {
	return proto.EnumName(ResolvedArgumentDefEnums_ArgumentKind_name, int32(x))
}

func (x *ResolvedArgumentDefEnums_ArgumentKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedArgumentDefEnums_ArgumentKind_value, data, "ResolvedArgumentDefEnums_ArgumentKind")
	if err != nil {
		return err
	}
	*x = ResolvedArgumentDefEnums_ArgumentKind(value)
	return nil
}

func (ResolvedArgumentDefEnums_ArgumentKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{13, 0}
}

type ResolvedFunctionCallBaseEnums_ErrorMode int32

const (
	ResolvedFunctionCallBaseEnums_DEFAULT_ERROR_MODE ResolvedFunctionCallBaseEnums_ErrorMode = 0
	ResolvedFunctionCallBaseEnums_SAFE_ERROR_MODE    ResolvedFunctionCallBaseEnums_ErrorMode = 1
)

var ResolvedFunctionCallBaseEnums_ErrorMode_name = map[int32]string{
	0: "DEFAULT_ERROR_MODE",
	1: "SAFE_ERROR_MODE",
}

var ResolvedFunctionCallBaseEnums_ErrorMode_value = map[string]int32{
	"DEFAULT_ERROR_MODE": 0,
	"SAFE_ERROR_MODE":    1,
}

func (x ResolvedFunctionCallBaseEnums_ErrorMode) Enum() *ResolvedFunctionCallBaseEnums_ErrorMode {
	p := new(ResolvedFunctionCallBaseEnums_ErrorMode)
	*p = x
	return p
}

func (x ResolvedFunctionCallBaseEnums_ErrorMode) String() string {
	return proto.EnumName(ResolvedFunctionCallBaseEnums_ErrorMode_name, int32(x))
}

func (x *ResolvedFunctionCallBaseEnums_ErrorMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedFunctionCallBaseEnums_ErrorMode_value, data, "ResolvedFunctionCallBaseEnums_ErrorMode")
	if err != nil {
		return err
	}
	*x = ResolvedFunctionCallBaseEnums_ErrorMode(value)
	return nil
}

func (ResolvedFunctionCallBaseEnums_ErrorMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{14, 0}
}

type ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier int32

const (
	ResolvedNonScalarFunctionCallBaseEnums_DEFAULT_NULL_HANDLING ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier = 0
	ResolvedNonScalarFunctionCallBaseEnums_IGNORE_NULLS          ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier = 1
	ResolvedNonScalarFunctionCallBaseEnums_RESPECT_NULLS         ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier = 2
)

var ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier_name = map[int32]string{
	0: "DEFAULT_NULL_HANDLING",
	1: "IGNORE_NULLS",
	2: "RESPECT_NULLS",
}

var ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier_value = map[string]int32{
	"DEFAULT_NULL_HANDLING": 0,
	"IGNORE_NULLS":          1,
	"RESPECT_NULLS":         2,
}

func (x ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier) Enum() *ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier {
	p := new(ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier)
	*p = x
	return p
}

func (x ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier) String() string {
	return proto.EnumName(ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier_name, int32(x))
}

func (x *ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier_value, data, "ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier")
	if err != nil {
		return err
	}
	*x = ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier(value)
	return nil
}

func (ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{15, 0}
}

type ResolvedAggregateHavingModifierEnums_HavingModifierKind int32

const (
	ResolvedAggregateHavingModifierEnums_INVALID ResolvedAggregateHavingModifierEnums_HavingModifierKind = 0
	ResolvedAggregateHavingModifierEnums_MAX     ResolvedAggregateHavingModifierEnums_HavingModifierKind = 1
	ResolvedAggregateHavingModifierEnums_MIN     ResolvedAggregateHavingModifierEnums_HavingModifierKind = 2
)

var ResolvedAggregateHavingModifierEnums_HavingModifierKind_name = map[int32]string{
	0: "INVALID",
	1: "MAX",
	2: "MIN",
}

var ResolvedAggregateHavingModifierEnums_HavingModifierKind_value = map[string]int32{
	"INVALID": 0,
	"MAX":     1,
	"MIN":     2,
}

func (x ResolvedAggregateHavingModifierEnums_HavingModifierKind) Enum() *ResolvedAggregateHavingModifierEnums_HavingModifierKind {
	p := new(ResolvedAggregateHavingModifierEnums_HavingModifierKind)
	*p = x
	return p
}

func (x ResolvedAggregateHavingModifierEnums_HavingModifierKind) String() string {
	return proto.EnumName(ResolvedAggregateHavingModifierEnums_HavingModifierKind_name, int32(x))
}

func (x *ResolvedAggregateHavingModifierEnums_HavingModifierKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedAggregateHavingModifierEnums_HavingModifierKind_value, data, "ResolvedAggregateHavingModifierEnums_HavingModifierKind")
	if err != nil {
		return err
	}
	*x = ResolvedAggregateHavingModifierEnums_HavingModifierKind(value)
	return nil
}

func (ResolvedAggregateHavingModifierEnums_HavingModifierKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{16, 0}
}

type ResolvedStatementEnums_ObjectAccess int32

const (
	ResolvedStatementEnums_NONE       ResolvedStatementEnums_ObjectAccess = 0
	ResolvedStatementEnums_READ       ResolvedStatementEnums_ObjectAccess = 1
	ResolvedStatementEnums_WRITE      ResolvedStatementEnums_ObjectAccess = 2
	ResolvedStatementEnums_READ_WRITE ResolvedStatementEnums_ObjectAccess = 3
)

var ResolvedStatementEnums_ObjectAccess_name = map[int32]string{
	0: "NONE",
	1: "READ",
	2: "WRITE",
	3: "READ_WRITE",
}

var ResolvedStatementEnums_ObjectAccess_value = map[string]int32{
	"NONE":       0,
	"READ":       1,
	"WRITE":      2,
	"READ_WRITE": 3,
}

func (x ResolvedStatementEnums_ObjectAccess) Enum() *ResolvedStatementEnums_ObjectAccess {
	p := new(ResolvedStatementEnums_ObjectAccess)
	*p = x
	return p
}

func (x ResolvedStatementEnums_ObjectAccess) String() string {
	return proto.EnumName(ResolvedStatementEnums_ObjectAccess_name, int32(x))
}

func (x *ResolvedStatementEnums_ObjectAccess) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedStatementEnums_ObjectAccess_value, data, "ResolvedStatementEnums_ObjectAccess")
	if err != nil {
		return err
	}
	*x = ResolvedStatementEnums_ObjectAccess(value)
	return nil
}

func (ResolvedStatementEnums_ObjectAccess) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{17, 0}
}

type ResolvedImportStmtEnums_ImportKind int32

const (
	ResolvedImportStmtEnums_MODULE                                     ResolvedImportStmtEnums_ImportKind = 0
	ResolvedImportStmtEnums_PROTO                                      ResolvedImportStmtEnums_ImportKind = 1
	ResolvedImportStmtEnums___ImportKind__switch_must_have_a_default__ ResolvedImportStmtEnums_ImportKind = -1
)

var ResolvedImportStmtEnums_ImportKind_name = map[int32]string{
	0:  "MODULE",
	1:  "PROTO",
	-1: "__ImportKind__switch_must_have_a_default__",
}

var ResolvedImportStmtEnums_ImportKind_value = map[string]int32{
	"MODULE": 0,
	"PROTO":  1,
	"__ImportKind__switch_must_have_a_default__": -1,
}

func (x ResolvedImportStmtEnums_ImportKind) Enum() *ResolvedImportStmtEnums_ImportKind {
	p := new(ResolvedImportStmtEnums_ImportKind)
	*p = x
	return p
}

func (x ResolvedImportStmtEnums_ImportKind) String() string {
	return proto.EnumName(ResolvedImportStmtEnums_ImportKind_name, int32(x))
}

func (x *ResolvedImportStmtEnums_ImportKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedImportStmtEnums_ImportKind_value, data, "ResolvedImportStmtEnums_ImportKind")
	if err != nil {
		return err
	}
	*x = ResolvedImportStmtEnums_ImportKind(value)
	return nil
}

func (ResolvedImportStmtEnums_ImportKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{18, 0}
}

type ResolvedForeignKeyEnums_MatchMode int32

const (
	ResolvedForeignKeyEnums_SIMPLE       ResolvedForeignKeyEnums_MatchMode = 0
	ResolvedForeignKeyEnums_FULL         ResolvedForeignKeyEnums_MatchMode = 1
	ResolvedForeignKeyEnums_NOT_DISTINCT ResolvedForeignKeyEnums_MatchMode = 2
)

var ResolvedForeignKeyEnums_MatchMode_name = map[int32]string{
	0: "SIMPLE",
	1: "FULL",
	2: "NOT_DISTINCT",
}

var ResolvedForeignKeyEnums_MatchMode_value = map[string]int32{
	"SIMPLE":       0,
	"FULL":         1,
	"NOT_DISTINCT": 2,
}

func (x ResolvedForeignKeyEnums_MatchMode) Enum() *ResolvedForeignKeyEnums_MatchMode {
	p := new(ResolvedForeignKeyEnums_MatchMode)
	*p = x
	return p
}

func (x ResolvedForeignKeyEnums_MatchMode) String() string {
	return proto.EnumName(ResolvedForeignKeyEnums_MatchMode_name, int32(x))
}

func (x *ResolvedForeignKeyEnums_MatchMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedForeignKeyEnums_MatchMode_value, data, "ResolvedForeignKeyEnums_MatchMode")
	if err != nil {
		return err
	}
	*x = ResolvedForeignKeyEnums_MatchMode(value)
	return nil
}

func (ResolvedForeignKeyEnums_MatchMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{19, 0}
}

type ResolvedForeignKeyEnums_ActionOperation int32

const (
	ResolvedForeignKeyEnums_NO_ACTION ResolvedForeignKeyEnums_ActionOperation = 0
	ResolvedForeignKeyEnums_RESTRICT  ResolvedForeignKeyEnums_ActionOperation = 1
	ResolvedForeignKeyEnums_CASCADE   ResolvedForeignKeyEnums_ActionOperation = 2
	ResolvedForeignKeyEnums_SET_NULL  ResolvedForeignKeyEnums_ActionOperation = 3
)

var ResolvedForeignKeyEnums_ActionOperation_name = map[int32]string{
	0: "NO_ACTION",
	1: "RESTRICT",
	2: "CASCADE",
	3: "SET_NULL",
}

var ResolvedForeignKeyEnums_ActionOperation_value = map[string]int32{
	"NO_ACTION": 0,
	"RESTRICT":  1,
	"CASCADE":   2,
	"SET_NULL":  3,
}

func (x ResolvedForeignKeyEnums_ActionOperation) Enum() *ResolvedForeignKeyEnums_ActionOperation {
	p := new(ResolvedForeignKeyEnums_ActionOperation)
	*p = x
	return p
}

func (x ResolvedForeignKeyEnums_ActionOperation) String() string {
	return proto.EnumName(ResolvedForeignKeyEnums_ActionOperation_name, int32(x))
}

func (x *ResolvedForeignKeyEnums_ActionOperation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedForeignKeyEnums_ActionOperation_value, data, "ResolvedForeignKeyEnums_ActionOperation")
	if err != nil {
		return err
	}
	*x = ResolvedForeignKeyEnums_ActionOperation(value)
	return nil
}

func (ResolvedForeignKeyEnums_ActionOperation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{19, 1}
}

type ResolvedSubqueryExprEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedSubqueryExprEnums) Reset()         { *m = ResolvedSubqueryExprEnums{} }
func (m *ResolvedSubqueryExprEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedSubqueryExprEnums) ProtoMessage()    {}
func (*ResolvedSubqueryExprEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{0}
}

func (m *ResolvedSubqueryExprEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedSubqueryExprEnums.Unmarshal(m, b)
}
func (m *ResolvedSubqueryExprEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedSubqueryExprEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedSubqueryExprEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedSubqueryExprEnums.Merge(m, src)
}
func (m *ResolvedSubqueryExprEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedSubqueryExprEnums.Size(m)
}
func (m *ResolvedSubqueryExprEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedSubqueryExprEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedSubqueryExprEnums proto.InternalMessageInfo

type ResolvedJoinScanEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedJoinScanEnums) Reset()         { *m = ResolvedJoinScanEnums{} }
func (m *ResolvedJoinScanEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedJoinScanEnums) ProtoMessage()    {}
func (*ResolvedJoinScanEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{1}
}

func (m *ResolvedJoinScanEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedJoinScanEnums.Unmarshal(m, b)
}
func (m *ResolvedJoinScanEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedJoinScanEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedJoinScanEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedJoinScanEnums.Merge(m, src)
}
func (m *ResolvedJoinScanEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedJoinScanEnums.Size(m)
}
func (m *ResolvedJoinScanEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedJoinScanEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedJoinScanEnums proto.InternalMessageInfo

type ResolvedSetOperationScanEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedSetOperationScanEnums) Reset()         { *m = ResolvedSetOperationScanEnums{} }
func (m *ResolvedSetOperationScanEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedSetOperationScanEnums) ProtoMessage()    {}
func (*ResolvedSetOperationScanEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{2}
}

func (m *ResolvedSetOperationScanEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedSetOperationScanEnums.Unmarshal(m, b)
}
func (m *ResolvedSetOperationScanEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedSetOperationScanEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedSetOperationScanEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedSetOperationScanEnums.Merge(m, src)
}
func (m *ResolvedSetOperationScanEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedSetOperationScanEnums.Size(m)
}
func (m *ResolvedSetOperationScanEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedSetOperationScanEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedSetOperationScanEnums proto.InternalMessageInfo

type ResolvedRecursiveScanEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedRecursiveScanEnums) Reset()         { *m = ResolvedRecursiveScanEnums{} }
func (m *ResolvedRecursiveScanEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedRecursiveScanEnums) ProtoMessage()    {}
func (*ResolvedRecursiveScanEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{3}
}

func (m *ResolvedRecursiveScanEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedRecursiveScanEnums.Unmarshal(m, b)
}
func (m *ResolvedRecursiveScanEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedRecursiveScanEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedRecursiveScanEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedRecursiveScanEnums.Merge(m, src)
}
func (m *ResolvedRecursiveScanEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedRecursiveScanEnums.Size(m)
}
func (m *ResolvedRecursiveScanEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedRecursiveScanEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedRecursiveScanEnums proto.InternalMessageInfo

type ResolvedSampleScanEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedSampleScanEnums) Reset()         { *m = ResolvedSampleScanEnums{} }
func (m *ResolvedSampleScanEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedSampleScanEnums) ProtoMessage()    {}
func (*ResolvedSampleScanEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{4}
}

func (m *ResolvedSampleScanEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedSampleScanEnums.Unmarshal(m, b)
}
func (m *ResolvedSampleScanEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedSampleScanEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedSampleScanEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedSampleScanEnums.Merge(m, src)
}
func (m *ResolvedSampleScanEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedSampleScanEnums.Size(m)
}
func (m *ResolvedSampleScanEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedSampleScanEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedSampleScanEnums proto.InternalMessageInfo

type ResolvedOrderByItemEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedOrderByItemEnums) Reset()         { *m = ResolvedOrderByItemEnums{} }
func (m *ResolvedOrderByItemEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedOrderByItemEnums) ProtoMessage()    {}
func (*ResolvedOrderByItemEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{5}
}

func (m *ResolvedOrderByItemEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedOrderByItemEnums.Unmarshal(m, b)
}
func (m *ResolvedOrderByItemEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedOrderByItemEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedOrderByItemEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedOrderByItemEnums.Merge(m, src)
}
func (m *ResolvedOrderByItemEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedOrderByItemEnums.Size(m)
}
func (m *ResolvedOrderByItemEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedOrderByItemEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedOrderByItemEnums proto.InternalMessageInfo

type ResolvedCreateStatementEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedCreateStatementEnums) Reset()         { *m = ResolvedCreateStatementEnums{} }
func (m *ResolvedCreateStatementEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedCreateStatementEnums) ProtoMessage()    {}
func (*ResolvedCreateStatementEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{6}
}

func (m *ResolvedCreateStatementEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedCreateStatementEnums.Unmarshal(m, b)
}
func (m *ResolvedCreateStatementEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedCreateStatementEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedCreateStatementEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedCreateStatementEnums.Merge(m, src)
}
func (m *ResolvedCreateStatementEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedCreateStatementEnums.Size(m)
}
func (m *ResolvedCreateStatementEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedCreateStatementEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedCreateStatementEnums proto.InternalMessageInfo

type ResolvedDropStmtEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedDropStmtEnums) Reset()         { *m = ResolvedDropStmtEnums{} }
func (m *ResolvedDropStmtEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedDropStmtEnums) ProtoMessage()    {}
func (*ResolvedDropStmtEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{7}
}

func (m *ResolvedDropStmtEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedDropStmtEnums.Unmarshal(m, b)
}
func (m *ResolvedDropStmtEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedDropStmtEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedDropStmtEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedDropStmtEnums.Merge(m, src)
}
func (m *ResolvedDropStmtEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedDropStmtEnums.Size(m)
}
func (m *ResolvedDropStmtEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedDropStmtEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedDropStmtEnums proto.InternalMessageInfo

type ResolvedBeginStmtEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedBeginStmtEnums) Reset()         { *m = ResolvedBeginStmtEnums{} }
func (m *ResolvedBeginStmtEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedBeginStmtEnums) ProtoMessage()    {}
func (*ResolvedBeginStmtEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{8}
}

func (m *ResolvedBeginStmtEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedBeginStmtEnums.Unmarshal(m, b)
}
func (m *ResolvedBeginStmtEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedBeginStmtEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedBeginStmtEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedBeginStmtEnums.Merge(m, src)
}
func (m *ResolvedBeginStmtEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedBeginStmtEnums.Size(m)
}
func (m *ResolvedBeginStmtEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedBeginStmtEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedBeginStmtEnums proto.InternalMessageInfo

type ResolvedWindowFrameEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedWindowFrameEnums) Reset()         { *m = ResolvedWindowFrameEnums{} }
func (m *ResolvedWindowFrameEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedWindowFrameEnums) ProtoMessage()    {}
func (*ResolvedWindowFrameEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{9}
}

func (m *ResolvedWindowFrameEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedWindowFrameEnums.Unmarshal(m, b)
}
func (m *ResolvedWindowFrameEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedWindowFrameEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedWindowFrameEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedWindowFrameEnums.Merge(m, src)
}
func (m *ResolvedWindowFrameEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedWindowFrameEnums.Size(m)
}
func (m *ResolvedWindowFrameEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedWindowFrameEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedWindowFrameEnums proto.InternalMessageInfo

type ResolvedWindowFrameExprEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedWindowFrameExprEnums) Reset()         { *m = ResolvedWindowFrameExprEnums{} }
func (m *ResolvedWindowFrameExprEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedWindowFrameExprEnums) ProtoMessage()    {}
func (*ResolvedWindowFrameExprEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{10}
}

func (m *ResolvedWindowFrameExprEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedWindowFrameExprEnums.Unmarshal(m, b)
}
func (m *ResolvedWindowFrameExprEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedWindowFrameExprEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedWindowFrameExprEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedWindowFrameExprEnums.Merge(m, src)
}
func (m *ResolvedWindowFrameExprEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedWindowFrameExprEnums.Size(m)
}
func (m *ResolvedWindowFrameExprEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedWindowFrameExprEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedWindowFrameExprEnums proto.InternalMessageInfo

type ResolvedInsertStmtEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedInsertStmtEnums) Reset()         { *m = ResolvedInsertStmtEnums{} }
func (m *ResolvedInsertStmtEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedInsertStmtEnums) ProtoMessage()    {}
func (*ResolvedInsertStmtEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{11}
}

func (m *ResolvedInsertStmtEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedInsertStmtEnums.Unmarshal(m, b)
}
func (m *ResolvedInsertStmtEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedInsertStmtEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedInsertStmtEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedInsertStmtEnums.Merge(m, src)
}
func (m *ResolvedInsertStmtEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedInsertStmtEnums.Size(m)
}
func (m *ResolvedInsertStmtEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedInsertStmtEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedInsertStmtEnums proto.InternalMessageInfo

type ResolvedMergeWhenEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedMergeWhenEnums) Reset()         { *m = ResolvedMergeWhenEnums{} }
func (m *ResolvedMergeWhenEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedMergeWhenEnums) ProtoMessage()    {}
func (*ResolvedMergeWhenEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{12}
}

func (m *ResolvedMergeWhenEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedMergeWhenEnums.Unmarshal(m, b)
}
func (m *ResolvedMergeWhenEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedMergeWhenEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedMergeWhenEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedMergeWhenEnums.Merge(m, src)
}
func (m *ResolvedMergeWhenEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedMergeWhenEnums.Size(m)
}
func (m *ResolvedMergeWhenEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedMergeWhenEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedMergeWhenEnums proto.InternalMessageInfo

type ResolvedArgumentDefEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedArgumentDefEnums) Reset()         { *m = ResolvedArgumentDefEnums{} }
func (m *ResolvedArgumentDefEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedArgumentDefEnums) ProtoMessage()    {}
func (*ResolvedArgumentDefEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{13}
}

func (m *ResolvedArgumentDefEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedArgumentDefEnums.Unmarshal(m, b)
}
func (m *ResolvedArgumentDefEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedArgumentDefEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedArgumentDefEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedArgumentDefEnums.Merge(m, src)
}
func (m *ResolvedArgumentDefEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedArgumentDefEnums.Size(m)
}
func (m *ResolvedArgumentDefEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedArgumentDefEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedArgumentDefEnums proto.InternalMessageInfo

type ResolvedFunctionCallBaseEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedFunctionCallBaseEnums) Reset()         { *m = ResolvedFunctionCallBaseEnums{} }
func (m *ResolvedFunctionCallBaseEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedFunctionCallBaseEnums) ProtoMessage()    {}
func (*ResolvedFunctionCallBaseEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{14}
}

func (m *ResolvedFunctionCallBaseEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedFunctionCallBaseEnums.Unmarshal(m, b)
}
func (m *ResolvedFunctionCallBaseEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedFunctionCallBaseEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedFunctionCallBaseEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedFunctionCallBaseEnums.Merge(m, src)
}
func (m *ResolvedFunctionCallBaseEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedFunctionCallBaseEnums.Size(m)
}
func (m *ResolvedFunctionCallBaseEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedFunctionCallBaseEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedFunctionCallBaseEnums proto.InternalMessageInfo

type ResolvedNonScalarFunctionCallBaseEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedNonScalarFunctionCallBaseEnums) Reset() {
	*m = ResolvedNonScalarFunctionCallBaseEnums{}
}
func (m *ResolvedNonScalarFunctionCallBaseEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedNonScalarFunctionCallBaseEnums) ProtoMessage()    {}
func (*ResolvedNonScalarFunctionCallBaseEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{15}
}

func (m *ResolvedNonScalarFunctionCallBaseEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedNonScalarFunctionCallBaseEnums.Unmarshal(m, b)
}
func (m *ResolvedNonScalarFunctionCallBaseEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedNonScalarFunctionCallBaseEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedNonScalarFunctionCallBaseEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedNonScalarFunctionCallBaseEnums.Merge(m, src)
}
func (m *ResolvedNonScalarFunctionCallBaseEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedNonScalarFunctionCallBaseEnums.Size(m)
}
func (m *ResolvedNonScalarFunctionCallBaseEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedNonScalarFunctionCallBaseEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedNonScalarFunctionCallBaseEnums proto.InternalMessageInfo

type ResolvedAggregateHavingModifierEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedAggregateHavingModifierEnums) Reset()         { *m = ResolvedAggregateHavingModifierEnums{} }
func (m *ResolvedAggregateHavingModifierEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedAggregateHavingModifierEnums) ProtoMessage()    {}
func (*ResolvedAggregateHavingModifierEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{16}
}

func (m *ResolvedAggregateHavingModifierEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedAggregateHavingModifierEnums.Unmarshal(m, b)
}
func (m *ResolvedAggregateHavingModifierEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedAggregateHavingModifierEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedAggregateHavingModifierEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedAggregateHavingModifierEnums.Merge(m, src)
}
func (m *ResolvedAggregateHavingModifierEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedAggregateHavingModifierEnums.Size(m)
}
func (m *ResolvedAggregateHavingModifierEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedAggregateHavingModifierEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedAggregateHavingModifierEnums proto.InternalMessageInfo

type ResolvedStatementEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedStatementEnums) Reset()         { *m = ResolvedStatementEnums{} }
func (m *ResolvedStatementEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedStatementEnums) ProtoMessage()    {}
func (*ResolvedStatementEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{17}
}

func (m *ResolvedStatementEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedStatementEnums.Unmarshal(m, b)
}
func (m *ResolvedStatementEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedStatementEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedStatementEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedStatementEnums.Merge(m, src)
}
func (m *ResolvedStatementEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedStatementEnums.Size(m)
}
func (m *ResolvedStatementEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedStatementEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedStatementEnums proto.InternalMessageInfo

type ResolvedImportStmtEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedImportStmtEnums) Reset()         { *m = ResolvedImportStmtEnums{} }
func (m *ResolvedImportStmtEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedImportStmtEnums) ProtoMessage()    {}
func (*ResolvedImportStmtEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{18}
}

func (m *ResolvedImportStmtEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedImportStmtEnums.Unmarshal(m, b)
}
func (m *ResolvedImportStmtEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedImportStmtEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedImportStmtEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedImportStmtEnums.Merge(m, src)
}
func (m *ResolvedImportStmtEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedImportStmtEnums.Size(m)
}
func (m *ResolvedImportStmtEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedImportStmtEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedImportStmtEnums proto.InternalMessageInfo

type ResolvedForeignKeyEnums struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolvedForeignKeyEnums) Reset()         { *m = ResolvedForeignKeyEnums{} }
func (m *ResolvedForeignKeyEnums) String() string { return proto.CompactTextString(m) }
func (*ResolvedForeignKeyEnums) ProtoMessage()    {}
func (*ResolvedForeignKeyEnums) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2d55ba04f2d4223, []int{19}
}

func (m *ResolvedForeignKeyEnums) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolvedForeignKeyEnums.Unmarshal(m, b)
}
func (m *ResolvedForeignKeyEnums) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolvedForeignKeyEnums.Marshal(b, m, deterministic)
}
func (m *ResolvedForeignKeyEnums) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolvedForeignKeyEnums.Merge(m, src)
}
func (m *ResolvedForeignKeyEnums) XXX_Size() int {
	return xxx_messageInfo_ResolvedForeignKeyEnums.Size(m)
}
func (m *ResolvedForeignKeyEnums) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolvedForeignKeyEnums.DiscardUnknown(m)
}

var xxx_messageInfo_ResolvedForeignKeyEnums proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("zetasql.ResolvedSubqueryExprEnums_SubqueryType", ResolvedSubqueryExprEnums_SubqueryType_name, ResolvedSubqueryExprEnums_SubqueryType_value)
	proto.RegisterEnum("zetasql.ResolvedJoinScanEnums_JoinType", ResolvedJoinScanEnums_JoinType_name, ResolvedJoinScanEnums_JoinType_value)
	proto.RegisterEnum("zetasql.ResolvedSetOperationScanEnums_SetOperationType", ResolvedSetOperationScanEnums_SetOperationType_name, ResolvedSetOperationScanEnums_SetOperationType_value)
	proto.RegisterEnum("zetasql.ResolvedRecursiveScanEnums_RecursiveSetOperationType", ResolvedRecursiveScanEnums_RecursiveSetOperationType_name, ResolvedRecursiveScanEnums_RecursiveSetOperationType_value)
	proto.RegisterEnum("zetasql.ResolvedSampleScanEnums_SampleUnit", ResolvedSampleScanEnums_SampleUnit_name, ResolvedSampleScanEnums_SampleUnit_value)
	proto.RegisterEnum("zetasql.ResolvedOrderByItemEnums_NullOrderMode", ResolvedOrderByItemEnums_NullOrderMode_name, ResolvedOrderByItemEnums_NullOrderMode_value)
	proto.RegisterEnum("zetasql.ResolvedCreateStatementEnums_CreateScope", ResolvedCreateStatementEnums_CreateScope_name, ResolvedCreateStatementEnums_CreateScope_value)
	proto.RegisterEnum("zetasql.ResolvedCreateStatementEnums_CreateMode", ResolvedCreateStatementEnums_CreateMode_name, ResolvedCreateStatementEnums_CreateMode_value)
	proto.RegisterEnum("zetasql.ResolvedCreateStatementEnums_SqlSecurity", ResolvedCreateStatementEnums_SqlSecurity_name, ResolvedCreateStatementEnums_SqlSecurity_value)
	proto.RegisterEnum("zetasql.ResolvedCreateStatementEnums_DeterminismLevel", ResolvedCreateStatementEnums_DeterminismLevel_name, ResolvedCreateStatementEnums_DeterminismLevel_value)
	proto.RegisterEnum("zetasql.ResolvedDropStmtEnums_DropMode", ResolvedDropStmtEnums_DropMode_name, ResolvedDropStmtEnums_DropMode_value)
	proto.RegisterEnum("zetasql.ResolvedBeginStmtEnums_ReadWriteMode", ResolvedBeginStmtEnums_ReadWriteMode_name, ResolvedBeginStmtEnums_ReadWriteMode_value)
	proto.RegisterEnum("zetasql.ResolvedWindowFrameEnums_FrameUnit", ResolvedWindowFrameEnums_FrameUnit_name, ResolvedWindowFrameEnums_FrameUnit_value)
	proto.RegisterEnum("zetasql.ResolvedWindowFrameExprEnums_BoundaryType", ResolvedWindowFrameExprEnums_BoundaryType_name, ResolvedWindowFrameExprEnums_BoundaryType_value)
	proto.RegisterEnum("zetasql.ResolvedInsertStmtEnums_InsertMode", ResolvedInsertStmtEnums_InsertMode_name, ResolvedInsertStmtEnums_InsertMode_value)
	proto.RegisterEnum("zetasql.ResolvedMergeWhenEnums_MatchType", ResolvedMergeWhenEnums_MatchType_name, ResolvedMergeWhenEnums_MatchType_value)
	proto.RegisterEnum("zetasql.ResolvedMergeWhenEnums_ActionType", ResolvedMergeWhenEnums_ActionType_name, ResolvedMergeWhenEnums_ActionType_value)
	proto.RegisterEnum("zetasql.ResolvedArgumentDefEnums_ArgumentKind", ResolvedArgumentDefEnums_ArgumentKind_name, ResolvedArgumentDefEnums_ArgumentKind_value)
	proto.RegisterEnum("zetasql.ResolvedFunctionCallBaseEnums_ErrorMode", ResolvedFunctionCallBaseEnums_ErrorMode_name, ResolvedFunctionCallBaseEnums_ErrorMode_value)
	proto.RegisterEnum("zetasql.ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier", ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier_name, ResolvedNonScalarFunctionCallBaseEnums_NullHandlingModifier_value)
	proto.RegisterEnum("zetasql.ResolvedAggregateHavingModifierEnums_HavingModifierKind", ResolvedAggregateHavingModifierEnums_HavingModifierKind_name, ResolvedAggregateHavingModifierEnums_HavingModifierKind_value)
	proto.RegisterEnum("zetasql.ResolvedStatementEnums_ObjectAccess", ResolvedStatementEnums_ObjectAccess_name, ResolvedStatementEnums_ObjectAccess_value)
	proto.RegisterEnum("zetasql.ResolvedImportStmtEnums_ImportKind", ResolvedImportStmtEnums_ImportKind_name, ResolvedImportStmtEnums_ImportKind_value)
	proto.RegisterEnum("zetasql.ResolvedForeignKeyEnums_MatchMode", ResolvedForeignKeyEnums_MatchMode_name, ResolvedForeignKeyEnums_MatchMode_value)
	proto.RegisterEnum("zetasql.ResolvedForeignKeyEnums_ActionOperation", ResolvedForeignKeyEnums_ActionOperation_name, ResolvedForeignKeyEnums_ActionOperation_value)
	proto.RegisterType((*ResolvedSubqueryExprEnums)(nil), "zetasql.ResolvedSubqueryExprEnums")
	proto.RegisterType((*ResolvedJoinScanEnums)(nil), "zetasql.ResolvedJoinScanEnums")
	proto.RegisterType((*ResolvedSetOperationScanEnums)(nil), "zetasql.ResolvedSetOperationScanEnums")
	proto.RegisterType((*ResolvedRecursiveScanEnums)(nil), "zetasql.ResolvedRecursiveScanEnums")
	proto.RegisterType((*ResolvedSampleScanEnums)(nil), "zetasql.ResolvedSampleScanEnums")
	proto.RegisterType((*ResolvedOrderByItemEnums)(nil), "zetasql.ResolvedOrderByItemEnums")
	proto.RegisterType((*ResolvedCreateStatementEnums)(nil), "zetasql.ResolvedCreateStatementEnums")
	proto.RegisterType((*ResolvedDropStmtEnums)(nil), "zetasql.ResolvedDropStmtEnums")
	proto.RegisterType((*ResolvedBeginStmtEnums)(nil), "zetasql.ResolvedBeginStmtEnums")
	proto.RegisterType((*ResolvedWindowFrameEnums)(nil), "zetasql.ResolvedWindowFrameEnums")
	proto.RegisterType((*ResolvedWindowFrameExprEnums)(nil), "zetasql.ResolvedWindowFrameExprEnums")
	proto.RegisterType((*ResolvedInsertStmtEnums)(nil), "zetasql.ResolvedInsertStmtEnums")
	proto.RegisterType((*ResolvedMergeWhenEnums)(nil), "zetasql.ResolvedMergeWhenEnums")
	proto.RegisterType((*ResolvedArgumentDefEnums)(nil), "zetasql.ResolvedArgumentDefEnums")
	proto.RegisterType((*ResolvedFunctionCallBaseEnums)(nil), "zetasql.ResolvedFunctionCallBaseEnums")
	proto.RegisterType((*ResolvedNonScalarFunctionCallBaseEnums)(nil), "zetasql.ResolvedNonScalarFunctionCallBaseEnums")
	proto.RegisterType((*ResolvedAggregateHavingModifierEnums)(nil), "zetasql.ResolvedAggregateHavingModifierEnums")
	proto.RegisterType((*ResolvedStatementEnums)(nil), "zetasql.ResolvedStatementEnums")
	proto.RegisterType((*ResolvedImportStmtEnums)(nil), "zetasql.ResolvedImportStmtEnums")
	proto.RegisterType((*ResolvedForeignKeyEnums)(nil), "zetasql.ResolvedForeignKeyEnums")
}

func init() {
	proto.RegisterFile("zetasql/resolved_ast/resolved_ast_enums.proto", fileDescriptor_c2d55ba04f2d4223)
}

var fileDescriptor_c2d55ba04f2d4223 = []byte{
	// 1387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x6d, 0x6f, 0xe3, 0xc4,
	0x16, 0xae, 0x93, 0xbe, 0xe5, 0xf4, 0x6d, 0xd6, 0xdb, 0x6e, 0xdb, 0x7b, 0x77, 0xaf, 0xee, 0xf5,
	0x45, 0x20, 0x21, 0xd1, 0x45, 0x02, 0x09, 0x90, 0x96, 0x15, 0x8e, 0x3d, 0x49, 0x87, 0x75, 0xc6,
	0xd9, 0x19, 0xbb, 0x69, 0x97, 0x95, 0x46, 0x6e, 0x32, 0x9b, 0x1a, 0x25, 0x76, 0xd6, 0x71, 0xba,
	0x14, 0x09, 0x89, 0x2f, 0xfc, 0x08, 0x90, 0xf8, 0xcc, 0xbf, 0xe0, 0x57, 0xf1, 0x1d, 0x34, 0x7e,
	0x89, 0xdd, 0xee, 0x0a, 0x89, 0x7c, 0xca, 0x3c, 0xe7, 0xf8, 0xbc, 0x3f, 0x67, 0x06, 0x3e, 0xfa,
	0x5e, 0xa6, 0xc1, 0xfc, 0xf5, 0xe4, 0x71, 0x22, 0xe7, 0xf1, 0xe4, 0x5a, 0x8e, 0x44, 0x30, 0x4f,
	0x6f, 0x1d, 0x84, 0x8c, 0x16, 0xd3, 0xf9, 0xc9, 0x2c, 0x89, 0xd3, 0x58, 0xdf, 0x28, 0xd4, 0x8d,
	0x33, 0x38, 0x66, 0x85, 0x12, 0x5f, 0x5c, 0xbe, 0x5e, 0xc8, 0xe4, 0x06, 0x7f, 0x37, 0x4b, 0xb0,
	0xd2, 0x35, 0xbe, 0x80, 0xed, 0x12, 0xf4, 0x6e, 0x66, 0x52, 0x07, 0x58, 0xe7, 0x96, 0xe9, 0x98,
	0x0c, 0xad, 0xe8, 0x2d, 0x58, 0x33, 0x19, 0x33, 0x2f, 0x90, 0xa6, 0x60, 0x7c, 0x4e, 0xb8, 0xc7,
	0x51, 0x43, 0x5f, 0x87, 0x06, 0xa1, 0xa8, 0x69, 0xf4, 0xe0, 0xa0, 0xb4, 0xfb, 0x75, 0x1c, 0x46,
	0x7c, 0x18, 0x44, 0xb9, 0xcd, 0x4f, 0x61, 0x53, 0x01, 0x99, 0xbd, 0x16, 0xac, 0x11, 0x4a, 0xb1,
	0x32, 0xb7, 0x09, 0xab, 0x0e, 0xee, 0x78, 0x48, 0x53, 0x20, 0x23, 0xdd, 0x53, 0x0f, 0x35, 0x14,
	0xd8, 0xf1, 0x1d, 0x07, 0x35, 0x8d, 0xdf, 0x34, 0x78, 0xb4, 0x8c, 0x53, 0xa6, 0xee, 0x4c, 0x26,
	0x41, 0x1a, 0xc6, 0x35, 0xbb, 0x3f, 0x69, 0x80, 0xea, 0x92, 0xcc, 0xc1, 0x0e, 0xb4, 0x7c, 0x4a,
	0x5c, 0x2a, 0x4c, 0xc7, 0x41, 0x2b, 0xba, 0x0e, 0xbb, 0xf9, 0xd1, 0x26, 0xdc, 0x23, 0xd4, 0x52,
	0xee, 0xee, 0xc1, 0x0e, 0xa1, 0x1e, 0x66, 0x1c, 0x5b, 0x5e, 0xa6, 0xd6, 0xd0, 0x1f, 0x80, 0x5e,
	0x41, 0x4b, 0xd5, 0xa6, 0xbe, 0x0b, 0x80, 0xcf, 0x2d, 0xdc, 0xcf, 0xf5, 0x56, 0xf5, 0xfb, 0xb0,
	0x57, 0x9c, 0x97, 0x4a, 0x6b, 0xc6, 0x4b, 0xf8, 0x57, 0x19, 0x28, 0x93, 0xc3, 0x45, 0x32, 0x0f,
	0xaf, 0x65, 0x15, 0xe5, 0x53, 0x55, 0xee, 0x12, 0xfd, 0xe7, 0xd1, 0x1a, 0x4f, 0xe1, 0x70, 0x59,
	0x86, 0x60, 0x3a, 0x9b, 0xd4, 0x4c, 0xff, 0x1f, 0x20, 0x87, 0xfc, 0x28, 0x4c, 0x55, 0xe9, 0x98,
	0x3b, 0xe0, 0x68, 0x45, 0xdf, 0x82, 0x8d, 0x3e, 0x66, 0x16, 0xa6, 0xea, 0xfb, 0x21, 0x1c, 0x95,
	0xdf, 0xbb, 0xc9, 0x48, 0x26, 0xed, 0x1b, 0x92, 0xca, 0x69, 0x6e, 0xa0, 0x0b, 0x3b, 0x74, 0x31,
	0x99, 0x64, 0x78, 0x2f, 0x1e, 0x49, 0xfd, 0x00, 0xee, 0xb9, 0xcc, 0xc6, 0x4c, 0xf8, 0x94, 0xf7,
	0xb1, 0x45, 0x3a, 0x04, 0xdb, 0x68, 0x45, 0xdf, 0x83, 0x2d, 0xea, 0x3b, 0x0e, 0x17, 0x1d, 0xc2,
	0xb8, 0x2a, 0xe1, 0x2e, 0x40, 0x0e, 0x38, 0x26, 0xf7, 0x50, 0xc3, 0xf8, 0xa3, 0x09, 0x0f, 0x4b,
	0x2f, 0x56, 0x22, 0x83, 0x54, 0xf2, 0x34, 0x48, 0xe5, 0x54, 0x46, 0x69, 0xee, 0x49, 0xc0, 0x56,
	0x81, 0x0f, 0xe3, 0x99, 0xd4, 0x8f, 0x60, 0xdf, 0x62, 0xd8, 0xf4, 0xb0, 0xb0, 0x71, 0xc7, 0xf4,
	0x1d, 0x4f, 0x70, 0xcb, 0xed, 0xe3, 0xbc, 0x04, 0x85, 0xa4, 0xcf, 0xc8, 0x99, 0xe9, 0xe1, 0xbc,
	0x61, 0x25, 0xe6, 0xb7, 0x1d, 0x62, 0xa1, 0x86, 0x8a, 0xa8, 0x80, 0x3c, 0xdc, 0xeb, 0xa3, 0xa6,
	0xf1, 0x1c, 0x20, 0x77, 0x90, 0xe5, 0x51, 0x59, 0x29, 0xec, 0xa3, 0x15, 0x95, 0x5b, 0x81, 0xb9,
	0x4c, 0x30, 0xdc, 0x77, 0x4c, 0x4b, 0x19, 0xaf, 0x42, 0x21, 0x1d, 0x41, 0x5d, 0x4f, 0x94, 0x83,
	0xad, 0x62, 0xe6, 0xaf, 0x27, 0x5c, 0x35, 0x2f, 0x4c, 0x6f, 0xf4, 0x87, 0x70, 0xc4, 0x9f, 0x3b,
	0x82, 0x63, 0xcb, 0x67, 0xc4, 0xbb, 0xb8, 0x53, 0xa2, 0x23, 0xd8, 0xbf, 0x25, 0xb5, 0x71, 0x87,
	0xa8, 0x39, 0xd7, 0xde, 0x92, 0x10, 0x7a, 0xe6, 0x3e, 0xc3, 0x0c, 0x35, 0x8c, 0xdf, 0x35, 0x40,
	0xb6, 0x4c, 0x65, 0x32, 0x0d, 0xa3, 0x70, 0x3e, 0x75, 0xe4, 0xb5, 0x9c, 0xe8, 0xff, 0x86, 0x43,
	0x1b, 0x7b, 0x98, 0xf5, 0x08, 0x25, 0xbc, 0x77, 0xc7, 0xcb, 0x23, 0x38, 0xae, 0x0b, 0xab, 0xff,
	0x1e, 0xb1, 0x90, 0xa6, 0xff, 0x0f, 0x1e, 0xd5, 0xc5, 0x2a, 0x9b, 0xdb, 0x2a, 0x0d, 0xfd, 0x18,
	0x0e, 0xea, 0x2a, 0xa4, 0xd7, 0xf3, 0x3d, 0xb3, 0xed, 0x60, 0xd4, 0x54, 0x24, 0xa8, 0x8b, 0x78,
	0x8e, 0xaf, 0xaa, 0x04, 0xea, 0xf8, 0x99, 0xeb, 0x98, 0x1e, 0x71, 0x30, 0x5a, 0x33, 0x2e, 0x2a,
	0xca, 0xdb, 0x49, 0x3c, 0xe3, 0xe9, 0xb4, 0x68, 0xf7, 0x57, 0xb0, 0xa9, 0x80, 0xac, 0x17, 0xca,
	0x23, 0x73, 0xfb, 0xa2, 0xe7, 0xda, 0xf8, 0x4e, 0x3a, 0xdb, 0xb0, 0xc9, 0x30, 0xf7, 0x18, 0xc9,
	0x78, 0xb9, 0x05, 0x1b, 0x96, 0xc9, 0x2d, 0xd3, 0xc6, 0xa8, 0x61, 0x5c, 0xc1, 0x83, 0xd2, 0x74,
	0x5b, 0x8e, 0xc3, 0xa8, 0xb2, 0x4d, 0x61, 0x87, 0xc9, 0x60, 0x34, 0x48, 0xc2, 0xa2, 0xd9, 0xfb,
	0x80, 0xde, 0x61, 0x5b, 0x87, 0xdd, 0x0c, 0x65, 0xd8, 0xb4, 0x85, 0x4b, 0x1d, 0xb5, 0xb6, 0xee,
	0xc3, 0x5e, 0x85, 0x0d, 0x18, 0xf1, 0x94, 0xa7, 0x27, 0x15, 0x41, 0x06, 0x61, 0x34, 0x8a, 0xdf,
	0x74, 0x92, 0x60, 0x2a, 0x73, 0x5f, 0xff, 0x85, 0x56, 0x76, 0xba, 0x43, 0x30, 0xb5, 0xb0, 0x4c,
	0xda, 0xc5, 0x48, 0x33, 0x7e, 0xd5, 0xaa, 0xc9, 0xaf, 0x7f, 0xbe, 0xdc, 0xa8, 0x3f, 0xc0, 0x76,
	0x3b, 0x5e, 0x44, 0xa3, 0xa0, 0xd8, 0xa8, 0x87, 0x70, 0xdf, 0xa7, 0x6d, 0xd7, 0xa7, 0x36, 0xb6,
	0x45, 0x9f, 0x61, 0x0b, 0xdb, 0x84, 0x76, 0xd1, 0x8a, 0x4a, 0xc3, 0xed, 0x74, 0x38, 0xf6, 0x6a,
	0xa8, 0x96, 0x0d, 0xba, 0xcf, 0x18, 0xa6, 0x9e, 0x60, 0xee, 0x00, 0x35, 0x6a, 0x6a, 0x1d, 0xd7,
	0x71, 0xdc, 0x81, 0x52, 0x6b, 0xde, 0xb6, 0x5a, 0x09, 0x56, 0x8d, 0x61, 0xb5, 0x3e, 0x48, 0x34,
	0x97, 0x49, 0x5a, 0x15, 0xf2, 0x14, 0x20, 0x87, 0xb2, 0x2a, 0x6e, 0xc3, 0xa6, 0xcb, 0x04, 0x66,
	0xcc, 0x55, 0xcb, 0x79, 0x07, 0x5a, 0x2e, 0x13, 0xa4, 0x4b, 0x5d, 0x86, 0x73, 0xbe, 0xd7, 0x48,
	0xd3, 0x28, 0xc4, 0x7e, 0xdf, 0x56, 0x04, 0x6d, 0x1a, 0xbf, 0x68, 0x55, 0xb7, 0x7a, 0x32, 0x19,
	0xcb, 0xc1, 0x95, 0x8c, 0xca, 0x6e, 0xb5, 0x7a, 0x41, 0x3a, 0xbc, 0xca, 0x72, 0xdf, 0x82, 0x8d,
	0x9e, 0xe9, 0x59, 0xa7, 0x59, 0x83, 0x8e, 0xe1, 0x40, 0x0d, 0x68, 0x01, 0x88, 0xf6, 0x85, 0xe0,
	0xae, 0xcf, 0x32, 0x4e, 0xbe, 0x2d, 0xf2, 0x4c, 0xd6, 0xc5, 0x6a, 0xd3, 0x7c, 0x0c, 0x60, 0x0e,
	0x97, 0xfb, 0x13, 0x60, 0x9d, 0x50, 0x8e, 0x99, 0xe2, 0x37, 0xc0, 0x7a, 0x11, 0x50, 0x76, 0x3f,
	0xd9, 0xd8, 0xc1, 0x59, 0x7f, 0xcf, 0xab, 0xfe, 0x9a, 0xc9, 0x78, 0xa1, 0x76, 0x92, 0x2d, 0x5f,
	0xe5, 0xd1, 0x3d, 0x81, 0xed, 0x12, 0x7b, 0x16, 0x46, 0xa3, 0x5b, 0xd7, 0xdd, 0x0e, 0xb4, 0xcc,
	0x6e, 0x97, 0xe1, 0xee, 0x72, 0x09, 0xa9, 0x98, 0x2a, 0xa8, 0x61, 0x5c, 0x54, 0x37, 0x54, 0x67,
	0x11, 0x65, 0x51, 0x59, 0xc1, 0x64, 0xd2, 0x0e, 0xe6, 0xc5, 0xf8, 0x7c, 0x0e, 0x2d, 0x9c, 0x24,
	0x71, 0xbe, 0x5b, 0x33, 0x7a, 0xe5, 0xcb, 0x2e, 0xab, 0x72, 0x46, 0x08, 0xb4, 0xa2, 0x86, 0x92,
	0x9b, 0x1d, 0x5c, 0x07, 0x35, 0xe3, 0x47, 0x0d, 0xde, 0x2f, 0x6d, 0xd3, 0xec, 0xd2, 0x9b, 0x04,
	0xc9, 0xbb, 0x9d, 0x9c, 0xc1, 0xbe, 0x5a, 0xe2, 0xa7, 0x41, 0x34, 0x9a, 0x84, 0xd1, 0xb8, 0x17,
	0x8f, 0xc2, 0x57, 0xa1, 0x4c, 0x72, 0xa6, 0xe7, 0xfe, 0xd4, 0xae, 0x16, 0xa7, 0x26, 0xb5, 0x9d,
	0x7c, 0xd4, 0x10, 0x6c, 0xe7, 0xad, 0xcd, 0x24, 0x3c, 0xcf, 0x8e, 0x61, 0x45, 0x1f, 0xaf, 0x80,
	0x1a, 0xc6, 0x37, 0xf0, 0xde, 0xb2, 0x6e, 0xe3, 0x71, 0x22, 0xc7, 0x41, 0x2a, 0x4f, 0x83, 0xeb,
	0x9a, 0x8b, 0xdc, 0xff, 0x27, 0xa0, 0xdf, 0x86, 0xb3, 0x4a, 0x6e, 0xc1, 0x06, 0xa1, 0x67, 0xa6,
	0x43, 0x54, 0xab, 0x37, 0xa0, 0xd9, 0x33, 0xcf, 0x91, 0x96, 0xfd, 0x21, 0x14, 0x35, 0x8c, 0x41,
	0x35, 0x30, 0x77, 0x6e, 0x8a, 0x2f, 0x61, 0xdb, 0xbd, 0xfc, 0x56, 0x0e, 0x53, 0x73, 0x38, 0x94,
	0xf3, 0xb9, 0x62, 0x1d, 0x75, 0x29, 0xce, 0x1f, 0x0c, 0x8a, 0xb8, 0xf9, 0x83, 0xa1, 0x60, 0xaf,
	0x9a, 0xcc, 0x1a, 0x9b, 0x9b, 0xc6, 0x9b, 0xda, 0xbc, 0x4f, 0x67, 0x71, 0x7d, 0xde, 0x5f, 0x02,
	0xe4, 0x50, 0xd9, 0xea, 0x9e, 0x6b, 0xfb, 0x0e, 0xce, 0xf9, 0xdc, 0x67, 0xae, 0xe7, 0x22, 0x4d,
	0xff, 0x0c, 0x3e, 0x14, 0xa2, 0x52, 0x13, 0x62, 0xfe, 0x26, 0x4c, 0x87, 0x57, 0x62, 0xba, 0x98,
	0xa7, 0xe2, 0x2a, 0xb8, 0x96, 0x22, 0x10, 0x23, 0xf9, 0x2a, 0x58, 0x4c, 0x52, 0x21, 0xd0, 0x9f,
	0xe5, 0x4f, 0x33, 0x7e, 0xd6, 0x2a, 0xcf, 0x9d, 0x38, 0x91, 0xe1, 0x38, 0x7a, 0x26, 0x6f, 0xca,
	0x12, 0xe5, 0x24, 0xc8, 0xe6, 0x40, 0xcd, 0x18, 0xe9, 0xf5, 0x9d, 0x22, 0xa5, 0xec, 0xb9, 0xa3,
	0xa9, 0x96, 0x64, 0xeb, 0xba, 0xbc, 0xf8, 0x1b, 0x06, 0x81, 0xbd, 0x7c, 0xd2, 0x97, 0x4f, 0x06,
	0x35, 0x92, 0xd4, 0x15, 0xa6, 0xe5, 0x11, 0x97, 0xfe, 0xed, 0xfa, 0x54, 0x22, 0xb5, 0x22, 0x68,
	0xf6, 0x96, 0x6a, 0x8f, 0xe0, 0x3f, 0xc3, 0x78, 0x7a, 0x32, 0x8e, 0xe3, 0xf1, 0x44, 0x9e, 0x14,
	0x0f, 0xc1, 0x93, 0xf2, 0xa9, 0x18, 0xcc, 0xd3, 0xf6, 0xe1, 0x0b, 0x99, 0x06, 0xfc, 0xb9, 0xb3,
	0xec, 0x38, 0xf7, 0xb2, 0xd0, 0xfb, 0xda, 0x8b, 0x0f, 0xc6, 0x61, 0x7a, 0xb5, 0xb8, 0x3c, 0x19,
	0xc6, 0xd3, 0xc7, 0xc1, 0x6c, 0x9e, 0x46, 0xa3, 0xcb, 0xc7, 0xef, 0x7a, 0x7a, 0xfe, 0x15, 0x00,
	0x00, 0xff, 0xff, 0xa3, 0x7f, 0x48, 0x17, 0x91, 0x0a, 0x00, 0x00,
}
