// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/resolved_ast/resolved_node_kind.proto

package zetasql

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResolvedNodeKind int32

const (
	ResolvedNodeKind_RESOLVED_LITERAL                               ResolvedNodeKind = 3
	ResolvedNodeKind_RESOLVED_PARAMETER                             ResolvedNodeKind = 4
	ResolvedNodeKind_RESOLVED_EXPRESSION_COLUMN                     ResolvedNodeKind = 5
	ResolvedNodeKind_RESOLVED_COLUMN_REF                            ResolvedNodeKind = 6
	ResolvedNodeKind_RESOLVED_CONSTANT                              ResolvedNodeKind = 103
	ResolvedNodeKind_RESOLVED_SYSTEM_VARIABLE                       ResolvedNodeKind = 139
	ResolvedNodeKind_RESOLVED_INLINE_LAMBDA                         ResolvedNodeKind = 159
	ResolvedNodeKind_RESOLVED_FUNCTION_CALL                         ResolvedNodeKind = 8
	ResolvedNodeKind_RESOLVED_AGGREGATE_FUNCTION_CALL               ResolvedNodeKind = 9
	ResolvedNodeKind_RESOLVED_ANALYTIC_FUNCTION_CALL                ResolvedNodeKind = 10
	ResolvedNodeKind_RESOLVED_EXTENDED_CAST_ELEMENT                 ResolvedNodeKind = 151
	ResolvedNodeKind_RESOLVED_EXTENDED_CAST                         ResolvedNodeKind = 158
	ResolvedNodeKind_RESOLVED_CAST                                  ResolvedNodeKind = 11
	ResolvedNodeKind_RESOLVED_MAKE_STRUCT                           ResolvedNodeKind = 12
	ResolvedNodeKind_RESOLVED_MAKE_PROTO                            ResolvedNodeKind = 13
	ResolvedNodeKind_RESOLVED_MAKE_PROTO_FIELD                      ResolvedNodeKind = 14
	ResolvedNodeKind_RESOLVED_GET_STRUCT_FIELD                      ResolvedNodeKind = 15
	ResolvedNodeKind_RESOLVED_GET_PROTO_FIELD                       ResolvedNodeKind = 16
	ResolvedNodeKind_RESOLVED_FLATTEN                               ResolvedNodeKind = 149
	ResolvedNodeKind_RESOLVED_FLATTENED_ARG                         ResolvedNodeKind = 150
	ResolvedNodeKind_RESOLVED_REPLACE_FIELD_ITEM                    ResolvedNodeKind = 128
	ResolvedNodeKind_RESOLVED_REPLACE_FIELD                         ResolvedNodeKind = 129
	ResolvedNodeKind_RESOLVED_SUBQUERY_EXPR                         ResolvedNodeKind = 17
	ResolvedNodeKind_RESOLVED_MODEL                                 ResolvedNodeKind = 109
	ResolvedNodeKind_RESOLVED_CONNECTION                            ResolvedNodeKind = 141
	ResolvedNodeKind_RESOLVED_DESCRIPTOR                            ResolvedNodeKind = 144
	ResolvedNodeKind_RESOLVED_SINGLE_ROW_SCAN                       ResolvedNodeKind = 19
	ResolvedNodeKind_RESOLVED_TABLE_SCAN                            ResolvedNodeKind = 20
	ResolvedNodeKind_RESOLVED_JOIN_SCAN                             ResolvedNodeKind = 21
	ResolvedNodeKind_RESOLVED_ARRAY_SCAN                            ResolvedNodeKind = 22
	ResolvedNodeKind_RESOLVED_COLUMN_HOLDER                         ResolvedNodeKind = 23
	ResolvedNodeKind_RESOLVED_FILTER_SCAN                           ResolvedNodeKind = 24
	ResolvedNodeKind_RESOLVED_GROUPING_SET                          ResolvedNodeKind = 93
	ResolvedNodeKind_RESOLVED_AGGREGATE_SCAN                        ResolvedNodeKind = 25
	ResolvedNodeKind_RESOLVED_SET_OPERATION_ITEM                    ResolvedNodeKind = 94
	ResolvedNodeKind_RESOLVED_SET_OPERATION_SCAN                    ResolvedNodeKind = 26
	ResolvedNodeKind_RESOLVED_ORDER_BY_SCAN                         ResolvedNodeKind = 27
	ResolvedNodeKind_RESOLVED_LIMIT_OFFSET_SCAN                     ResolvedNodeKind = 28
	ResolvedNodeKind_RESOLVED_WITH_REF_SCAN                         ResolvedNodeKind = 29
	ResolvedNodeKind_RESOLVED_ANALYTIC_SCAN                         ResolvedNodeKind = 30
	ResolvedNodeKind_RESOLVED_SAMPLE_SCAN                           ResolvedNodeKind = 31
	ResolvedNodeKind_RESOLVED_COMPUTED_COLUMN                       ResolvedNodeKind = 32
	ResolvedNodeKind_RESOLVED_ORDER_BY_ITEM                         ResolvedNodeKind = 33
	ResolvedNodeKind_RESOLVED_COLUMN_ANNOTATIONS                    ResolvedNodeKind = 104
	ResolvedNodeKind_RESOLVED_GENERATED_COLUMN_INFO                 ResolvedNodeKind = 105
	ResolvedNodeKind_RESOLVED_COLUMN_DEFINITION                     ResolvedNodeKind = 91
	ResolvedNodeKind_RESOLVED_PRIMARY_KEY                           ResolvedNodeKind = 92
	ResolvedNodeKind_RESOLVED_FOREIGN_KEY                           ResolvedNodeKind = 110
	ResolvedNodeKind_RESOLVED_CHECK_CONSTRAINT                      ResolvedNodeKind = 113
	ResolvedNodeKind_RESOLVED_OUTPUT_COLUMN                         ResolvedNodeKind = 34
	ResolvedNodeKind_RESOLVED_PROJECT_SCAN                          ResolvedNodeKind = 35
	ResolvedNodeKind_RESOLVED_TVFSCAN                               ResolvedNodeKind = 81
	ResolvedNodeKind_RESOLVED_FUNCTION_ARGUMENT                     ResolvedNodeKind = 82
	ResolvedNodeKind_RESOLVED_EXPLAIN_STMT                          ResolvedNodeKind = 37
	ResolvedNodeKind_RESOLVED_QUERY_STMT                            ResolvedNodeKind = 38
	ResolvedNodeKind_RESOLVED_CREATE_DATABASE_STMT                  ResolvedNodeKind = 95
	ResolvedNodeKind_RESOLVED_INDEX_ITEM                            ResolvedNodeKind = 96
	ResolvedNodeKind_RESOLVED_UNNEST_ITEM                           ResolvedNodeKind = 126
	ResolvedNodeKind_RESOLVED_CREATE_INDEX_STMT                     ResolvedNodeKind = 97
	ResolvedNodeKind_RESOLVED_CREATE_SCHEMA_STMT                    ResolvedNodeKind = 157
	ResolvedNodeKind_RESOLVED_CREATE_TABLE_STMT                     ResolvedNodeKind = 90
	ResolvedNodeKind_RESOLVED_CREATE_TABLE_AS_SELECT_STMT           ResolvedNodeKind = 40
	ResolvedNodeKind_RESOLVED_CREATE_MODEL_STMT                     ResolvedNodeKind = 107
	ResolvedNodeKind_RESOLVED_CREATE_VIEW_STMT                      ResolvedNodeKind = 41
	ResolvedNodeKind_RESOLVED_WITH_PARTITION_COLUMNS                ResolvedNodeKind = 153
	ResolvedNodeKind_RESOLVED_CREATE_EXTERNAL_TABLE_STMT            ResolvedNodeKind = 42
	ResolvedNodeKind_RESOLVED_EXPORT_MODEL_STMT                     ResolvedNodeKind = 152
	ResolvedNodeKind_RESOLVED_EXPORT_DATA_STMT                      ResolvedNodeKind = 43
	ResolvedNodeKind_RESOLVED_DEFINE_TABLE_STMT                     ResolvedNodeKind = 44
	ResolvedNodeKind_RESOLVED_DESCRIBE_STMT                         ResolvedNodeKind = 45
	ResolvedNodeKind_RESOLVED_SHOW_STMT                             ResolvedNodeKind = 46
	ResolvedNodeKind_RESOLVED_BEGIN_STMT                            ResolvedNodeKind = 47
	ResolvedNodeKind_RESOLVED_SET_TRANSACTION_STMT                  ResolvedNodeKind = 120
	ResolvedNodeKind_RESOLVED_COMMIT_STMT                           ResolvedNodeKind = 48
	ResolvedNodeKind_RESOLVED_ROLLBACK_STMT                         ResolvedNodeKind = 49
	ResolvedNodeKind_RESOLVED_START_BATCH_STMT                      ResolvedNodeKind = 122
	ResolvedNodeKind_RESOLVED_RUN_BATCH_STMT                        ResolvedNodeKind = 123
	ResolvedNodeKind_RESOLVED_ABORT_BATCH_STMT                      ResolvedNodeKind = 124
	ResolvedNodeKind_RESOLVED_DROP_STMT                             ResolvedNodeKind = 50
	ResolvedNodeKind_RESOLVED_DROP_MATERIALIZED_VIEW_STMT           ResolvedNodeKind = 121
	ResolvedNodeKind_RESOLVED_RECURSIVE_REF_SCAN                    ResolvedNodeKind = 147
	ResolvedNodeKind_RESOLVED_RECURSIVE_SCAN                        ResolvedNodeKind = 148
	ResolvedNodeKind_RESOLVED_WITH_SCAN                             ResolvedNodeKind = 51
	ResolvedNodeKind_RESOLVED_WITH_ENTRY                            ResolvedNodeKind = 52
	ResolvedNodeKind_RESOLVED_OPTION                                ResolvedNodeKind = 53
	ResolvedNodeKind_RESOLVED_WINDOW_PARTITIONING                   ResolvedNodeKind = 54
	ResolvedNodeKind_RESOLVED_WINDOW_ORDERING                       ResolvedNodeKind = 55
	ResolvedNodeKind_RESOLVED_WINDOW_FRAME                          ResolvedNodeKind = 56
	ResolvedNodeKind_RESOLVED_ANALYTIC_FUNCTION_GROUP               ResolvedNodeKind = 57
	ResolvedNodeKind_RESOLVED_WINDOW_FRAME_EXPR                     ResolvedNodeKind = 58
	ResolvedNodeKind_RESOLVED_DMLVALUE                              ResolvedNodeKind = 59
	ResolvedNodeKind_RESOLVED_DMLDEFAULT                            ResolvedNodeKind = 60
	ResolvedNodeKind_RESOLVED_ASSERT_STMT                           ResolvedNodeKind = 98
	ResolvedNodeKind_RESOLVED_ASSERT_ROWS_MODIFIED                  ResolvedNodeKind = 61
	ResolvedNodeKind_RESOLVED_INSERT_ROW                            ResolvedNodeKind = 62
	ResolvedNodeKind_RESOLVED_INSERT_STMT                           ResolvedNodeKind = 63
	ResolvedNodeKind_RESOLVED_DELETE_STMT                           ResolvedNodeKind = 64
	ResolvedNodeKind_RESOLVED_UPDATE_ITEM                           ResolvedNodeKind = 65
	ResolvedNodeKind_RESOLVED_UPDATE_ARRAY_ITEM                     ResolvedNodeKind = 102
	ResolvedNodeKind_RESOLVED_UPDATE_STMT                           ResolvedNodeKind = 66
	ResolvedNodeKind_RESOLVED_MERGE_WHEN                            ResolvedNodeKind = 100
	ResolvedNodeKind_RESOLVED_MERGE_STMT                            ResolvedNodeKind = 101
	ResolvedNodeKind_RESOLVED_TRUNCATE_STMT                         ResolvedNodeKind = 133
	ResolvedNodeKind_RESOLVED_PRIVILEGE                             ResolvedNodeKind = 67
	ResolvedNodeKind_RESOLVED_GRANT_STMT                            ResolvedNodeKind = 69
	ResolvedNodeKind_RESOLVED_REVOKE_STMT                           ResolvedNodeKind = 70
	ResolvedNodeKind_RESOLVED_ALTER_DATABASE_STMT                   ResolvedNodeKind = 134
	ResolvedNodeKind_RESOLVED_ALTER_MATERIALIZED_VIEW_STMT          ResolvedNodeKind = 127
	ResolvedNodeKind_RESOLVED_ALTER_TABLE_STMT                      ResolvedNodeKind = 115
	ResolvedNodeKind_RESOLVED_ALTER_VIEW_STMT                       ResolvedNodeKind = 118
	ResolvedNodeKind_RESOLVED_SET_OPTIONS_ACTION                    ResolvedNodeKind = 117
	ResolvedNodeKind_RESOLVED_ADD_COLUMN_ACTION                     ResolvedNodeKind = 131
	ResolvedNodeKind_RESOLVED_DROP_COLUMN_ACTION                    ResolvedNodeKind = 132
	ResolvedNodeKind_RESOLVED_SET_AS_ACTION                         ResolvedNodeKind = 156
	ResolvedNodeKind_RESOLVED_ALTER_TABLE_SET_OPTIONS_STMT          ResolvedNodeKind = 71
	ResolvedNodeKind_RESOLVED_RENAME_STMT                           ResolvedNodeKind = 72
	ResolvedNodeKind_RESOLVED_CREATE_ROW_ACCESS_POLICY_STMT         ResolvedNodeKind = 73
	ResolvedNodeKind_RESOLVED_DROP_ROW_ACCESS_POLICY_STMT           ResolvedNodeKind = 74
	ResolvedNodeKind_RESOLVED_GRANT_TO_ACTION                       ResolvedNodeKind = 135
	ResolvedNodeKind_RESOLVED_FILTER_USING_ACTION                   ResolvedNodeKind = 136
	ResolvedNodeKind_RESOLVED_REVOKE_FROM_ACTION                    ResolvedNodeKind = 137
	ResolvedNodeKind_RESOLVED_RENAME_TO_ACTION                      ResolvedNodeKind = 138
	ResolvedNodeKind_RESOLVED_ALTER_ROW_ACCESS_POLICY_STMT          ResolvedNodeKind = 75
	ResolvedNodeKind_RESOLVED_ALTER_ALL_ROW_ACCESS_POLICIES_STMT    ResolvedNodeKind = 145
	ResolvedNodeKind_RESOLVED_CREATE_CONSTANT_STMT                  ResolvedNodeKind = 99
	ResolvedNodeKind_RESOLVED_CREATE_FUNCTION_STMT                  ResolvedNodeKind = 76
	ResolvedNodeKind_RESOLVED_ARGUMENT_DEF                          ResolvedNodeKind = 77
	ResolvedNodeKind_RESOLVED_ARGUMENT_REF                          ResolvedNodeKind = 78
	ResolvedNodeKind_RESOLVED_CREATE_TABLE_FUNCTION_STMT            ResolvedNodeKind = 88
	ResolvedNodeKind_RESOLVED_RELATION_ARGUMENT_SCAN                ResolvedNodeKind = 89
	ResolvedNodeKind_RESOLVED_ARGUMENT_LIST                         ResolvedNodeKind = 79
	ResolvedNodeKind_RESOLVED_FUNCTION_SIGNATURE_HOLDER             ResolvedNodeKind = 84
	ResolvedNodeKind_RESOLVED_DROP_FUNCTION_STMT                    ResolvedNodeKind = 80
	ResolvedNodeKind_RESOLVED_CALL_STMT                             ResolvedNodeKind = 83
	ResolvedNodeKind_RESOLVED_IMPORT_STMT                           ResolvedNodeKind = 86
	ResolvedNodeKind_RESOLVED_MODULE_STMT                           ResolvedNodeKind = 87
	ResolvedNodeKind_RESOLVED_AGGREGATE_HAVING_MODIFIER             ResolvedNodeKind = 85
	ResolvedNodeKind_RESOLVED_CREATE_MATERIALIZED_VIEW_STMT         ResolvedNodeKind = 119
	ResolvedNodeKind_RESOLVED_CREATE_PROCEDURE_STMT                 ResolvedNodeKind = 125
	ResolvedNodeKind_RESOLVED_EXECUTE_IMMEDIATE_ARGUMENT            ResolvedNodeKind = 143
	ResolvedNodeKind_RESOLVED_EXECUTE_IMMEDIATE_STMT                ResolvedNodeKind = 140
	ResolvedNodeKind_RESOLVED_ASSIGNMENT_STMT                       ResolvedNodeKind = 142
	ResolvedNodeKind_RESOLVED_CREATE_ENTITY_STMT                    ResolvedNodeKind = 154
	ResolvedNodeKind_RESOLVED_ALTER_ENTITY_STMT                     ResolvedNodeKind = 155
	ResolvedNodeKind___ResolvedNodeKind__switch_must_have_default__ ResolvedNodeKind = -1
)

var ResolvedNodeKind_name = map[int32]string{
	3:   "RESOLVED_LITERAL",
	4:   "RESOLVED_PARAMETER",
	5:   "RESOLVED_EXPRESSION_COLUMN",
	6:   "RESOLVED_COLUMN_REF",
	103: "RESOLVED_CONSTANT",
	139: "RESOLVED_SYSTEM_VARIABLE",
	159: "RESOLVED_INLINE_LAMBDA",
	8:   "RESOLVED_FUNCTION_CALL",
	9:   "RESOLVED_AGGREGATE_FUNCTION_CALL",
	10:  "RESOLVED_ANALYTIC_FUNCTION_CALL",
	151: "RESOLVED_EXTENDED_CAST_ELEMENT",
	158: "RESOLVED_EXTENDED_CAST",
	11:  "RESOLVED_CAST",
	12:  "RESOLVED_MAKE_STRUCT",
	13:  "RESOLVED_MAKE_PROTO",
	14:  "RESOLVED_MAKE_PROTO_FIELD",
	15:  "RESOLVED_GET_STRUCT_FIELD",
	16:  "RESOLVED_GET_PROTO_FIELD",
	149: "RESOLVED_FLATTEN",
	150: "RESOLVED_FLATTENED_ARG",
	128: "RESOLVED_REPLACE_FIELD_ITEM",
	129: "RESOLVED_REPLACE_FIELD",
	17:  "RESOLVED_SUBQUERY_EXPR",
	109: "RESOLVED_MODEL",
	141: "RESOLVED_CONNECTION",
	144: "RESOLVED_DESCRIPTOR",
	19:  "RESOLVED_SINGLE_ROW_SCAN",
	20:  "RESOLVED_TABLE_SCAN",
	21:  "RESOLVED_JOIN_SCAN",
	22:  "RESOLVED_ARRAY_SCAN",
	23:  "RESOLVED_COLUMN_HOLDER",
	24:  "RESOLVED_FILTER_SCAN",
	93:  "RESOLVED_GROUPING_SET",
	25:  "RESOLVED_AGGREGATE_SCAN",
	94:  "RESOLVED_SET_OPERATION_ITEM",
	26:  "RESOLVED_SET_OPERATION_SCAN",
	27:  "RESOLVED_ORDER_BY_SCAN",
	28:  "RESOLVED_LIMIT_OFFSET_SCAN",
	29:  "RESOLVED_WITH_REF_SCAN",
	30:  "RESOLVED_ANALYTIC_SCAN",
	31:  "RESOLVED_SAMPLE_SCAN",
	32:  "RESOLVED_COMPUTED_COLUMN",
	33:  "RESOLVED_ORDER_BY_ITEM",
	104: "RESOLVED_COLUMN_ANNOTATIONS",
	105: "RESOLVED_GENERATED_COLUMN_INFO",
	91:  "RESOLVED_COLUMN_DEFINITION",
	92:  "RESOLVED_PRIMARY_KEY",
	110: "RESOLVED_FOREIGN_KEY",
	113: "RESOLVED_CHECK_CONSTRAINT",
	34:  "RESOLVED_OUTPUT_COLUMN",
	35:  "RESOLVED_PROJECT_SCAN",
	81:  "RESOLVED_TVFSCAN",
	82:  "RESOLVED_FUNCTION_ARGUMENT",
	37:  "RESOLVED_EXPLAIN_STMT",
	38:  "RESOLVED_QUERY_STMT",
	95:  "RESOLVED_CREATE_DATABASE_STMT",
	96:  "RESOLVED_INDEX_ITEM",
	126: "RESOLVED_UNNEST_ITEM",
	97:  "RESOLVED_CREATE_INDEX_STMT",
	157: "RESOLVED_CREATE_SCHEMA_STMT",
	90:  "RESOLVED_CREATE_TABLE_STMT",
	40:  "RESOLVED_CREATE_TABLE_AS_SELECT_STMT",
	107: "RESOLVED_CREATE_MODEL_STMT",
	41:  "RESOLVED_CREATE_VIEW_STMT",
	153: "RESOLVED_WITH_PARTITION_COLUMNS",
	42:  "RESOLVED_CREATE_EXTERNAL_TABLE_STMT",
	152: "RESOLVED_EXPORT_MODEL_STMT",
	43:  "RESOLVED_EXPORT_DATA_STMT",
	44:  "RESOLVED_DEFINE_TABLE_STMT",
	45:  "RESOLVED_DESCRIBE_STMT",
	46:  "RESOLVED_SHOW_STMT",
	47:  "RESOLVED_BEGIN_STMT",
	120: "RESOLVED_SET_TRANSACTION_STMT",
	48:  "RESOLVED_COMMIT_STMT",
	49:  "RESOLVED_ROLLBACK_STMT",
	122: "RESOLVED_START_BATCH_STMT",
	123: "RESOLVED_RUN_BATCH_STMT",
	124: "RESOLVED_ABORT_BATCH_STMT",
	50:  "RESOLVED_DROP_STMT",
	121: "RESOLVED_DROP_MATERIALIZED_VIEW_STMT",
	147: "RESOLVED_RECURSIVE_REF_SCAN",
	148: "RESOLVED_RECURSIVE_SCAN",
	51:  "RESOLVED_WITH_SCAN",
	52:  "RESOLVED_WITH_ENTRY",
	53:  "RESOLVED_OPTION",
	54:  "RESOLVED_WINDOW_PARTITIONING",
	55:  "RESOLVED_WINDOW_ORDERING",
	56:  "RESOLVED_WINDOW_FRAME",
	57:  "RESOLVED_ANALYTIC_FUNCTION_GROUP",
	58:  "RESOLVED_WINDOW_FRAME_EXPR",
	59:  "RESOLVED_DMLVALUE",
	60:  "RESOLVED_DMLDEFAULT",
	98:  "RESOLVED_ASSERT_STMT",
	61:  "RESOLVED_ASSERT_ROWS_MODIFIED",
	62:  "RESOLVED_INSERT_ROW",
	63:  "RESOLVED_INSERT_STMT",
	64:  "RESOLVED_DELETE_STMT",
	65:  "RESOLVED_UPDATE_ITEM",
	102: "RESOLVED_UPDATE_ARRAY_ITEM",
	66:  "RESOLVED_UPDATE_STMT",
	100: "RESOLVED_MERGE_WHEN",
	101: "RESOLVED_MERGE_STMT",
	133: "RESOLVED_TRUNCATE_STMT",
	67:  "RESOLVED_PRIVILEGE",
	69:  "RESOLVED_GRANT_STMT",
	70:  "RESOLVED_REVOKE_STMT",
	134: "RESOLVED_ALTER_DATABASE_STMT",
	127: "RESOLVED_ALTER_MATERIALIZED_VIEW_STMT",
	115: "RESOLVED_ALTER_TABLE_STMT",
	118: "RESOLVED_ALTER_VIEW_STMT",
	117: "RESOLVED_SET_OPTIONS_ACTION",
	131: "RESOLVED_ADD_COLUMN_ACTION",
	132: "RESOLVED_DROP_COLUMN_ACTION",
	156: "RESOLVED_SET_AS_ACTION",
	71:  "RESOLVED_ALTER_TABLE_SET_OPTIONS_STMT",
	72:  "RESOLVED_RENAME_STMT",
	73:  "RESOLVED_CREATE_ROW_ACCESS_POLICY_STMT",
	74:  "RESOLVED_DROP_ROW_ACCESS_POLICY_STMT",
	135: "RESOLVED_GRANT_TO_ACTION",
	136: "RESOLVED_FILTER_USING_ACTION",
	137: "RESOLVED_REVOKE_FROM_ACTION",
	138: "RESOLVED_RENAME_TO_ACTION",
	75:  "RESOLVED_ALTER_ROW_ACCESS_POLICY_STMT",
	145: "RESOLVED_ALTER_ALL_ROW_ACCESS_POLICIES_STMT",
	99:  "RESOLVED_CREATE_CONSTANT_STMT",
	76:  "RESOLVED_CREATE_FUNCTION_STMT",
	77:  "RESOLVED_ARGUMENT_DEF",
	78:  "RESOLVED_ARGUMENT_REF",
	88:  "RESOLVED_CREATE_TABLE_FUNCTION_STMT",
	89:  "RESOLVED_RELATION_ARGUMENT_SCAN",
	79:  "RESOLVED_ARGUMENT_LIST",
	84:  "RESOLVED_FUNCTION_SIGNATURE_HOLDER",
	80:  "RESOLVED_DROP_FUNCTION_STMT",
	83:  "RESOLVED_CALL_STMT",
	86:  "RESOLVED_IMPORT_STMT",
	87:  "RESOLVED_MODULE_STMT",
	85:  "RESOLVED_AGGREGATE_HAVING_MODIFIER",
	119: "RESOLVED_CREATE_MATERIALIZED_VIEW_STMT",
	125: "RESOLVED_CREATE_PROCEDURE_STMT",
	143: "RESOLVED_EXECUTE_IMMEDIATE_ARGUMENT",
	140: "RESOLVED_EXECUTE_IMMEDIATE_STMT",
	142: "RESOLVED_ASSIGNMENT_STMT",
	154: "RESOLVED_CREATE_ENTITY_STMT",
	155: "RESOLVED_ALTER_ENTITY_STMT",
	-1:  "__ResolvedNodeKind__switch_must_have_default__",
}

var ResolvedNodeKind_value = map[string]int32{
	"RESOLVED_LITERAL":                               3,
	"RESOLVED_PARAMETER":                             4,
	"RESOLVED_EXPRESSION_COLUMN":                     5,
	"RESOLVED_COLUMN_REF":                            6,
	"RESOLVED_CONSTANT":                              103,
	"RESOLVED_SYSTEM_VARIABLE":                       139,
	"RESOLVED_INLINE_LAMBDA":                         159,
	"RESOLVED_FUNCTION_CALL":                         8,
	"RESOLVED_AGGREGATE_FUNCTION_CALL":               9,
	"RESOLVED_ANALYTIC_FUNCTION_CALL":                10,
	"RESOLVED_EXTENDED_CAST_ELEMENT":                 151,
	"RESOLVED_EXTENDED_CAST":                         158,
	"RESOLVED_CAST":                                  11,
	"RESOLVED_MAKE_STRUCT":                           12,
	"RESOLVED_MAKE_PROTO":                            13,
	"RESOLVED_MAKE_PROTO_FIELD":                      14,
	"RESOLVED_GET_STRUCT_FIELD":                      15,
	"RESOLVED_GET_PROTO_FIELD":                       16,
	"RESOLVED_FLATTEN":                               149,
	"RESOLVED_FLATTENED_ARG":                         150,
	"RESOLVED_REPLACE_FIELD_ITEM":                    128,
	"RESOLVED_REPLACE_FIELD":                         129,
	"RESOLVED_SUBQUERY_EXPR":                         17,
	"RESOLVED_MODEL":                                 109,
	"RESOLVED_CONNECTION":                            141,
	"RESOLVED_DESCRIPTOR":                            144,
	"RESOLVED_SINGLE_ROW_SCAN":                       19,
	"RESOLVED_TABLE_SCAN":                            20,
	"RESOLVED_JOIN_SCAN":                             21,
	"RESOLVED_ARRAY_SCAN":                            22,
	"RESOLVED_COLUMN_HOLDER":                         23,
	"RESOLVED_FILTER_SCAN":                           24,
	"RESOLVED_GROUPING_SET":                          93,
	"RESOLVED_AGGREGATE_SCAN":                        25,
	"RESOLVED_SET_OPERATION_ITEM":                    94,
	"RESOLVED_SET_OPERATION_SCAN":                    26,
	"RESOLVED_ORDER_BY_SCAN":                         27,
	"RESOLVED_LIMIT_OFFSET_SCAN":                     28,
	"RESOLVED_WITH_REF_SCAN":                         29,
	"RESOLVED_ANALYTIC_SCAN":                         30,
	"RESOLVED_SAMPLE_SCAN":                           31,
	"RESOLVED_COMPUTED_COLUMN":                       32,
	"RESOLVED_ORDER_BY_ITEM":                         33,
	"RESOLVED_COLUMN_ANNOTATIONS":                    104,
	"RESOLVED_GENERATED_COLUMN_INFO":                 105,
	"RESOLVED_COLUMN_DEFINITION":                     91,
	"RESOLVED_PRIMARY_KEY":                           92,
	"RESOLVED_FOREIGN_KEY":                           110,
	"RESOLVED_CHECK_CONSTRAINT":                      113,
	"RESOLVED_OUTPUT_COLUMN":                         34,
	"RESOLVED_PROJECT_SCAN":                          35,
	"RESOLVED_TVFSCAN":                               81,
	"RESOLVED_FUNCTION_ARGUMENT":                     82,
	"RESOLVED_EXPLAIN_STMT":                          37,
	"RESOLVED_QUERY_STMT":                            38,
	"RESOLVED_CREATE_DATABASE_STMT":                  95,
	"RESOLVED_INDEX_ITEM":                            96,
	"RESOLVED_UNNEST_ITEM":                           126,
	"RESOLVED_CREATE_INDEX_STMT":                     97,
	"RESOLVED_CREATE_SCHEMA_STMT":                    157,
	"RESOLVED_CREATE_TABLE_STMT":                     90,
	"RESOLVED_CREATE_TABLE_AS_SELECT_STMT":           40,
	"RESOLVED_CREATE_MODEL_STMT":                     107,
	"RESOLVED_CREATE_VIEW_STMT":                      41,
	"RESOLVED_WITH_PARTITION_COLUMNS":                153,
	"RESOLVED_CREATE_EXTERNAL_TABLE_STMT":            42,
	"RESOLVED_EXPORT_MODEL_STMT":                     152,
	"RESOLVED_EXPORT_DATA_STMT":                      43,
	"RESOLVED_DEFINE_TABLE_STMT":                     44,
	"RESOLVED_DESCRIBE_STMT":                         45,
	"RESOLVED_SHOW_STMT":                             46,
	"RESOLVED_BEGIN_STMT":                            47,
	"RESOLVED_SET_TRANSACTION_STMT":                  120,
	"RESOLVED_COMMIT_STMT":                           48,
	"RESOLVED_ROLLBACK_STMT":                         49,
	"RESOLVED_START_BATCH_STMT":                      122,
	"RESOLVED_RUN_BATCH_STMT":                        123,
	"RESOLVED_ABORT_BATCH_STMT":                      124,
	"RESOLVED_DROP_STMT":                             50,
	"RESOLVED_DROP_MATERIALIZED_VIEW_STMT":           121,
	"RESOLVED_RECURSIVE_REF_SCAN":                    147,
	"RESOLVED_RECURSIVE_SCAN":                        148,
	"RESOLVED_WITH_SCAN":                             51,
	"RESOLVED_WITH_ENTRY":                            52,
	"RESOLVED_OPTION":                                53,
	"RESOLVED_WINDOW_PARTITIONING":                   54,
	"RESOLVED_WINDOW_ORDERING":                       55,
	"RESOLVED_WINDOW_FRAME":                          56,
	"RESOLVED_ANALYTIC_FUNCTION_GROUP":               57,
	"RESOLVED_WINDOW_FRAME_EXPR":                     58,
	"RESOLVED_DMLVALUE":                              59,
	"RESOLVED_DMLDEFAULT":                            60,
	"RESOLVED_ASSERT_STMT":                           98,
	"RESOLVED_ASSERT_ROWS_MODIFIED":                  61,
	"RESOLVED_INSERT_ROW":                            62,
	"RESOLVED_INSERT_STMT":                           63,
	"RESOLVED_DELETE_STMT":                           64,
	"RESOLVED_UPDATE_ITEM":                           65,
	"RESOLVED_UPDATE_ARRAY_ITEM":                     102,
	"RESOLVED_UPDATE_STMT":                           66,
	"RESOLVED_MERGE_WHEN":                            100,
	"RESOLVED_MERGE_STMT":                            101,
	"RESOLVED_TRUNCATE_STMT":                         133,
	"RESOLVED_PRIVILEGE":                             67,
	"RESOLVED_GRANT_STMT":                            69,
	"RESOLVED_REVOKE_STMT":                           70,
	"RESOLVED_ALTER_DATABASE_STMT":                   134,
	"RESOLVED_ALTER_MATERIALIZED_VIEW_STMT":          127,
	"RESOLVED_ALTER_TABLE_STMT":                      115,
	"RESOLVED_ALTER_VIEW_STMT":                       118,
	"RESOLVED_SET_OPTIONS_ACTION":                    117,
	"RESOLVED_ADD_COLUMN_ACTION":                     131,
	"RESOLVED_DROP_COLUMN_ACTION":                    132,
	"RESOLVED_SET_AS_ACTION":                         156,
	"RESOLVED_ALTER_TABLE_SET_OPTIONS_STMT":          71,
	"RESOLVED_RENAME_STMT":                           72,
	"RESOLVED_CREATE_ROW_ACCESS_POLICY_STMT":         73,
	"RESOLVED_DROP_ROW_ACCESS_POLICY_STMT":           74,
	"RESOLVED_GRANT_TO_ACTION":                       135,
	"RESOLVED_FILTER_USING_ACTION":                   136,
	"RESOLVED_REVOKE_FROM_ACTION":                    137,
	"RESOLVED_RENAME_TO_ACTION":                      138,
	"RESOLVED_ALTER_ROW_ACCESS_POLICY_STMT":          75,
	"RESOLVED_ALTER_ALL_ROW_ACCESS_POLICIES_STMT":    145,
	"RESOLVED_CREATE_CONSTANT_STMT":                  99,
	"RESOLVED_CREATE_FUNCTION_STMT":                  76,
	"RESOLVED_ARGUMENT_DEF":                          77,
	"RESOLVED_ARGUMENT_REF":                          78,
	"RESOLVED_CREATE_TABLE_FUNCTION_STMT":            88,
	"RESOLVED_RELATION_ARGUMENT_SCAN":                89,
	"RESOLVED_ARGUMENT_LIST":                         79,
	"RESOLVED_FUNCTION_SIGNATURE_HOLDER":             84,
	"RESOLVED_DROP_FUNCTION_STMT":                    80,
	"RESOLVED_CALL_STMT":                             83,
	"RESOLVED_IMPORT_STMT":                           86,
	"RESOLVED_MODULE_STMT":                           87,
	"RESOLVED_AGGREGATE_HAVING_MODIFIER":             85,
	"RESOLVED_CREATE_MATERIALIZED_VIEW_STMT":         119,
	"RESOLVED_CREATE_PROCEDURE_STMT":                 125,
	"RESOLVED_EXECUTE_IMMEDIATE_ARGUMENT":            143,
	"RESOLVED_EXECUTE_IMMEDIATE_STMT":                140,
	"RESOLVED_ASSIGNMENT_STMT":                       142,
	"RESOLVED_CREATE_ENTITY_STMT":                    154,
	"RESOLVED_ALTER_ENTITY_STMT":                     155,
	"__ResolvedNodeKind__switch_must_have_default__": -1,
}

func (x ResolvedNodeKind) Enum() *ResolvedNodeKind {
	p := new(ResolvedNodeKind)
	*p = x
	return p
}

func (x ResolvedNodeKind) String() string {
	return proto.EnumName(ResolvedNodeKind_name, int32(x))
}

func (x *ResolvedNodeKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResolvedNodeKind_value, data, "ResolvedNodeKind")
	if err != nil {
		return err
	}
	*x = ResolvedNodeKind(value)
	return nil
}

func (ResolvedNodeKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c5aba04ecd2219e, []int{0}
}

func init() {
	proto.RegisterEnum("zetasql.ResolvedNodeKind", ResolvedNodeKind_name, ResolvedNodeKind_value)
}

func init() {
	proto.RegisterFile("zetasql/resolved_ast/resolved_node_kind.proto", fileDescriptor_8c5aba04ecd2219e)
}

var fileDescriptor_8c5aba04ecd2219e = []byte{
	// 1657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x58, 0xf7, 0x77, 0x1c, 0xb7,
	0x11, 0x7e, 0xfb, 0xd2, 0x37, 0xb1, 0x0d, 0x41, 0x85, 0xea, 0xdd, 0x8a, 0x2c, 0x47, 0xb4, 0xd3,
	0x8b, 0xd3, 0x70, 0xbb, 0x73, 0x7b, 0x10, 0xb1, 0xc0, 0x0a, 0xc0, 0x1e, 0x79, 0x4a, 0x41, 0x18,
	0xf1, 0x2c, 0xe9, 0x99, 0xe2, 0xc5, 0x26, 0x25, 0x27, 0x4e, 0x7f, 0xe9, 0x3d, 0x79, 0xe9, 0xfd,
	0x8f, 0xcc, 0x1f, 0x90, 0x3c, 0x94, 0xbb, 0xdb, 0x39, 0x2e, 0xa3, 0xdf, 0x84, 0xef, 0xc3, 0x70,
	0x66, 0xf0, 0xe1, 0xc3, 0xec, 0xe5, 0xb7, 0xdf, 0x9a, 0x1e, 0x6c, 0xef, 0xbf, 0xbe, 0xfb, 0xd2,
	0x1b, 0xd3, 0xfd, 0xd9, 0xee, 0xd3, 0xe9, 0x8e, 0xdb, 0xde, 0x3f, 0x58, 0xfe, 0x67, 0x6f, 0xb6,
	0x33, 0x75, 0xaf, 0x3d, 0xda, 0xdb, 0x59, 0xff, 0xda, 0x1b, 0xb3, 0x83, 0x19, 0x7d, 0x57, 0xa2,
	0xdf, 0xfa, 0xcf, 0xd5, 0x9c, 0xe8, 0xc4, 0x92, 0xb3, 0x9d, 0xe9, 0xc6, 0xa3, 0xbd, 0x1d, 0x7a,
	0x22, 0x27, 0x1a, 0x8c, 0x12, 0x63, 0x28, 0x9d, 0xe0, 0x16, 0x34, 0x13, 0xe4, 0x6d, 0xf4, 0x54,
	0x4e, 0x17, 0xab, 0x0d, 0xd3, 0xac, 0x06, 0x0b, 0x9a, 0xbc, 0x9d, 0x5e, 0xcc, 0xcf, 0x2e, 0xd6,
	0x61, 0xab, 0xd1, 0x60, 0x0c, 0x57, 0xd2, 0x15, 0x4a, 0xb4, 0xb5, 0x24, 0xef, 0xa0, 0x6b, 0xf9,
	0xf1, 0x05, 0x1e, 0x17, 0x9d, 0x86, 0x21, 0x79, 0x27, 0x3d, 0x99, 0x1f, 0xeb, 0x00, 0xd2, 0x58,
	0x26, 0x2d, 0x79, 0x40, 0x2f, 0xe4, 0xa7, 0x17, 0xcb, 0x66, 0x62, 0x2c, 0xd4, 0x6e, 0xcc, 0x34,
	0x67, 0x03, 0x01, 0xe4, 0x17, 0x19, 0x3d, 0x97, 0x9f, 0x5a, 0xc0, 0x5c, 0x0a, 0x2e, 0xc1, 0x09,
	0x56, 0x0f, 0x4a, 0x46, 0xfe, 0x9d, 0xd1, 0xb3, 0x1d, 0x70, 0xd8, 0xca, 0xc2, 0x86, 0x4c, 0x98,
	0x10, 0xe4, 0xdd, 0xf4, 0x7a, 0x7e, 0x79, 0x81, 0xb1, 0xaa, 0xd2, 0x50, 0x31, 0x0b, 0x2b, 0xac,
	0xf7, 0xd0, 0x6b, 0xf9, 0xa5, 0x25, 0x4b, 0x32, 0x31, 0xb1, 0xbc, 0x58, 0x21, 0xe5, 0xf4, 0x5a,
	0x7e, 0xb1, 0x53, 0xb2, 0x05, 0x59, 0xfa, 0x12, 0x98, 0xb1, 0x0e, 0x04, 0xd4, 0x20, 0x2d, 0xf9,
	0x33, 0x4e, 0x14, 0x91, 0xc8, 0xbf, 0x32, 0x7a, 0x2c, 0x7f, 0x66, 0x59, 0xbb, 0x5f, 0x7b, 0x2f,
	0x3d, 0x9d, 0x9f, 0x58, 0x2c, 0xd5, 0x6c, 0x03, 0x9c, 0xb1, 0xba, 0x2d, 0x2c, 0x79, 0x1f, 0xea,
	0x60, 0x40, 0x1a, 0xad, 0xac, 0x22, 0xcf, 0xd0, 0x0b, 0xf9, 0x99, 0x1e, 0xc0, 0x0d, 0x39, 0x88,
	0x92, 0x3c, 0x8b, 0xe0, 0x0a, 0x6c, 0x0a, 0x98, 0xe0, 0xe7, 0xe8, 0xf9, 0x4e, 0xa3, 0x3d, 0xdc,
	0xdd, 0x4c, 0xe8, 0xc9, 0x8e, 0x08, 0x86, 0x82, 0x59, 0x0b, 0x92, 0xfc, 0x11, 0x57, 0x95, 0x96,
	0x7d, 0xa7, 0x74, 0x45, 0xfe, 0x94, 0xd1, 0xcb, 0xf9, 0xb9, 0x05, 0xa8, 0xa1, 0x11, 0xac, 0x80,
	0x18, 0xcf, 0x71, 0x0b, 0x35, 0xf9, 0x1e, 0xde, 0x8e, 0x18, 0xe4, 0xfb, 0xf8, 0xf4, 0x4c, 0x3b,
	0xb8, 0xdb, 0x82, 0x9e, 0x04, 0x49, 0x91, 0x63, 0x94, 0xe6, 0xcf, 0x2e, 0x4b, 0x55, 0x25, 0x08,
	0xf2, 0x98, 0x9e, 0x46, 0xca, 0x92, 0x12, 0xc2, 0x21, 0x91, 0x5f, 0x65, 0x08, 0x29, 0xc1, 0x14,
	0x9a, 0x37, 0x56, 0x69, 0xf2, 0xdb, 0x0c, 0x15, 0x6d, 0xb8, 0xac, 0x04, 0x38, 0xad, 0x36, 0x9d,
	0x29, 0x98, 0x24, 0xc7, 0x51, 0xa7, 0xad, 0x57, 0x5c, 0x04, 0x4e, 0x20, 0xf1, 0xdf, 0x51, 0x5c,
	0xc6, 0xf5, 0x93, 0x68, 0x03, 0xd3, 0x9a, 0x4d, 0x22, 0x70, 0x0a, 0xd5, 0x92, 0x54, 0x3f, 0x52,
	0xa2, 0x04, 0x4d, 0xd6, 0xd0, 0x49, 0x0f, 0xb9, 0xb0, 0xa0, 0xe3, 0xae, 0xd3, 0xf4, 0x4c, 0x7e,
	0x72, 0x79, 0x24, 0x5a, 0xb5, 0x0d, 0x97, 0x95, 0x33, 0x60, 0xc9, 0x97, 0xe8, 0xb9, 0x7c, 0xad,
	0x47, 0xbe, 0x61, 0xdf, 0x19, 0x7a, 0xa9, 0xd3, 0x78, 0x03, 0xd6, 0xa9, 0x06, 0x34, 0x0b, 0x8a,
	0x0d, 0x8d, 0xff, 0xf2, 0xff, 0x21, 0x84, 0x08, 0x67, 0x51, 0xbe, 0x4a, 0x97, 0xa0, 0xdd, 0x20,
	0xd5, 0x72, 0x0e, 0xdd, 0x70, 0xc1, 0x6b, 0x6e, 0x9d, 0x1a, 0x0e, 0x7d, 0x94, 0x80, 0x9f, 0x47,
	0x7b, 0x37, 0xb9, 0x1d, 0xf9, 0xfb, 0x1d, 0xb1, 0x0b, 0x08, 0x5b, 0xdc, 0xa7, 0x80, 0x5d, 0x44,
	0x7d, 0x30, 0xac, 0x6e, 0xe6, 0xed, 0xbe, 0x84, 0x4e, 0xa9, 0x50, 0x75, 0xd3, 0xda, 0x45, 0x1b,
	0xc9, 0xe5, 0xfe, 0x5c, 0x43, 0xa1, 0x57, 0x50, 0xa1, 0xa9, 0xef, 0x4c, 0x4a, 0x65, 0x43, 0xb1,
	0x86, 0x3c, 0xa4, 0x57, 0x3b, 0x77, 0xb7, 0x02, 0xe9, 0xdb, 0xb0, 0xa4, 0x72, 0x39, 0x54, 0xe4,
	0x11, 0x2a, 0x38, 0x21, 0x25, 0x0c, 0xb9, 0xe4, 0x41, 0x5f, 0x5f, 0x40, 0x89, 0x37, 0x9a, 0xd7,
	0x4c, 0x4f, 0xdc, 0x06, 0x4c, 0xc8, 0x17, 0xf1, 0xd1, 0x2a, 0x0d, 0xbc, 0x92, 0x01, 0xd9, 0x43,
	0x97, 0xb1, 0x18, 0x41, 0xb1, 0x11, 0x3d, 0x4f, 0x33, 0x2e, 0x2d, 0x79, 0x1d, 0xd7, 0xd4, 0xda,
	0xa6, 0xb5, 0xf3, 0x7a, 0xaf, 0x22, 0x55, 0x34, 0x5a, 0xdd, 0x81, 0x22, 0xb5, 0xfe, 0x1a, 0xb2,
	0x6a, 0x3b, 0x1e, 0x86, 0xd5, 0xbb, 0x28, 0xff, 0x85, 0x77, 0x31, 0x5d, 0xb5, 0xc1, 0x9b, 0x34,
	0x0a, 0x08, 0x5b, 0x8d, 0x60, 0x5e, 0xd0, 0xb6, 0xb6, 0xe4, 0x79, 0x24, 0xe8, 0x78, 0x01, 0x03,
	0x70, 0x83, 0x5e, 0xc9, 0x2f, 0x2c, 0xf3, 0xd7, 0xe0, 0xc5, 0x57, 0x32, 0xcb, 0x06, 0xcc, 0x40,
	0xa4, 0x38, 0xb4, 0x97, 0xcb, 0x12, 0xb6, 0xe2, 0xa1, 0x7c, 0x05, 0x75, 0xa5, 0x95, 0x12, 0x8c,
	0x8d, 0xc8, 0x77, 0x70, 0xa7, 0x63, 0xd4, 0xb8, 0x33, 0x84, 0xdc, 0x46, 0x8e, 0x92, 0x70, 0x53,
	0x8c, 0xa0, 0x66, 0x91, 0xf0, 0xcf, 0xac, 0x2f, 0x42, 0xba, 0xb9, 0x9e, 0x70, 0x8f, 0xde, 0xcc,
	0xaf, 0xf7, 0xe3, 0xcc, 0x38, 0x03, 0x22, 0xf4, 0xd2, 0x33, 0x6f, 0xf6, 0x45, 0x0a, 0x4e, 0x13,
	0xf1, 0xd7, 0xf0, 0x09, 0x46, 0x7c, 0xcc, 0x61, 0x33, 0xc2, 0x2f, 0xd0, 0xeb, 0x9d, 0x97, 0x23,
	0xdc, 0x82, 0x86, 0x69, 0xcb, 0xed, 0xf2, 0x2d, 0x34, 0xe4, 0xaf, 0x19, 0x7d, 0x7f, 0x7e, 0x6d,
	0x35, 0x88, 0x7f, 0x1c, 0xb4, 0x64, 0xa2, 0x9b, 0xf7, 0x2d, 0x7a, 0x09, 0x3f, 0xab, 0x4a, 0xdb,
	0x6e, 0x36, 0x7f, 0xc9, 0x50, 0x3a, 0x89, 0xe0, 0x0f, 0x24, 0xe2, 0x2f, 0xa2, 0x6a, 0x82, 0x78,
	0x51, 0x5f, 0x3e, 0x80, 0x04, 0x17, 0x2d, 0x72, 0x90, 0xb0, 0xdb, 0xc8, 0xed, 0xcc, 0x48, 0xa5,
	0x12, 0xd7, 0xd1, 0x01, 0x0f, 0xa0, 0x9a, 0xab, 0xe6, 0x25, 0x24, 0x0e, 0x6f, 0x0c, 0x56, 0x33,
	0x69, 0x58, 0xd4, 0x5d, 0xa0, 0x7c, 0x1d, 0x69, 0xa0, 0x50, 0xb5, 0x77, 0x91, 0x80, 0xbc, 0x8c,
	0x32, 0xd1, 0x4a, 0x88, 0x01, 0x2b, 0x36, 0x22, 0xf6, 0x41, 0x54, 0xa4, 0xb1, 0x4c, 0x5b, 0x37,
	0x60, 0xb6, 0x18, 0x45, 0xf8, 0x2d, 0x64, 0x8a, 0xba, 0x95, 0x5d, 0xf0, 0x9b, 0x68, 0x2f, 0x1b,
	0x28, 0xbc, 0xf7, 0x5b, 0xa8, 0xc8, 0x52, 0xab, 0x26, 0xae, 0x7f, 0x08, 0x09, 0x26, 0xac, 0xd7,
	0xcc, 0x82, 0xe6, 0x4c, 0xf0, 0x7b, 0x50, 0x76, 0x4e, 0xfc, 0x1b, 0x2b, 0xcf, 0x5d, 0xd1, 0x6a,
	0xc3, 0xc7, 0xb0, 0x34, 0xbf, 0xdf, 0xfb, 0xd7, 0x66, 0xad, 0x87, 0x11, 0xd0, 0x3f, 0x64, 0x28,
	0x83, 0xa0, 0x98, 0x00, 0x7c, 0x18, 0xb5, 0x39, 0xac, 0x83, 0xb4, 0x7a, 0x42, 0x3e, 0x42, 0x8f,
	0xe7, 0xcf, 0x2d, 0x4d, 0xa2, 0x09, 0x66, 0xf4, 0x51, 0x7a, 0x39, 0x3f, 0xdf, 0x61, 0xcb, 0x52,
	0x6d, 0x2e, 0x95, 0xc7, 0x65, 0x45, 0x3e, 0x86, 0xdc, 0x34, 0x31, 0x82, 0x6d, 0x7a, 0xf4, 0xe3,
	0xc8, 0x0c, 0x12, 0x3a, 0xf4, 0xd3, 0x1d, 0xf9, 0x04, 0x1e, 0x99, 0x0e, 0x0d, 0x43, 0xe1, 0x81,
	0x22, 0x9f, 0x44, 0x4a, 0xeb, 0x06, 0x88, 0x4f, 0xf7, 0xa7, 0xd0, 0x9c, 0x57, 0xd6, 0x62, 0xcc,
	0x44, 0x0b, 0xe4, 0x15, 0x54, 0x65, 0x59, 0x8b, 0x12, 0x86, 0xac, 0x15, 0x96, 0x7c, 0x1a, 0x29,
	0x85, 0x19, 0x03, 0x3a, 0x29, 0xe5, 0xab, 0x48, 0x66, 0x09, 0xd1, 0x6a, 0xd3, 0xf8, 0x8b, 0xc1,
	0x87, 0x1c, 0x4a, 0xf2, 0x99, 0x15, 0x0f, 0x9a, 0x53, 0xc8, 0x67, 0x51, 0xd4, 0x04, 0x84, 0xa8,
	0x9f, 0x43, 0x48, 0x09, 0x02, 0x6c, 0xba, 0x07, 0x9f, 0xc7, 0xbe, 0xd5, 0x94, 0xc1, 0x9d, 0xbc,
	0x6f, 0x31, 0x54, 0x73, 0x42, 0xe2, 0xf3, 0x1f, 0xf0, 0x57, 0xfb, 0x76, 0x86, 0x98, 0x03, 0x3c,
	0xcc, 0x81, 0xae, 0xc0, 0x6d, 0x8e, 0x40, 0x92, 0x9d, 0x1e, 0x20, 0xec, 0x98, 0xa2, 0x99, 0xc9,
	0xea, 0x56, 0x16, 0x8b, 0x68, 0x3f, 0xc2, 0x1a, 0x6a, 0x34, 0x1f, 0x73, 0x01, 0x15, 0x90, 0x02,
	0x45, 0xab, 0x34, 0x93, 0xa9, 0x5a, 0x40, 0x99, 0x69, 0x18, 0xab, 0x8d, 0x14, 0x6b, 0x48, 0xaf,
	0x74, 0x84, 0xc4, 0xc2, 0x54, 0x82, 0x0d, 0xfe, 0xc7, 0x19, 0x7d, 0x21, 0x7f, 0x7e, 0x85, 0x72,
	0xc4, 0xe5, 0xf8, 0x2e, 0xbe, 0x7d, 0x81, 0xda, 0xb1, 0x9f, 0x7d, 0xa4, 0xc9, 0x08, 0x2f, 0x37,
	0x3f, 0xed, 0x19, 0x57, 0xc2, 0xf3, 0xed, 0xa2, 0xa5, 0x90, 0x27, 0xc8, 0x1d, 0x59, 0xb9, 0x7c,
	0xea, 0x23, 0xfe, 0x03, 0x3c, 0x8a, 0x86, 0x5b, 0x8c, 0x19, 0x3f, 0xc4, 0xa3, 0xa8, 0xff, 0x1b,
	0x6c, 0x11, 0xfe, 0x1f, 0x7d, 0x85, 0xa6, 0xec, 0x3b, 0xc9, 0x84, 0x5c, 0xab, 0x95, 0x86, 0x4a,
	0x2f, 0xfc, 0x80, 0x8c, 0xe8, 0xad, 0xfc, 0xc6, 0xaa, 0xd7, 0xfb, 0x59, 0x93, 0x15, 0x05, 0x18,
	0xe3, 0x1a, 0x25, 0x78, 0x91, 0x9e, 0x57, 0x7e, 0xd8, 0x75, 0x8e, 0x60, 0xde, 0x41, 0xdf, 0x47,
	0xf1, 0x64, 0xad, 0x9a, 0x67, 0xfe, 0x93, 0x0c, 0x9d, 0x62, 0x1a, 0x2e, 0x5b, 0x3f, 0xe8, 0xce,
	0x29, 0x3f, 0x5d, 0x1d, 0xd3, 0x83, 0x04, 0x86, 0x5a, 0xd5, 0x73, 0xc6, 0xcf, 0xfc, 0xa3, 0x7a,
	0x66, 0xb5, 0xa6, 0xe5, 0x1f, 0xf9, 0x79, 0x5f, 0x7b, 0x8e, 0x48, 0x77, 0x83, 0xbe, 0x9c, 0xbf,
	0xb8, 0x42, 0x65, 0x42, 0x1c, 0xa2, 0x73, 0x48, 0xfd, 0xfc, 0x5d, 0xd6, 0x37, 0x69, 0xcc, 0x3f,
	0x0f, 0x23, 0xe7, 0x7e, 0x1f, 0x65, 0x61, 0x4b, 0x81, 0x22, 0x90, 0xad, 0xcd, 0x47, 0x1f, 0xff,
	0x10, 0x92, 0xba, 0x1f, 0xf2, 0xdf, 0xa4, 0xb2, 0xef, 0x79, 0x8e, 0x07, 0x8f, 0xc3, 0x6f, 0xa1,
	0xef, 0x44, 0x0d, 0x82, 0xa1, 0x11, 0x2b, 0x1a, 0xf9, 0x04, 0x0f, 0xbf, 0x73, 0x4c, 0x70, 0x63,
	0x89, 0xa2, 0x37, 0xf2, 0xab, 0x87, 0x67, 0x34, 0xc3, 0x2b, 0xc9, 0x6c, 0xab, 0x61, 0xfe, 0xb1,
	0x60, 0xd1, 0x55, 0x08, 0xc2, 0xc0, 0x99, 0x34, 0xc8, 0x01, 0xfc, 0xf7, 0x69, 0x5c, 0x37, 0xd8,
	0xf0, 0xea, 0x30, 0x1f, 0x04, 0x64, 0x8c, 0xbf, 0x34, 0x55, 0xd9, 0xce, 0x6f, 0xe5, 0x26, 0x4a,
	0x6a, 0xf9, 0x91, 0x31, 0x62, 0x63, 0x2f, 0xa0, 0xe4, 0xb2, 0x9a, 0xb4, 0x7d, 0xca, 0x3e, 0xc2,
	0x08, 0xde, 0x44, 0x03, 0x77, 0xe2, 0x36, 0x5a, 0x15, 0x50, 0xfa, 0x32, 0x03, 0xe7, 0xdb, 0xf4,
	0x66, 0xa7, 0xed, 0xb0, 0x05, 0x45, 0xeb, 0x9d, 0xb6, 0xae, 0xa1, 0xe4, 0xd1, 0x59, 0xd3, 0xe4,
	0xfa, 0x9b, 0x0c, 0x4d, 0x59, 0x87, 0x99, 0x21, 0xdc, 0x2f, 0x33, 0x74, 0x47, 0x98, 0xf1, 0x5d,
	0x8d, 0xc7, 0xe2, 0xe1, 0x5f, 0x67, 0x7d, 0x53, 0x25, 0x48, 0xcb, 0x6d, 0x12, 0xed, 0xdf, 0x32,
	0xec, 0x2f, 0x41, 0xb5, 0x5d, 0xc2, 0xdf, 0x33, 0xfa, 0x4a, 0xbe, 0xee, 0xdc, 0xea, 0x2f, 0x27,
	0xce, 0xed, 0xbf, 0xf9, 0xe8, 0xe0, 0xfe, 0x43, 0xf7, 0xf8, 0xc9, 0xfe, 0x81, 0x7b, 0xb8, 0xfd,
	0x74, 0xea, 0x76, 0xa6, 0xaf, 0x6e, 0x3f, 0xd9, 0x3d, 0x70, 0x8e, 0xfc, 0x77, 0xfe, 0x2f, 0x1b,
	0xdc, 0xce, 0xe9, 0xfd, 0xd9, 0xe3, 0xf5, 0x07, 0xb3, 0xd9, 0x83, 0xdd, 0xe9, 0x7a, 0xfa, 0x2d,
	0x66, 0xb0, 0x76, 0x6f, 0x7a, 0xb0, 0x6d, 0xee, 0x8a, 0xd5, 0xa8, 0xff, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0xaa, 0x06, 0xe3, 0xb7, 0xdd, 0x11, 0x00, 0x00,
}
