// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/public/parse_resume_location.proto

package public

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParseResumeLocationProto struct {
	Filename             *string  `protobuf:"bytes,4,opt,name=filename" json:"filename,omitempty"`
	Input                *string  `protobuf:"bytes,1,opt,name=input" json:"input,omitempty"`
	BytePosition         *int32   `protobuf:"varint,2,opt,name=byte_position,json=bytePosition" json:"byte_position,omitempty"`
	AllowResume          *bool    `protobuf:"varint,3,opt,name=allow_resume,json=allowResume" json:"allow_resume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseResumeLocationProto) Reset()         { *m = ParseResumeLocationProto{} }
func (m *ParseResumeLocationProto) String() string { return proto.CompactTextString(m) }
func (*ParseResumeLocationProto) ProtoMessage()    {}
func (*ParseResumeLocationProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_5edd5daa249e740f, []int{0}
}

func (m *ParseResumeLocationProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseResumeLocationProto.Unmarshal(m, b)
}
func (m *ParseResumeLocationProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseResumeLocationProto.Marshal(b, m, deterministic)
}
func (m *ParseResumeLocationProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseResumeLocationProto.Merge(m, src)
}
func (m *ParseResumeLocationProto) XXX_Size() int {
	return xxx_messageInfo_ParseResumeLocationProto.Size(m)
}
func (m *ParseResumeLocationProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseResumeLocationProto.DiscardUnknown(m)
}

var xxx_messageInfo_ParseResumeLocationProto proto.InternalMessageInfo

func (m *ParseResumeLocationProto) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *ParseResumeLocationProto) GetInput() string {
	if m != nil && m.Input != nil {
		return *m.Input
	}
	return ""
}

func (m *ParseResumeLocationProto) GetBytePosition() int32 {
	if m != nil && m.BytePosition != nil {
		return *m.BytePosition
	}
	return 0
}

func (m *ParseResumeLocationProto) GetAllowResume() bool {
	if m != nil && m.AllowResume != nil {
		return *m.AllowResume
	}
	return false
}

func init() {
	proto.RegisterType((*ParseResumeLocationProto)(nil), "zetasql.ParseResumeLocationProto")
}

func init() {
	proto.RegisterFile("zetasql/public/parse_resume_location.proto", fileDescriptor_5edd5daa249e740f)
}

var fileDescriptor_5edd5daa249e740f = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x65, 0xa0, 0xa2, 0x98, 0x76, 0xb1, 0x18, 0x2c, 0xa6, 0x14, 0x96, 0x88, 0x21, 0x79,
	0x87, 0x0e, 0x4c, 0x1d, 0x42, 0xd8, 0xba, 0x44, 0x4e, 0x38, 0x82, 0x25, 0xdb, 0x67, 0xec, 0xb3,
	0x10, 0x3c, 0x07, 0x0f, 0x8c, 0xe2, 0x5a, 0x48, 0x1d, 0xff, 0xcf, 0x9f, 0xac, 0x4f, 0xc7, 0x9f,
	0x7e, 0x80, 0x54, 0xfc, 0x34, 0xad, 0x4f, 0xa3, 0xd1, 0x53, 0xeb, 0x55, 0x88, 0x30, 0x04, 0x88,
	0xc9, 0xc2, 0x60, 0x70, 0x52, 0xa4, 0xd1, 0x35, 0x3e, 0x20, 0xa1, 0xb8, 0x2e, 0xee, 0xc3, 0x2f,
	0xe3, 0xb2, 0x5b, 0xc4, 0x3e, 0x7b, 0x87, 0xa2, 0x75, 0xd9, 0xba, 0xe7, 0xeb, 0x77, 0x6d, 0xc0,
	0x29, 0x0b, 0xf2, 0xaa, 0x62, 0xf5, 0x4d, 0xff, 0xbf, 0xc5, 0x1d, 0x5f, 0x69, 0xe7, 0x13, 0x49,
	0x96, 0x1f, 0x4e, 0x43, 0x3c, 0xf2, 0xed, 0xf8, 0x4d, 0x30, 0x78, 0x8c, 0x7a, 0xf9, 0x47, 0x5e,
	0x54, 0xac, 0x5e, 0xf5, 0x9b, 0x05, 0x76, 0x85, 0x89, 0x1d, 0xdf, 0x28, 0x63, 0xf0, 0xab, 0xb4,
	0xc9, 0xcb, 0x8a, 0xd5, 0xeb, 0xfe, 0x36, 0xb3, 0x53, 0xc6, 0xfe, 0x99, 0x8b, 0x09, 0x6d, 0x33,
	0x23, 0xce, 0x06, 0x9a, 0x12, 0xbb, 0xdf, 0x1e, 0x81, 0xd4, 0xeb, 0xcb, 0x21, 0x07, 0x87, 0xe3,
	0x6e, 0xd6, 0xf4, 0x91, 0xc6, 0x66, 0x42, 0xdb, 0x2a, 0x1f, 0xc9, 0xbd, 0x8d, 0xed, 0xf9, 0x0d,
	0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x71, 0xf8, 0x51, 0xc4, 0x14, 0x01, 0x00, 0x00,
}
