// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zetasql/public/deprecation_warning.proto

package public

import (
	fmt "fmt"
	error_locationpb "github.com/apstndb/go-zetasql-genproto/zetasql/public/error_locationpb"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeprecationWarning_Kind int32

const (
	DeprecationWarning___Kind__switch_must_have_a_default__ DeprecationWarning_Kind = -1
	DeprecationWarning_UNKNOWN                              DeprecationWarning_Kind = 0
	DeprecationWarning_DEPRECATED_FUNCTION                  DeprecationWarning_Kind = 1
	DeprecationWarning_DEPRECATED_FUNCTION_SIGNATURE        DeprecationWarning_Kind = 2
	DeprecationWarning_PROTO3_FIELD_PRESENCE                DeprecationWarning_Kind = 3
)

var DeprecationWarning_Kind_name = map[int32]string{
	-1: "__Kind__switch_must_have_a_default__",
	0:  "UNKNOWN",
	1:  "DEPRECATED_FUNCTION",
	2:  "DEPRECATED_FUNCTION_SIGNATURE",
	3:  "PROTO3_FIELD_PRESENCE",
}

var DeprecationWarning_Kind_value = map[string]int32{
	"__Kind__switch_must_have_a_default__": -1,
	"UNKNOWN":                              0,
	"DEPRECATED_FUNCTION":                  1,
	"DEPRECATED_FUNCTION_SIGNATURE":        2,
	"PROTO3_FIELD_PRESENCE":                3,
}

func (x DeprecationWarning_Kind) Enum() *DeprecationWarning_Kind {
	p := new(DeprecationWarning_Kind)
	*p = x
	return p
}

func (x DeprecationWarning_Kind) String() string {
	return proto.EnumName(DeprecationWarning_Kind_name, int32(x))
}

func (x *DeprecationWarning_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DeprecationWarning_Kind_value, data, "DeprecationWarning_Kind")
	if err != nil {
		return err
	}
	*x = DeprecationWarning_Kind(value)
	return nil
}

func (DeprecationWarning_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2e0683ed542d717c, []int{0, 0}
}

type DeprecationWarning struct {
	Kind                 *DeprecationWarning_Kind `protobuf:"varint,1,opt,name=kind,enum=zetasql.DeprecationWarning_Kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *DeprecationWarning) Reset()         { *m = DeprecationWarning{} }
func (m *DeprecationWarning) String() string { return proto.CompactTextString(m) }
func (*DeprecationWarning) ProtoMessage()    {}
func (*DeprecationWarning) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0683ed542d717c, []int{0}
}

func (m *DeprecationWarning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeprecationWarning.Unmarshal(m, b)
}
func (m *DeprecationWarning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeprecationWarning.Marshal(b, m, deterministic)
}
func (m *DeprecationWarning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeprecationWarning.Merge(m, src)
}
func (m *DeprecationWarning) XXX_Size() int {
	return xxx_messageInfo_DeprecationWarning.Size(m)
}
func (m *DeprecationWarning) XXX_DiscardUnknown() {
	xxx_messageInfo_DeprecationWarning.DiscardUnknown(m)
}

var xxx_messageInfo_DeprecationWarning proto.InternalMessageInfo

func (m *DeprecationWarning) GetKind() DeprecationWarning_Kind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return DeprecationWarning___Kind__switch_must_have_a_default__
}

type FreestandingDeprecationWarning struct {
	Message              *string                         `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	CaretString          *string                         `protobuf:"bytes,2,opt,name=caret_string,json=caretString" json:"caret_string,omitempty"`
	ErrorLocation        *error_locationpb.ErrorLocation `protobuf:"bytes,3,opt,name=error_location,json=errorLocation" json:"error_location,omitempty"`
	DeprecationWarning   *DeprecationWarning             `protobuf:"bytes,4,opt,name=deprecation_warning,json=deprecationWarning" json:"deprecation_warning,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *FreestandingDeprecationWarning) Reset()         { *m = FreestandingDeprecationWarning{} }
func (m *FreestandingDeprecationWarning) String() string { return proto.CompactTextString(m) }
func (*FreestandingDeprecationWarning) ProtoMessage()    {}
func (*FreestandingDeprecationWarning) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0683ed542d717c, []int{1}
}

func (m *FreestandingDeprecationWarning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreestandingDeprecationWarning.Unmarshal(m, b)
}
func (m *FreestandingDeprecationWarning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreestandingDeprecationWarning.Marshal(b, m, deterministic)
}
func (m *FreestandingDeprecationWarning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreestandingDeprecationWarning.Merge(m, src)
}
func (m *FreestandingDeprecationWarning) XXX_Size() int {
	return xxx_messageInfo_FreestandingDeprecationWarning.Size(m)
}
func (m *FreestandingDeprecationWarning) XXX_DiscardUnknown() {
	xxx_messageInfo_FreestandingDeprecationWarning.DiscardUnknown(m)
}

var xxx_messageInfo_FreestandingDeprecationWarning proto.InternalMessageInfo

func (m *FreestandingDeprecationWarning) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *FreestandingDeprecationWarning) GetCaretString() string {
	if m != nil && m.CaretString != nil {
		return *m.CaretString
	}
	return ""
}

func (m *FreestandingDeprecationWarning) GetErrorLocation() *error_locationpb.ErrorLocation {
	if m != nil {
		return m.ErrorLocation
	}
	return nil
}

func (m *FreestandingDeprecationWarning) GetDeprecationWarning() *DeprecationWarning {
	if m != nil {
		return m.DeprecationWarning
	}
	return nil
}

func init() {
	proto.RegisterEnum("zetasql.DeprecationWarning_Kind", DeprecationWarning_Kind_name, DeprecationWarning_Kind_value)
	proto.RegisterType((*DeprecationWarning)(nil), "zetasql.DeprecationWarning")
	proto.RegisterType((*FreestandingDeprecationWarning)(nil), "zetasql.FreestandingDeprecationWarning")
}

func init() {
	proto.RegisterFile("zetasql/public/deprecation_warning.proto", fileDescriptor_2e0683ed542d717c)
}

var fileDescriptor_2e0683ed542d717c = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x27, 0x5b, 0xa5, 0x0a, 0x17, 0xa6, 0xc8, 0x13, 0x10, 0x40, 0xa0, 0x76, 0x70, 0xe8, 0x29,
	0x11, 0x83, 0x2b, 0x87, 0xad, 0x71, 0x51, 0xb5, 0x2a, 0x09, 0x6e, 0xaa, 0x49, 0x5c, 0x9e, 0xdc,
	0xc4, 0xa4, 0x16, 0x89, 0x1d, 0x6c, 0x87, 0x49, 0x7c, 0x17, 0xbe, 0x20, 0x5f, 0x02, 0x94, 0xb4,
	0x05, 0x46, 0xab, 0xf9, 0xe4, 0xf7, 0x7e, 0x7f, 0xa4, 0xdf, 0x7b, 0x0f, 0x8d, 0xbf, 0x73, 0xcb,
	0xcc, 0xd7, 0x32, 0xa8, 0x9b, 0x55, 0x29, 0xb2, 0x20, 0xe7, 0xb5, 0xe6, 0x19, 0xb3, 0x42, 0x49,
	0xb8, 0x61, 0x5a, 0x0a, 0x59, 0xf8, 0xb5, 0x56, 0x56, 0xe1, 0xfe, 0x96, 0xf9, 0xec, 0xd5, 0x7f,
	0x12, 0xae, 0xb5, 0xd2, 0x50, 0xaa, 0x8d, 0x6a, 0xc3, 0x3e, 0xfb, 0xe9, 0x20, 0x1c, 0xfe, 0xf5,
	0xba, 0xde, 0x58, 0xe1, 0x77, 0xa8, 0xf7, 0x45, 0xc8, 0xdc, 0x73, 0x86, 0xce, 0xf8, 0xe4, 0x7c,
	0xe8, 0x6f, 0xad, 0xfc, 0x7d, 0xaa, 0x7f, 0x25, 0x64, 0x4e, 0x3b, 0xf6, 0xd9, 0x0f, 0x07, 0xf5,
	0xda, 0x12, 0xbf, 0x41, 0xaf, 0x01, 0xda, 0x1f, 0x80, 0xb9, 0x11, 0x36, 0x5b, 0x43, 0xd5, 0x18,
	0x0b, 0x6b, 0xf6, 0x8d, 0x03, 0x83, 0x9c, 0x7f, 0x66, 0x4d, 0x69, 0x01, 0xdc, 0x5f, 0xbb, 0xe7,
	0xe0, 0x01, 0xea, 0x2f, 0xa3, 0xab, 0x28, 0xbe, 0x8e, 0xdc, 0x7b, 0xf8, 0x09, 0x3a, 0x0d, 0x49,
	0x42, 0xc9, 0xe4, 0x22, 0x25, 0x21, 0x4c, 0x97, 0xd1, 0x24, 0x9d, 0xc5, 0x91, 0xeb, 0xe0, 0x11,
	0x7a, 0x71, 0x00, 0x80, 0xc5, 0xec, 0x43, 0x74, 0x91, 0x2e, 0x29, 0x71, 0x8f, 0xf0, 0x53, 0xf4,
	0x28, 0xa1, 0x71, 0x1a, 0xbf, 0x85, 0xe9, 0x8c, 0xcc, 0x43, 0x48, 0x28, 0x59, 0x90, 0x68, 0x42,
	0xdc, 0xe3, 0x36, 0xec, 0xcb, 0xa9, 0xe6, 0xdc, 0x58, 0x26, 0x73, 0x21, 0x8b, 0x03, 0xc1, 0x3d,
	0xd4, 0xaf, 0xb8, 0x31, 0xac, 0xe0, 0x5d, 0xf6, 0xfb, 0x74, 0x57, 0xe2, 0x11, 0x7a, 0x90, 0x31,
	0xcd, 0x2d, 0x18, 0xab, 0x85, 0x2c, 0xbc, 0xa3, 0x0e, 0x1e, 0x74, 0xbd, 0x45, 0xd7, 0xc2, 0xef,
	0xd1, 0xc9, 0xed, 0x21, 0x7b, 0xc7, 0x43, 0x67, 0x3c, 0x38, 0x7f, 0xfc, 0x67, 0x7e, 0xa4, 0x85,
	0xe7, 0x5b, 0x94, 0x3e, 0xe4, 0xff, 0x96, 0x78, 0x8e, 0x4e, 0x0f, 0xac, 0xd5, 0xeb, 0x75, 0x1e,
	0xcf, 0xef, 0xd8, 0x01, 0xc5, 0xf9, 0x5e, 0xef, 0xf2, 0x23, 0xc2, 0x99, 0xaa, 0xfc, 0x42, 0xa9,
	0xa2, 0xe4, 0x3b, 0xf1, 0xa5, 0xb7, 0xaf, 0x4e, 0xda, 0x43, 0x30, 0x9f, 0x46, 0x85, 0xb0, 0xeb,
	0x66, 0xe5, 0x67, 0xaa, 0x0a, 0x58, 0x6d, 0xac, 0xcc, 0x57, 0xc1, 0xed, 0x0b, 0xfa, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x14, 0x60, 0x5b, 0xb9, 0x85, 0x02, 0x00, 0x00,
}
